.TH PURIFY "26" "February 2019" "purify 3.0.1" "User Commands"
.SH NAME
purify \- Reconstruct images from radio interferometers using PADMM
.SH SYNOPSIS
.B
purify [CONFIGFILE]
.SH DESCRIPTION
PURIFY is a tool for radio interferometric imaging including file handling
(for both visibilities and fits files), implementation of the measurement
operator and set-up of the different optimization problems used for image
deconvolution.
.PP
The code is given for educational purpose. The code is in beta and still under
development.
.SH OPTIONS
purify only requires a config yaml file with all the details needed to run it.
Details about how to create such file are available in the source or online at
https://github.com/astro-informatics/purify/blob/development/data/config/config.yaml
.SH AUTHORS
PURIFY was initially created by Rafael Carrillo, Jason McEwen and Yves Wiaux
but major contributions have since been made by a number of others. The full
list of contributors is as follows: Rafael E. Carrillo, Jason D. McEwen, Yves
Wiaux, Luke Pratley, Mayeul d'Avezac, Ilektra Christidi, Roland Guichard and
David Perez-Suarez.
.SH BUGS
If you have any questions or comments, feel free to contact Rafael Carrillo or
Jason McEwen, or add an issue in the issue tracker
https://github.com/astro-informatics/purify/issues
.SH LICENSE
PURIFY Copyright (C) 2013 Rafael Carrillo, Jason McEwen, Yves Wiaux
.PP
This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 2 of the License, or (at your
option) any later version.
.PP
This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General
Public License for more details.
