PURIFY: /mydata/cpp/benchmarks/measurement_operator.cc File Reference
measurement_operator.cc File Reference
#include <chrono>
#include <benchmark/benchmark.h>
#include "benchmarks/utilities.h"
#include "purify/operators.h"
Classes
class DegridOperatorFixture
class DegridOperatorDirectFixture
class DegridOperatorAdjointFixture
Functions
void degrid_operator_ctor (benchmark::State &state)
BENCHMARK_DEFINE_F (DegridOperatorDirectFixture, Apply)(benchmark
BENCHMARK_DEFINE_F (DegridOperatorAdjointFixture, Apply)(benchmark
Args ({1024, 1000000, 4}) -> Args(
UseManualTime () -> Repetitions(10) ->Unit(benchmark::kMillisecond)
BENCHMARK_MAIN ()
Function Documentation
Args()
Args ({1024, 1000000, 4}) -> Args(
Definition at line 141 of file measurement_operator.cc.
References BENCHMARK_MAIN(), and UseManualTime().
            {1024, 1000000, 4})
     ->Args({1024, 10000000, 4})
BENCHMARK_DEFINE_F() [1/2]
BENCHMARK_DEFINE_F (DegridOperatorDirectFixture , Apply)
Definition at line 107 of file measurement_operator.cc.
References b_utilities::duration().
{
   // Benchmark the application of the operator
   if ((m_counter % 10) == 1) {
     m_uv_data.vis = (*m_degridOperator) * Image<t_complex>::Map(m_image.data(), m_image.size(), 1);
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     m_uv_data.vis = (*m_degridOperator) * Image<t_complex>::Map(m_image.data(), m_image.size(), 1);
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizey * m_imsizex) *
                           sizeof(t_complex));
 }
BENCHMARK_DEFINE_F() [2/2]
BENCHMARK_DEFINE_F (DegridOperatorAdjointFixture , Apply)
Definition at line 123 of file measurement_operator.cc.
References b_utilities::duration().
{
   // Benchmark the application of the adjoint operator
   if ((m_counter % 10) == 1) {
     m_image = m_degridOperator->adjoint() * m_uv_data.vis;
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     m_image = m_degridOperator->adjoint() * m_uv_data.vis;
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizey * m_imsizex) *
                           sizeof(t_complex));
 }
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
Referenced by Args().
degrid_operator_ctor()
void degrid_operator_ctor (benchmark::State & state)
Definition at line 10 of file measurement_operator.cc.
References cols, b_utilities::duration(), purify::kernels::kb, b_utilities::random_measurements(), and rows.
{
   // Generating random uv(w) coverage
   t_int const rows = state.range(0);
   t_int const cols = state.range(0);
   t_int const number_of_vis = state.range(1);
   auto uv_data = b_utilities::random_measurements(number_of_vis);
   const t_real FoV = 1;  // deg
   const t_real cellsize = FoV / cols * 60. * 60.;
   const bool w_term = false;
   // Keep count of the benchmark repetitions
   static t_uint counter = 0;
   counter++;
   // benchmark the creation of measurement operator
   if ((counter % 10) == 1) {
     auto sky_measurements = measurementoperator::init_degrid_operator_2d<Vector<t_complex>>(
         uv_data, rows, cols, cellsize, cellsize, 2, kernels::kernel::kb, state.range(2),
         state.range(2), w_term);
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     auto sky_measurements = measurementoperator::init_degrid_operator_2d<Vector<t_complex>>(
         uv_data, rows, cols, cellsize, cellsize, 2, kernels::kernel::kb, state.range(2),
         state.range(2), w_term);
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (number_of_vis + rows * cols) *
                           sizeof(t_complex));
 }
UseManualTime()
UseManualTime () -> Repetitions(10) ->Unit(benchmark::kMillisecond)
Referenced by Args(), and BENCHMARK_DEFINE_F().