PURIFY: DegridOperatorFixturePar Class Reference
DegridOperatorFixturePar Class Reference abstract
Public Member Functions
void SetUp (const ::benchmark::State &state)
void TearDown (const ::benchmark::State &state)
virtual bool updateImage (t_uint newSize)=0
virtual std::shared_ptr< sopt::LinearTransform< Vector< t_complex > > const > measurementOperator (t_real cellsize, bool w_term)=0
Public Attributes
t_uint m_counter
sopt::mpi::Communicator m_world
t_uint m_kernel
t_uint m_imsizex
t_uint m_imsizey
utilities::vis_params m_uv_data
std::shared_ptr< sopt::LinearTransform< Vector< t_complex > > const > m_degridOperator
Detailed Description
Definition at line 91 of file measurement_operator_mpi.cc.
Member Function Documentation
measurementOperator()
virtual std::shared_ptr<sopt::LinearTransform<Vector<t_complex> > const> DegridOperatorFixturePar::measurementOperator (t_real cellsize, bool w_term) pure virtual
Implemented in DegridOperatorAdjointFixtureMPI, DegridOperatorAdjointFixtureDistr, DegridOperatorDirectFixtureMPI, and DegridOperatorDirectFixtureDistr.
SetUp()
void DegridOperatorFixturePar::SetUp (const ::benchmark::State & state) inline
Definition at line 93 of file measurement_operator_mpi.cc.
References b_utilities::updateImage(), and b_utilities::updateMeasurements().
{
     // Keep count of the benchmark repetitions
     m_counter++;
     // Reading image from file and create temporary image
     bool newImage = updateImage(state.range(0));
     // Generating random uv(w) coverage
     bool newMeasurements = b_utilities::updateMeasurements(state.range(1), m_uv_data, m_world);
     // Create measurement operators
     bool newKernel = m_kernel != state.range(2);
     if (newImage || newMeasurements || newKernel) {
       const t_real FoV = 1;  // deg
       const t_real cellsize = FoV / m_imsizex * 60. * 60.;
       const bool w_term = false;
       m_kernel = state.range(2);
       m_degridOperator = measurementOperator(cellsize, w_term);
     }
   }
TearDown()
void DegridOperatorFixturePar::TearDown (const ::benchmark::State & state) inline
Definition at line 114 of file measurement_operator_mpi.cc.
References b_utilities::updateImage().
 {}
updateImage()
virtual bool DegridOperatorFixturePar::updateImage (t_uint newSize) pure virtual
Implemented in DegridOperatorAdjointFixturePar, and DegridOperatorDirectFixturePar.
Member Data Documentation
m_counter
t_uint DegridOperatorFixturePar::m_counter
Definition at line 120 of file measurement_operator_mpi.cc.
m_degridOperator
std::shared_ptr<sopt::LinearTransform<Vector<t_complex> > const> DegridOperatorFixturePar::m_degridOperator
Definition at line 129 of file measurement_operator_mpi.cc.
m_imsizex
t_uint DegridOperatorFixturePar::m_imsizex
Definition at line 124 of file measurement_operator_mpi.cc.
m_imsizey
t_uint DegridOperatorFixturePar::m_imsizey
Definition at line 125 of file measurement_operator_mpi.cc.
m_kernel
t_uint DegridOperatorFixturePar::m_kernel
Definition at line 122 of file measurement_operator_mpi.cc.
m_uv_data
utilities::vis_params DegridOperatorFixturePar::m_uv_data
Definition at line 127 of file measurement_operator_mpi.cc.
m_world
sopt::mpi::Communicator DegridOperatorFixturePar::m_world
Definition at line 121 of file measurement_operator_mpi.cc.
The documentation for this class was generated from the following file:
/mydata/cpp/benchmarks/measurement_operator_mpi.cc