PURIFY: DegridOperatorCtorFixturePar Class Reference
DegridOperatorCtorFixturePar Class Reference
Public Member Functions
void SetUp (const ::benchmark::State &state)
void TearDown (const ::benchmark::State &state)
void SetUp (const ::benchmark::State &state)
void TearDown (const ::benchmark::State &state)
Public Attributes
t_uint m_counter
sopt::mpi::Communicator m_world
t_uint m_imsizex
t_uint m_imsizey
utilities::vis_params m_uv_data
t_real m_cellsize
bool m_w_term
utilities::vis_params m_uv_data_all_to_all
std::vector< t_real > m_w_stacks
std::vector< t_int > m_image_index
Detailed Description
Definition at line 18 of file measurement_operator_mpi.cc.
Member Function Documentation
SetUp() [1/2]
void DegridOperatorCtorFixturePar::SetUp (const ::benchmark::State & state) inline
Definition at line 20 of file measurement_operator_mpi.cc.
{
     // Keep count of the benchmark repetitions
     m_counter++;
     m_imsizex = state.range(0);
     m_imsizey = state.range(0);
     // Generating random uv(w) coverage
     bool newMeasurements = m_uv_data.size() != state.range(1);
     if (newMeasurements) {
       t_real const sigma_m = constant::pi / 3;
       m_uv_data = utilities::random_sample_density(state.range(1), 0, sigma_m);
     }
     // Data needed for the creation of the measurement operator
     const t_real FoV = 1;  // deg
     m_cellsize = FoV / m_imsizex * 60. * 60.;
     m_w_term = false;
   }
References purify::constant::pi, and purify::utilities::random_sample_density().
SetUp() [2/2]
void DegridOperatorCtorFixturePar::SetUp (const ::benchmark::State & state) inline
Definition at line 22 of file measurement_operator_wproj.cc.
{
     // Keep count of the benchmark repetitions
     m_counter++;
     // Data needed for the creation of the measurement operator
     const t_real FoV = 25;  // deg
     m_cellsize = FoV / m_imsizex * 60. * 60.;
     m_w_term = true;
     m_imsizex = state.range(0);
     m_imsizey = state.range(0);
     // Generating random uv(w) coverage
     b_utilities::update_comm(m_world);
     t_real const sigma_m = constant::pi / 3;
     const t_real du = widefield::pixel_to_lambda(m_cellsize, m_imsizex, 2);
     const t_real max_w = 300.;  // lambda
     auto const uv_data = b_utilities::random_measurements(state.range(1), max_w, m_world.rank());
     const auto cost = [](t_real x) -> t_real { return std::abs(x * x); };
     m_uv_data = utilities::w_stacking(uv_data, m_world, 100, cost);
     std::tie(m_uv_data_all_to_all, m_image_index, m_w_stacks) =
         utilities::w_stacking_with_all_to_all(uv_data, du, 4, 100, m_world, 100, 1.01, cost);
   }
References purify::constant::pi, purify::widefield::pixel_to_lambda(), b_utilities::random_measurements(), purify::utilities::w_stacking(), and purify::utilities::w_stacking_with_all_to_all().
TearDown() [1/2]
void DegridOperatorCtorFixturePar::TearDown (const ::benchmark::State & state) inline
Definition at line 40 of file measurement_operator_mpi.cc.
 {}
TearDown() [2/2]
void DegridOperatorCtorFixturePar::TearDown (const ::benchmark::State & state) inline
Definition at line 45 of file measurement_operator_wproj.cc.
 {}
Member Data Documentation
m_cellsize
t_real DegridOperatorCtorFixturePar::m_cellsize
Definition at line 47 of file measurement_operator_mpi.cc.
m_counter
t_uint DegridOperatorCtorFixturePar::m_counter
Definition at line 42 of file measurement_operator_mpi.cc.
m_image_index
std::vector<t_int> DegridOperatorCtorFixturePar::m_image_index
Definition at line 54 of file measurement_operator_wproj.cc.
m_imsizex
t_uint DegridOperatorCtorFixturePar::m_imsizex
Definition at line 44 of file measurement_operator_mpi.cc.
m_imsizey
t_uint DegridOperatorCtorFixturePar::m_imsizey
Definition at line 45 of file measurement_operator_mpi.cc.
m_uv_data
utilities::vis_params DegridOperatorCtorFixturePar::m_uv_data
Definition at line 46 of file measurement_operator_mpi.cc.
m_uv_data_all_to_all
utilities::vis_params DegridOperatorCtorFixturePar::m_uv_data_all_to_all
Definition at line 52 of file measurement_operator_wproj.cc.
m_w_stacks
std::vector<t_real> DegridOperatorCtorFixturePar::m_w_stacks
Definition at line 53 of file measurement_operator_wproj.cc.
m_w_term
bool DegridOperatorCtorFixturePar::m_w_term
Definition at line 48 of file measurement_operator_mpi.cc.
m_world
sopt::mpi::Communicator DegridOperatorCtorFixturePar::m_world
Definition at line 43 of file measurement_operator_mpi.cc.
The documentation for this class was generated from the following files:
/home/runner/work/purify/purify/cpp/benchmarks/measurement_operator_mpi.cc
/home/runner/work/purify/purify/cpp/benchmarks/measurement_operator_wproj.cc