PURIFY: PadmmFixtureMPI Class Reference
PadmmFixtureMPI Class Reference
Public Member Functions
void SetUp (const ::benchmark::State &state)
void TearDown (const ::benchmark::State &state)
Public Attributes
sopt::mpi::Communicator m_world
const sopt::wavelets::SARA m_sara
Image< t_complex > m_image
t_uint m_imsizex
t_uint m_imsizey
utilities::vis_params m_uv_data
t_real m_epsilon
t_uint m_kernel
std::shared_ptr< sopt::LinearTransform< Vector< t_complex > > const > m_measurements1
std::shared_ptr< sopt::LinearTransform< Vector< t_complex > > const > m_measurements3
Detailed Description
Definition at line 22 of file padmm_mpi.cc.
Member Function Documentation
SetUp()
void PadmmFixtureMPI::SetUp (const ::benchmark::State & state) inline
Definition at line 24 of file padmm_mpi.cc.
{
     // Reading image from file and update related quantities
     bool newImage = b_utilities::updateImage(state.range(0), m_image, m_imsizex, m_imsizey);
     // Generating random uv(w) coverage
     bool newMeasurements = m_uv_data.size() != state.range(1);
     if (newMeasurements) {
       t_real const sigma_m = constant::pi / 3;
       m_uv_data = utilities::random_sample_density(state.range(1), 0, sigma_m);
     }
     bool newKernel = m_kernel != state.range(2);
     if (newImage || newMeasurements || newKernel) {
       m_kernel = state.range(2);
       // creating the measurement operator
       const t_real FoV = 1;  // deg
       const t_real cellsize = FoV / m_imsizex * 60. * 60.;
       const bool w_term = false;
       // algorithm 1
       if (state.range(4) == 1)
         m_measurements1 = measurementoperator::init_degrid_operator_2d_mpi<Vector<t_complex>>(
             m_world, m_uv_data, m_image.rows(), m_image.cols(), cellsize, cellsize, 2,
             kernels::kernel::kb, m_kernel, m_kernel, w_term);
       // algorithm 3
       if (state.range(4) == 3)
         m_measurements3 = measurementoperator::init_degrid_operator_2d<Vector<t_complex>>(
             m_world, m_uv_data, m_image.rows(), m_image.cols(), cellsize, cellsize, 2,
             kernels::kernel::kb, m_kernel, m_kernel, w_term);
     }
   }
References purify::measurementoperator::init_degrid_operator_2d(), purify::kernels::kb, purify::constant::pi, purify::utilities::random_sample_density(), and b_utilities::updateImage().
TearDown()
void PadmmFixtureMPI::TearDown (const ::benchmark::State & state) inline
Definition at line 55 of file padmm_mpi.cc.
 {}
Member Data Documentation
m_epsilon
t_real PadmmFixtureMPI::m_epsilon
Definition at line 69 of file padmm_mpi.cc.
m_image
Image<t_complex> PadmmFixtureMPI::m_image
Definition at line 64 of file padmm_mpi.cc.
m_imsizex
t_uint PadmmFixtureMPI::m_imsizex
Definition at line 65 of file padmm_mpi.cc.
m_imsizey
t_uint PadmmFixtureMPI::m_imsizey
Definition at line 66 of file padmm_mpi.cc.
m_kernel
t_uint PadmmFixtureMPI::m_kernel
Definition at line 71 of file padmm_mpi.cc.
m_measurements1
std::shared_ptr<sopt::LinearTransform<Vector<t_complex> > const> PadmmFixtureMPI::m_measurements1
Definition at line 72 of file padmm_mpi.cc.
m_measurements3
std::shared_ptr<sopt::LinearTransform<Vector<t_complex> > const> PadmmFixtureMPI::m_measurements3
Definition at line 73 of file padmm_mpi.cc.
m_sara
const sopt::wavelets::SARA PadmmFixtureMPI::m_sara
Initial value:
{
      std::make_tuple("Dirac", 3u), std::make_tuple("DB1", 3u), std::make_tuple("DB2", 3u),
      std::make_tuple("DB3", 3u),   std::make_tuple("DB4", 3u), std::make_tuple("DB5", 3u),
      std::make_tuple("DB6", 3u),   std::make_tuple("DB7", 3u), std::make_tuple("DB8", 3u)}
Definition at line 59 of file padmm_mpi.cc.
m_uv_data
utilities::vis_params PadmmFixtureMPI::m_uv_data
Definition at line 68 of file padmm_mpi.cc.
m_world
sopt::mpi::Communicator PadmmFixtureMPI::m_world
Definition at line 57 of file padmm_mpi.cc.
The documentation for this class was generated from the following file:
/home/runner/work/purify/purify/cpp/benchmarks/padmm_mpi.cc