PURIFY: DegridOperatorFixture Class Reference
DegridOperatorFixture Class Reference abstract
Public Member Functions
void SetUp (const ::benchmark::State &state)
void TearDown (const ::benchmark::State &state)
virtual bool updateImage (t_uint newSize)=0
void SetUp (const ::benchmark::State &state)
void TearDown (const ::benchmark::State &state)
virtual bool updateImage (t_uint newSize)=0
Public Attributes
t_uint m_counter
t_uint m_imsizex
t_uint m_imsizey
utilities::vis_params m_uv_data
t_uint m_kernel
std::shared_ptr< sopt::LinearTransform< Vector< t_complex > > const > m_degridOperator
Detailed Description
Definition at line 45 of file measurement_operator.cc.
Member Function Documentation
SetUp() [1/2]
void DegridOperatorFixture::SetUp (const ::benchmark::State & state) inline
Definition at line 47 of file measurement_operator.cc.
{
     // Keep count of the benchmark repetitions
     m_counter++;
     // Reading image from file and create temporary image
     bool newImage = updateImage(state.range(0));
     // Generating random uv(w) coverage
     bool newMeasurements = m_uv_data.size() != state.range(1);
     if (newMeasurements) {
       t_real const sigma_m = constant::pi / 3;
       m_uv_data = utilities::random_sample_density(state.range(1), 0, sigma_m);
     }
     // Create measurement operator
     bool newKernel = m_kernel != state.range(2);
     if (newImage || newMeasurements || newKernel) {
       const t_real FoV = 1;  // deg
       const t_real cellsize = FoV / m_imsizex * 60. * 60.;
       const bool w_term = false;
       m_kernel = state.range(2);
       m_degridOperator = measurementoperator::init_degrid_operator_2d<Vector<t_complex>>(
           m_uv_data, m_imsizey, m_imsizex, cellsize, cellsize, 2, kernels::kernel::kb, m_kernel,
           m_kernel, w_term);
     }
   }
References purify::kernels::kb, purify::constant::pi, purify::utilities::random_sample_density(), and b_utilities::updateImage().
SetUp() [2/2]
void DegridOperatorFixture::SetUp (const ::benchmark::State & state) inline
Definition at line 55 of file measurement_operator_af.cc.
{
     af::setDevice(0);
     af::setBackend(AF_BACKEND_CUDA);
     // Keep count of the benchmark repetitions
     m_counter++;
     // Reading image from file and create temporary image
     bool newImage = updateImage(state.range(0));
     // Generating random uv(w) coverage
     bool newMeasurements = b_utilities::updateMeasurements(state.range(1), m_uv_data);
     // Create measurement operator
     bool newKernel = m_kernel != state.range(2);
     if (newImage || newMeasurements || newKernel) {
       const t_real FoV = 1;  // deg
       const t_real cellsize = FoV / m_imsizex * 60. * 60.;
       const bool w_term = false;
       m_kernel = state.range(2);
 #ifdef PURIFY_CPU
       m_degridOperator = measurementoperator::init_degrid_operator_2d<Vector<t_complex>>(
           m_uv_data, m_imsizey, m_imsizex, cellsize, cellsize, 2, kernels::kernel::kb, m_kernel,
           m_kernel, w_term);
 #else
       m_degridOperator = gpu::measurementoperator::init_degrid_operator_2d(
           m_uv_data, m_imsizey, m_imsizex, cellsize, cellsize, 2, kernels::kernel::kb, m_kernel,
           m_kernel, w_term);
 #endif
     }
   }
References purify::measurementoperator::init_degrid_operator_2d(), purify::kernels::kb, b_utilities::updateImage(), and b_utilities::updateMeasurements().
TearDown() [1/2]
void DegridOperatorFixture::TearDown (const ::benchmark::State & state) inline
Definition at line 74 of file measurement_operator.cc.
 {}
TearDown() [2/2]
void DegridOperatorFixture::TearDown (const ::benchmark::State & state) inline
Definition at line 86 of file measurement_operator_af.cc.
 {}
updateImage() [1/2]
virtual bool DegridOperatorFixture::updateImage (t_uint newSize) pure virtual
Implemented in DegridOperatorAdjointFixture, DegridOperatorDirectFixture, DegridOperatorAdjointFixture, and DegridOperatorDirectFixture.
updateImage() [2/2]
virtual bool DegridOperatorFixture::updateImage (t_uint newSize) pure virtual
Implemented in DegridOperatorAdjointFixture, DegridOperatorDirectFixture, DegridOperatorAdjointFixture, and DegridOperatorDirectFixture.
Member Data Documentation
m_counter
t_uint DegridOperatorFixture::m_counter
Definition at line 78 of file measurement_operator.cc.
m_degridOperator
std::shared_ptr< sopt::LinearTransform< Vector< t_complex > > const > DegridOperatorFixture::m_degridOperator
Definition at line 86 of file measurement_operator.cc.
m_imsizex
t_uint DegridOperatorFixture::m_imsizex
Definition at line 80 of file measurement_operator.cc.
m_imsizey
t_uint DegridOperatorFixture::m_imsizey
Definition at line 81 of file measurement_operator.cc.
m_kernel
t_uint DegridOperatorFixture::m_kernel
Definition at line 85 of file measurement_operator.cc.
m_uv_data
utilities::vis_params DegridOperatorFixture::m_uv_data
Definition at line 83 of file measurement_operator.cc.
The documentation for this class was generated from the following files:
/home/runner/work/purify/purify/cpp/benchmarks/measurement_operator.cc
/home/runner/work/purify/purify/cpp/benchmarks/measurement_operator_af.cc