PURIFY: purify::casa::MeasurementSet Class Reference
purify::casa::MeasurementSet Class Reference
Interface around measurement sets.
#include <casacore.h>
Classes
class ChannelWrapper
class const_iterator
Public Types
typedef Eigen::Array< t_real, 2, 1 > Direction
Type for (RA, DEC) direction.
Public Member Functions
MeasurementSet (std::string const filename)
Constructs the interface around a given measurement set.
MeasurementSet (MeasurementSet const &c)
Shallow measurement set copy.
std::string const & filename () const
Filename of the measurement set.
MeasurementSet & filename (std::string const &filename)
Set new filename.
::casacore::Table const & table (std::string const &name="") const
Gets table or subtable.
template<class T >
::casacore::ScalarColumn< T > scalar_column (std::string const &col, std::string const &tabname="") const
Gets scalar column from table.
template<class T >
::casacore::ArrayColumn< T > array_column (std::string const &col, std::string const &tabname="") const
Gets array column from table.
void clear ()
Clear memory.
template<class T >
Matrix< T > column (std::string const &column, std::string const &filter="") const
Data from a column.
std::size_t size () const
Number of channels in the measurement set.
const_iterator begin (std::string const &filter="") const
Iterates over channels.
const_iterator end (std::string const &filter="") const
Iterates over channels.
ChannelWrapper operator[] (t_uint i) const
Returns wrapper over specific channel.
ChannelWrapper operator[] (std::tuple< t_uint, std::string > const &i) const
Returns wrapper over specific channel.
Direction direction (t_real tolerance=1e-8, std::string const &filter="") const
Direction (RA, DEC) in radians.
Direction::Scalar right_ascension (t_real tolerance=1e-8, std::string const &filter="") const
Right ascention in radians.
Direction::Scalar declination (t_real tolerance=1e-8, std::string const &filter="") const
Declination in radians.
Static Public Attributes
static std::string const default_filter = "WHERE NOT ANY(FLAG)"
Default filter specifying which data to accept.
Detailed Description
Interface around measurement sets.
Definition at line 27 of file casacore.h.
Member Typedef Documentation
Direction
typedef Eigen::Array<t_real, 2, 1> purify::casa::MeasurementSet::Direction
Type for (RA, DEC) direction.
Definition at line 35 of file casacore.h.
Constructor & Destructor Documentation
MeasurementSet() [1/2]
purify::casa::MeasurementSet::MeasurementSet (std::string const filename) inline
Constructs the interface around a given measurement set.
Definition at line 38 of file casacore.h.
       : filename_(filename),
         tables_(std::make_shared<std::map<std::string, ::casacore::Table>>()){};
MeasurementSet() [2/2]
purify::casa::MeasurementSet::MeasurementSet (MeasurementSet const & c) inline
Shallow measurement set copy.
Definition at line 42 of file casacore.h.
 : filename_(c.filename_), tables_(c.tables_){};
Member Function Documentation
array_column()
template<class T > ::casacore::ArrayColumn<T> purify::casa::MeasurementSet::array_column (std::string const & col, std::string const & tabname = "") const inline
Gets array column from table.
Definition at line 59 of file casacore.h.
{
     return get_column<T, ::casacore::ArrayColumn>(col, tabname);
   }
begin()
MeasurementSet::const_iterator purify::casa::MeasurementSet::begin (std::string const & filter = "") const
Iterates over channels.
Definition at line 37 of file casacore.cc.
{
   return const_iterator(0, *this, filter);
 }
clear()
void purify::casa::MeasurementSet::clear () inline
Clear memory.
Definition at line 64 of file casacore.h.
 { tables_ = std::make_shared<std::map<std::string, ::casacore::Table>>(); }
Referenced by filename().
column()
template<class T > Matrix<T> purify::casa::MeasurementSet::column (std::string const & column, std::string const & filter = "") const inline
Data from a column.
Definition at line 68 of file casacore.h.
{
     return table_column<T>(this->table(), column, filter);
   }
References table().
Referenced by purify::casa::MeasurementSet::ChannelWrapper::data_desc_id(), purify::casa::MeasurementSet::ChannelWrapper::field_ids(), and size().
declination()
Direction::Scalar purify::casa::MeasurementSet::declination (t_real tolerance = 1e-8, std::string const & filter = "") const inline
Declination in radians.
Definition at line 90 of file casacore.h.
{
     return direction(tolerance, filter)(1);
   }
References direction().
Referenced by purify::casa::MeasurementSet::ChannelWrapper::declination(), and purify::casa::read_measurementset().
direction()
MeasurementSet::Direction purify::casa::MeasurementSet::direction (t_real tolerance = 1e-8, std::string const & filter = "") const
Direction (RA, DEC) in radians.
Definition at line 102 of file casacore.cc.
{
   auto const field_ids_raw = column<::casacore::Int>("FIELD_ID", filter);
   auto const source_ids_raw = table_column<::casacore::Int>(table("FIELD"), "SOURCE_ID");
   std::set<::casacore::Int> source_ids;
   for (Eigen::DenseIndex i(0); i < field_ids_raw.size(); ++i) {
     assert(field_ids_raw(i) < source_ids_raw.size());
     source_ids.insert(source_ids_raw(field_ids_raw(i)));
   }
   if (source_ids.size() == 0 and source_ids_raw.size() > 0) {
     PURIFY_DEBUG(
         "Could not find sources. Try different filter, no matching data in channel. "
         "Currently using filter: " +
         filter);
     Vector<t_real> original(2);
     original(0) = 0.;
     original(1) = 0.;
     return original;
   } else if (source_ids_raw.size() == 0)
     throw std::runtime_error("Could not find sources. Cannot determine direction");
   auto const directions = table_column<::casacore::Double>(table("SOURCE"), "DIRECTION");
   auto const original = directions.row(*source_ids.begin());
   for (auto const other : source_ids)
     if (not directions.row(other).isApprox(original, tolerance))
       throw std::runtime_error("Found more than one direction");
   return original;
 }
References PURIFY_DEBUG, and table().
Referenced by declination(), purify::casa::MeasurementSet::ChannelWrapper::direction(), and right_ascension().
end()
MeasurementSet::const_iterator purify::casa::MeasurementSet::end (std::string const & filter = "") const
Iterates over channels.
Definition at line 40 of file casacore.cc.
{
   return const_iterator(size(), *this, filter);
 }
References size().
Referenced by purify::casa::read_measurementset_channels().
filename() [1/2]
std::string const& purify::casa::MeasurementSet::filename () const inline
Filename of the measurement set.
Definition at line 44 of file casacore.h.
 { return filename_; }
Referenced by filename(), purify::casa::read_measurementset(), purify::casa::read_measurementset_channels(), and table().
filename() [2/2]
MeasurementSet & purify::casa::MeasurementSet::filename (std::string const & filename)
Set new filename.
Definition at line 12 of file casacore.cc.
{
   clear();
   filename_ = filename;
   return *this;
 }
References clear(), and filename().
operator[]() [1/2]
MeasurementSet::ChannelWrapper purify::casa::MeasurementSet::operator[] (std::tuple< t_uint, std::string > const & i) const
Returns wrapper over specific channel.
Definition at line 47 of file casacore.cc.
{
   if (std::get<0>(i) >= size()) throw std::out_of_range("Not that many channels");
   return ChannelWrapper(std::get<0>(i), *this, std::get<1>(i));
 }
References size().
operator[]() [2/2]
MeasurementSet::ChannelWrapper purify::casa::MeasurementSet::operator[] (t_uint i) const
Returns wrapper over specific channel.
Definition at line 43 of file casacore.cc.
{
   return ChannelWrapper(i, *this, "");
 }
right_ascension()
Direction::Scalar purify::casa::MeasurementSet::right_ascension (t_real tolerance = 1e-8, std::string const & filter = "") const inline
Right ascention in radians.
Definition at line 86 of file casacore.h.
{
     return direction(tolerance, filter)(0);
   }
References direction().
Referenced by purify::casa::read_measurementset(), and purify::casa::MeasurementSet::ChannelWrapper::right_ascension().
scalar_column()
template<class T > ::casacore::ScalarColumn<T> purify::casa::MeasurementSet::scalar_column (std::string const & col, std::string const & tabname = "") const inline
Gets scalar column from table.
Definition at line 53 of file casacore.h.
{
     return get_column<T, ::casacore::ScalarColumn>(col, tabname);
   }
size()
std::size_t purify::casa::MeasurementSet::size () const
Number of channels in the measurement set.
Definition at line 27 of file casacore.cc.
{
   if (table().nrow() == 0) return 0;
   auto const column = array_column<::casacore::Double>("CHAN_FREQ", "SPECTRAL_WINDOW");
   auto const orig = column.shape(0);
   for (t_uint i(1); i < column.nrow(); ++i)
     if (orig != column.shape(i))
       throw std::runtime_error("Can only do rectangular measurement set for now");
   return orig(0);
 }
References column(), and table().
Referenced by end(), operator[](), and purify::casa::read_measurementset().
table()
casacore::Table const & purify::casa::MeasurementSet::table (std::string const & name = "") const
Gets table or subtable.
Definition at line 18 of file casacore.cc.
{
   auto const tabname = name == "" ? filename() : filename() + "/" + name;
   auto i_result = tables_->find(tabname);
   if (i_result == tables_->end())
     i_result = tables_->emplace(tabname, ::casacore::Table(tabname)).first;
   return i_result->second;
 }
References filename().
Referenced by column(), direction(), purify::casa::MeasurementSet::const_iterator::same_measurement_set(), and size().
Member Data Documentation
default_filter
std::string const purify::casa::MeasurementSet::default_filter = "WHERE NOT ANY(FLAG)" static
Default filter specifying which data to accept.
Definition at line 33 of file casacore.h.
The documentation for this class was generated from the following files:
/home/runner/work/purify/purify/cpp/purify/casacore.h
/home/runner/work/purify/purify/cpp/purify/casacore.cc