PURIFY: purify::casa::MeasurementSet::const_iterator Class Reference
purify::casa::MeasurementSet::const_iterator Class Reference
#include <casacore.h>
Public Types
typedef MeasurementSet::ChannelWrapper value_type
Convenience wrapper to access values associated with a single channel.
typedef std::shared_ptr< value_type const > pointer
typedef value_type const & reference
typedef t_int difference_type
Public Member Functions
const_iterator (t_int channel, MeasurementSet const &ms, std::string const &filter="")
pointer operator-> () const
reference operator* () const
const_iterator & operator++ ()
const_iterator operator++ (int)
const_iterator & operator+= (difference_type n)
const_iterator & operator-= (difference_type n)
const_iterator operator+ (difference_type n) const
const_iterator operator- (difference_type n) const
bool operator> (const_iterator const &c) const
bool operator>= (const_iterator const &c) const
bool operator< (const_iterator const &c) const
bool operator<= (const_iterator const &c) const
bool operator== (const_iterator const &c) const
bool operator!= (const_iterator const &c) const
bool same_measurement_set (const_iterator const &c) const
True if iterating over the same measurement set.
Detailed Description
Definition at line 315 of file casacore.h.
Member Typedef Documentation
difference_type
typedef t_int purify::casa::MeasurementSet::const_iterator::difference_type
Definition at line 321 of file casacore.h.
pointer
typedef std::shared_ptr<value_type const> purify::casa::MeasurementSet::const_iterator::pointer
Definition at line 319 of file casacore.h.
reference
typedef value_type const& purify::casa::MeasurementSet::const_iterator::reference
Definition at line 320 of file casacore.h.
value_type
typedef MeasurementSet::ChannelWrapper purify::casa::MeasurementSet::const_iterator::value_type
Convenience wrapper to access values associated with a single channel.
Definition at line 318 of file casacore.h.
Constructor & Destructor Documentation
const_iterator()
purify::casa::MeasurementSet::const_iterator::const_iterator (t_int channel, MeasurementSet const & ms, std::string const & filter = "") inline
Definition at line 323 of file casacore.h.
       : channel_(channel),
         ms_(ms),
         filter_(filter),
         wrapper_(new value_type(channel_, ms_, filter_)){};
Member Function Documentation
operator!=()
bool purify::casa::MeasurementSet::const_iterator::operator!= (const_iterator const & c) const inline
Definition at line 346 of file casacore.h.
 { return not operator==(c); }
operator*()
reference purify::casa::MeasurementSet::const_iterator::operator* () const inline
Definition at line 330 of file casacore.h.
 { return *wrapper_; }
operator+()
const_iterator purify::casa::MeasurementSet::const_iterator::operator+ (difference_type n) const inline
Definition at line 335 of file casacore.h.
{
     return const_iterator(channel_ + n, ms_, filter_);
   }
operator++() [1/2]
MeasurementSet::const_iterator & purify::casa::MeasurementSet::const_iterator::operator++ ()
Definition at line 130 of file casacore.cc.
{
   ++channel_;
   wrapper_ = std::make_shared<value_type>(channel_, ms_, filter_);
   return *this;
 }
operator++() [2/2]
MeasurementSet::const_iterator purify::casa::MeasurementSet::const_iterator::operator++ (int)
Definition at line 136 of file casacore.cc.
{
   operator++();
   return const_iterator(channel_ - 1, ms_, filter_);
 }
operator+=()
MeasurementSet::const_iterator & purify::casa::MeasurementSet::const_iterator::operator+= (difference_type n)
Definition at line 379 of file casacore.cc.
{
   channel_ += n;
   return *this;
 }
operator-()
const_iterator purify::casa::MeasurementSet::const_iterator::operator- (difference_type n) const inline
Definition at line 338 of file casacore.h.
References purify::constant::c.
{
     return const_iterator(channel_ - n, ms_, filter_);
   }
operator-=()
const_iterator& purify::casa::MeasurementSet::const_iterator::operator-= (difference_type n) inline
Definition at line 334 of file casacore.h.
 { return operator+=(-n); }
operator->()
pointer purify::casa::MeasurementSet::const_iterator::operator-> () const inline
Definition at line 329 of file casacore.h.
 { return wrapper_; }
operator<()
bool purify::casa::MeasurementSet::const_iterator::operator< (const_iterator const & c) const inline
Definition at line 343 of file casacore.h.
 { return not operator>=(c); }
operator<=()
bool purify::casa::MeasurementSet::const_iterator::operator<= (const_iterator const & c) const inline
Definition at line 344 of file casacore.h.
 { return not operator>(c); }
operator==()
bool purify::casa::MeasurementSet::const_iterator::operator== (const_iterator const & c) const
Definition at line 141 of file casacore.cc.
{
   if (not same_measurement_set(c))
     throw std::runtime_error("Iterators are not over the same measurement set");
   return channel_ == c.channel_;
 }
operator>()
bool purify::casa::MeasurementSet::const_iterator::operator> (const_iterator const & c) const
Definition at line 384 of file casacore.cc.
{
   if (not same_measurement_set(c))
     throw std::runtime_error("Iterators are not over the same measurement set");
   return channel_ > c.channel_;
 }
operator>=()
bool purify::casa::MeasurementSet::const_iterator::operator>= (const_iterator const & c) const
Definition at line 390 of file casacore.cc.
{
   if (not same_measurement_set(c))
     throw std::runtime_error("Iterators are not over the same measurement set");
   return channel_ >= c.channel_;
 }
same_measurement_set()
bool purify::casa::MeasurementSet::const_iterator::same_measurement_set (const_iterator const & c) const inline
True if iterating over the same measurement set.
Definition at line 349 of file casacore.h.
References purify::casa::average_frequency(), purify::casa::MeasurementSet::filename(), purify::I, purify::casa::read_measurementset(), purify::casa::read_measurementset_channels(), and purify::casa::MeasurementSet::table().
{
     return &ms_.table() == &c.ms_.table();
   }
The documentation for this class was generated from the following files:
/mydata/cpp/purify/casacore.h
/mydata/cpp/purify/casacore.cc