PURIFY: /home/runner/work/purify/purify/cpp/tests/common_catch_main.cc File Reference
common_catch_main.cc File Reference
#include "purify/config.h"
#include <sopt/config.h>
#include <memory>
#include <random>
#include <catch2/catch_all.hpp>
#include "purify/logging.h"
#include <sopt/logging.h>
Macros
#define CATCH_CONFIG_RUNNER
Functions
std::unique_ptr< std::mt19937_64 > mersenne (new std::mt19937_64(0))
int main (int argc, char **argv)
Macro Definition Documentation
CATCH_CONFIG_RUNNER
#define CATCH_CONFIG_RUNNER
Definition at line 1 of file common_catch_main.cc.
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 13 of file common_catch_main.cc.
{
   Catch::Session session;  // There must be exactly once instance
   int returnCode = session.applyCommandLine(argc, const_cast<char **>(argv));
   if (returnCode != 0)  // Indicates a command line error
     return returnCode;
   mersenne.reset(new std::mt19937_64(session.configData().rngSeed));
   sopt::logging::initialize();
   purify::logging::initialize();
   return session.run();
 }
References purify::logging::initialize(), and mersenne().
mersenne()
std::unique_ptr<std::mt19937_64> mersenne (new std::mt19937_640)
Referenced by main(), and TEST_CASE().