PURIFY: /mydata/cpp/benchmarks/degridding.cc File Reference
degridding.cc File Reference
#include <chrono>
#include <benchmark/benchmark.h>
#include "benchmarks/utilities.h"
#include "purify/operators.h"
Classes
class GridOperatorFixture
Functions
BENCHMARK_DEFINE_F (GridOperatorFixture, Apply)(benchmark
RangeMultiplier (2) -> Range(100000, 100000<< 5) ->UseManualTime() ->Repetitions(10) ->ReportAggregatesOnly(true) ->Unit(benchmark::kMillisecond)
BENCHMARK_MAIN ()
Function Documentation
BENCHMARK_DEFINE_F()
BENCHMARK_DEFINE_F (GridOperatorFixture , Apply)
Definition at line 37 of file degridding.cc.
References BENCHMARK_MAIN(), and b_utilities::duration().
{
   const t_real oversample_ratio = 2;
   const t_uint N = m_imsizex * m_imsizey * oversample_ratio * oversample_ratio;
   const auto& forward = std::get<0>(Gop);
   const Vector<t_complex> input = Vector<t_complex>::Random(N);
   Vector<t_complex> output = Vector<t_complex>::Zero(M);
   forward(output, input);
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     forward(output, input);
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end));
   }
 }
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
Referenced by BENCHMARK_DEFINE_F().
RangeMultiplier()
RangeMultiplier (2) -> Range(100000, 100000<< 5) ->UseManualTime() ->Repetitions(10) ->ReportAggregatesOnly(true) ->Unit(benchmark::kMillisecond)