PURIFY: /home/runner/work/purify/purify/cpp/benchmarks/measurement_operator_mpi.cc File Reference
measurement_operator_mpi.cc File Reference
#include <chrono>
#include <sstream>
#include <benchmark/benchmark.h>
#include "benchmarks/utilities.h"
#include "purify/directories.h"
#include "purify/operators.h"
#include "purify/pfitsio.h"
#include <sopt/imaging_padmm.h>
#include <sopt/mpi/communicator.h>
#include <sopt/mpi/session.h>
#include <sopt/wavelets.h>
Classes
class DegridOperatorCtorFixturePar
class DegridOperatorFixturePar
class DegridOperatorDirectFixturePar
class DegridOperatorAdjointFixturePar
class DegridOperatorDirectFixtureDistr
class DegridOperatorDirectFixtureMPI
class DegridOperatorAdjointFixtureDistr
class DegridOperatorAdjointFixtureMPI
Functions
BENCHMARK_DEFINE_F (DegridOperatorCtorFixturePar, Distr)(benchmark
BENCHMARK_DEFINE_F (DegridOperatorCtorFixturePar, MPI)(benchmark
BENCHMARK_DEFINE_F (DegridOperatorDirectFixtureDistr, Apply)(benchmark
BENCHMARK_DEFINE_F (DegridOperatorAdjointFixtureDistr, Apply)(benchmark
BENCHMARK_DEFINE_F (DegridOperatorDirectFixtureMPI, Apply)(benchmark
BENCHMARK_DEFINE_F (DegridOperatorAdjointFixtureMPI, Apply)(benchmark
Args ({1024, static_cast< t_int >(1e6), 4}) -> Args(
Args ({1024, static_cast< t_int >(1e7), 4}) -> Args(
Args ({1024, static_cast< t_int >(1e8), 4}) -> Args(
UseManualTime () -> Repetitions(10) ->Unit(benchmark::kMillisecond)
Function Documentation
Args() [1/3]
Args ({1024, static_cast< t_int >(1e6), 4}) -> Args(
Definition at line 286 of file measurement_operator_mpi.cc.
            {1024, static_cast<t_int>(1e6), 4})
     ->Args({1024, static_cast<t_int>(5e6), 4})
Args() [2/3]
Args ({1024, static_cast< t_int >(1e7), 4}) -> Args(
Definition at line 288 of file measurement_operator_mpi.cc.
            {1024, static_cast<t_int>(1e7), 4})
     ->Args({1024, static_cast<t_int>(5e7), 4})
Args() [3/3]
Args ({1024, static_cast< t_int >(1e8), 4}) -> Args(
Definition at line 290 of file measurement_operator_mpi.cc.
            {1024, static_cast<t_int>(1e8), 4})
     ->Args({1024, static_cast<t_int>(5e8), 4})
BENCHMARK_DEFINE_F() [1/6]
BENCHMARK_DEFINE_F (DegridOperatorAdjointFixtureDistr , Apply)
Definition at line 216 of file measurement_operator_mpi.cc.
{
   // Benchmark the application of the adjoint distributed operator
   if ((m_counter % 10) == 1) {
     m_image = m_degridOperator->adjoint() * m_uv_data.vis;
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     m_image = m_degridOperator->adjoint() * m_uv_data.vis;
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end, m_world));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizey * m_imsizex) *
                           sizeof(t_complex));
 }
References b_utilities::duration().
BENCHMARK_DEFINE_F() [2/6]
BENCHMARK_DEFINE_F (DegridOperatorAdjointFixtureMPI , Apply)
Definition at line 248 of file measurement_operator_mpi.cc.
{
   // Benchmark the application of the adjoint distributed MPI operator
   if ((m_counter % 10) == 1) {
     m_image = m_degridOperator->adjoint() * m_uv_data.vis;
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     m_image = m_degridOperator->adjoint() * m_uv_data.vis;
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end, m_world));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizey * m_imsizex) *
                           sizeof(t_complex));
 }
References b_utilities::duration().
BENCHMARK_DEFINE_F() [3/6]
BENCHMARK_DEFINE_F (DegridOperatorCtorFixturePar , Distr)
Definition at line 53 of file measurement_operator_mpi.cc.
{
   // benchmark the creation of the distributed measurement operator
   if ((m_counter % 10) == 1) {
     auto sky_measurements = measurementoperator::init_degrid_operator_2d<Vector<t_complex>>(
         m_world, m_uv_data, m_imsizey, m_imsizex, m_cellsize, m_cellsize, 2, kernels::kernel::kb,
         state.range(2), state.range(2), m_w_term);
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     auto sky_measurements = measurementoperator::init_degrid_operator_2d<Vector<t_complex>>(
         m_world, m_uv_data, m_imsizey, m_imsizex, m_cellsize, m_cellsize, 2, kernels::kernel::kb,
         state.range(2), state.range(2), m_w_term);
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end, m_world));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizex * m_imsizey) *
                           sizeof(t_complex));
 }
References b_utilities::duration(), and purify::kernels::kb.
BENCHMARK_DEFINE_F() [4/6]
BENCHMARK_DEFINE_F (DegridOperatorCtorFixturePar , MPI)
Definition at line 73 of file measurement_operator_mpi.cc.
{
   // benchmark the creation of the distributed MPI measurement operator
   if ((m_counter % 10) == 1) {
     auto sky_measurements = measurementoperator::init_degrid_operator_2d_mpi<Vector<t_complex>>(
         m_world, m_uv_data, m_imsizey, m_imsizex, m_cellsize, m_cellsize, 2, kernels::kernel::kb,
         state.range(2), state.range(2), m_w_term);
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     auto sky_measurements = measurementoperator::init_degrid_operator_2d_mpi<Vector<t_complex>>(
         m_world, m_uv_data, m_imsizey, m_imsizex, m_cellsize, m_cellsize, 2, kernels::kernel::kb,
         state.range(2), state.range(2), m_w_term);
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end, m_world));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizex * m_imsizey) *
                           sizeof(t_complex));
 }
References b_utilities::duration(), and purify::kernels::kb.
BENCHMARK_DEFINE_F() [5/6]
BENCHMARK_DEFINE_F (DegridOperatorDirectFixtureDistr , Apply)
Definition at line 200 of file measurement_operator_mpi.cc.
{
   // Benchmark the application of the distributed operator
   if ((m_counter % 10) == 1) {
     m_uv_data.vis = (*m_degridOperator) * Image<t_complex>::Map(m_image.data(), m_image.size(), 1);
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     m_uv_data.vis = (*m_degridOperator) * Image<t_complex>::Map(m_image.data(), m_image.size(), 1);
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end, m_world));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizey * m_imsizex) *
                           sizeof(t_complex));
 }
References b_utilities::duration().
BENCHMARK_DEFINE_F() [6/6]
BENCHMARK_DEFINE_F (DegridOperatorDirectFixtureMPI , Apply)
Definition at line 232 of file measurement_operator_mpi.cc.
{
   // Benchmark the application of the distributed MPI operator
   if ((m_counter % 10) == 1) {
     m_uv_data.vis = (*m_degridOperator) * Image<t_complex>::Map(m_image.data(), m_image.size(), 1);
   }
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     m_uv_data.vis = (*m_degridOperator) * Image<t_complex>::Map(m_image.data(), m_image.size(), 1);
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end, m_world));
   }
   state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizey * m_imsizex) *
                           sizeof(t_complex));
 }
References b_utilities::duration().
UseManualTime()
UseManualTime () -> Repetitions(10) ->Unit(benchmark::kMillisecond)