PURIFY: purify::logging Namespace Reference
purify::logging Namespace Reference
Classes
class Log
Logging system for controlled & formatted writing to stdout.
Functions
void _updateLevels (const Log::LevelMap &defaultLevels, Log::LogMap &existingLogs)
ostream & operator<< (Log &log, int level)
Streaming output to a logger must have a Log::Level/int as its first argument.
Log & getLog ()
Access method to default Log object.
void set_level (const std::string &level)
Method to set the logging level of the default Log object.
template<typename Arg >
void applyFormat (std::stringstream &ss, char *&pos, Arg &&arg)
template<typename... Args>
std::string mkFormattedString (const char *txt, Args &&... args)
Helper method to construct formatted string.
std::string mkFormattedString (const std::string &txt)
Function Documentation
_updateLevels()
void purify::logging::_updateLevels (const Log::LevelMap & defaultLevels, Log::LogMap & existingLogs)
Todo:
Add single static setLevel
Todo:
Check ordering - "Foo" should come before "Foo.Bar"
Definition at line 24 of file logging.cc.
{
   for (Log::LevelMap::const_iterator lev = defaultLevels.begin(); lev != defaultLevels.end();
        ++lev) {
     for (Log::LogMap::iterator log = existingLogs.begin(); log != existingLogs.end(); ++log) {
       if (log->first.find(lev->first) == 0) {
         log->second.setLevel(lev->second);
       }
     }
   }
 }
Referenced by purify::logging::Log::setLevels().
applyFormat()
template<typename Arg > void purify::logging::applyFormat (std::stringstream & ss, char *& pos, Arg && arg)
Helper method to ireplace a set of curly braces with the template argument arg in a string stream
Definition at line 142 of file logging.h.
{
   char* delim = strstr(pos, "{}");
   if (delim != NULL) {
     ss << std::string(pos, delim - pos) << std::forward<Arg>(arg);
     pos = delim + 2;
   } else {
     throw std::runtime_error("Insufficient placeholders for number of arguments!");
   }
 }
Referenced by mkFormattedString().
getLog()
Log& purify::logging::getLog () inline
Access method to default Log object.
Definition at line 134 of file logging.h.
 { return Log::getLog("purify::"); }
References purify::logging::Log::getLog().
Referenced by set_level().
mkFormattedString() [1/2]
template<typename... Args> std::string purify::logging::mkFormattedString (const char * txt, Args &&... args) inline
Helper method to construct formatted string.
Definition at line 154 of file logging.h.
{
   std::string mys = txt;
   std::stringstream rtn;
   char* pos = (char*)txt;
   ((void)applyFormat(rtn, pos, std::forward<Args>(args)), ...);
   rtn << std::string(pos);
   return rtn.str();
 }
References applyFormat().
Referenced by mkFormattedString().
mkFormattedString() [2/2]
std::string purify::logging::mkFormattedString (const std::string & txt) inline
Definition at line 163 of file logging.h.
{
   return mkFormattedString(txt.data());
 }
References mkFormattedString().
operator<<()
std::ostream & purify::logging::operator<< (Log & log, int level)
Streaming output to a logger must have a Log::Level/int as its first argument.
The streaming operator can use Log's internals.
Definition at line 171 of file logging.cc.
{
   if (log.isActive(level)) {
     if (level > Log::warning) {
       cerr << log.formatMessage(level, "");
       return cerr;
     } else {
       cout << log.formatMessage(level, "");
       return cout;
     }
   } else {
     static ostream devNull(nullptr);
     return devNull;
   }
 }
set_level()
void purify::logging::set_level (const std::string & level) inline
Method to set the logging level of the default Log object.
Definition at line 137 of file logging.h.
 { getLog().setLevel(Log::getLevelFromName(level)); }
References purify::logging::Log::getLevelFromName(), getLog(), and purify::logging::Log::setLevel().
Referenced by main(), and TEST_CASE().