PURIFY: purify::notinstalled Namespace Reference
purify::notinstalled Namespace Reference
Functions
template<class T >
std::enable_if< std::is_scalar< T >::value, std::vector< T > >::type read_data (const std::string &filename)
read real values from data file
template<class T >
std::enable_if< std::is_same< t_complex, T >::value, std::vector< T > >::type read_data (const std::string &filename)
read complex values from data file
std::vector< t_complex > read_data (const std::vector< t_real > &input)
std::string data_directory ()
Holds data and such.
std::string data_filename (std::string const &filename)
Holds data and such.
std::string scratch_directory ()
Holds data and such in Scratch (useful for legion)
std::string scratch_filename (std::string const &filename)
Holds data and such in Scratch (useful for legion)
std::string image_filename (std::string const &filename)
Image filename.
std::string visibility_filename (std::string const &filename)
Visibility filename.
std::string vla_filename (std::string const &filename)
Specific vla data.
std::string atca_filename (std::string const &filename)
Specific atca data.
std::string gridding_filename (std::string const &filename)
Some gridding regression data.
std::string degridding_filename (std::string const &filename)
Some degridding regression data.
std::string output_directory ()
Where test outputs go.
std::string output_filename (std::string const &filename)
Test output file.
std::string ngc3256_ms ()
Function Documentation
atca_filename()
std::string purify::notinstalled::atca_filename (std::string const & filename) inline
Specific atca data.
Definition at line 44 of file directories.in.h.
References data_filename().
Referenced by TEST_CASE().
{
   return data_filename("atca/" + filename);
 }
data_directory()
std::string purify::notinstalled::data_directory () inline
Holds data and such.
Definition at line 10 of file directories.in.h.
Referenced by data_filename().
 { return "@PROJECT_SOURCE_DIR@/data"; }
data_filename()
std::string purify::notinstalled::data_filename (std::string const & filename) inline
Holds data and such.
Definition at line 12 of file directories.in.h.
References data_directory().
Referenced by atca_filename(), degridding_filename(), gridding_filename(), image_filename(), TEST_CASE(), and vla_filename().
{
   return data_directory() + "/" + filename;
 }
degridding_filename()
std::string purify::notinstalled::degridding_filename (std::string const & filename) inline
Some degridding regression data.
Definition at line 52 of file directories.in.h.
References data_filename().
{
   return data_filename("expected/degridding/" + filename);
 }
gridding_filename()
std::string purify::notinstalled::gridding_filename (std::string const & filename) inline
Some gridding regression data.
Definition at line 48 of file directories.in.h.
References data_filename().
{
   return data_filename("expected/gridding/" + filename);
 }
image_filename()
std::string purify::notinstalled::image_filename (std::string const & filename) inline
Image filename.
Definition at line 32 of file directories.in.h.
References data_filename().
Referenced by main(), TEST_CASE(), and b_utilities::updateImage().
{
   return data_filename("images/" + filename);
 }
ngc3256_ms()
std::string purify::notinstalled::ngc3256_ms () inline
Definition at line 63 of file directories.in.h.
Referenced by main().
 { return "@NGC3256_MS@"; }
output_directory()
std::string purify::notinstalled::output_directory () inline
Where test outputs go.
Definition at line 57 of file directories.in.h.
Referenced by output_filename().
 { return "@PROJECT_BINARY_DIR@/outputs"; }
output_filename()
std::string purify::notinstalled::output_filename (std::string const & filename) inline
Test output file.
Definition at line 59 of file directories.in.h.
References output_directory().
Referenced by main(), padmm(), and TEST_CASE().
{
   return output_directory() + "/" + filename;
 }
read_data() [1/3]
template<class T > std::enable_if<std::is_scalar<T>::value, std::vector<T> >::type purify::notinstalled::read_data (const std::string & filename)
read real values from data file
Definition at line 16 of file data.in.h.
{
   std::ifstream data_file(filename);
   if (!data_file)
       throw std::runtime_error("Test data is missing: "+filename);
   std::string s;
   //read data
   std::vector<T> data;
   for(std::string s; std::getline(data_file, s, ',');){
     data.push_back(std::stod(s));
   }
   return data;
   }
read_data() [2/3]
template<class T > std::enable_if<std::is_same<t_complex, T>::value, std::vector<T> >::type purify::notinstalled::read_data (const std::string & filename)
read complex values from data file
Definition at line 31 of file data.in.h.
{
   std::ifstream data_file(filename);
   if (!data_file)
       throw std::runtime_error("Test data is missing: "+filename);
   std::string real = "";
   std::string imag = "";
   //read data
   std::vector<T> data;
   for(std::string real; std::getline(data_file, real, ',');){
     real.erase(0, 1);
     if(!std::getline(data_file, imag, ')'))
       break;
     data.push_back(T(std::stod(real), std::stod(imag)));
     real="";
     imag="";
   }
   return data;
   }
read_data() [3/3]
std::vector<t_complex> purify::notinstalled::read_data (const std::vector< t_real > & input)
Definition at line 50 of file data.in.h.
References a.
{
     std::vector<t_complex> output;
   for(auto a = input.begin(); a != input.end(); a++ )
     output.push_back(t_complex(*a, 0.));
   return output;
   }
scratch_directory()
std::string purify::notinstalled::scratch_directory () inline
Holds data and such in Scratch (useful for legion)
Definition at line 16 of file directories.in.h.
Referenced by scratch_filename().
{
   std::string dirName = "$ENV{HOME}/Scratch/purify/data";
   struct stat sb;
   if ( stat("$ENV{HOME}/Scratch",&sb)!=0 || !S_ISDIR(sb.st_mode) )
     mkdir("$ENV{HOME}/Scratch",S_IRWXU);
   if ( stat("$ENV{HOME}/Scratch/purify",&sb)!=0 || !S_ISDIR(sb.st_mode) )
     mkdir("$ENV{HOME}/Scratch/purify",S_IRWXU);
   if ( stat("$ENV{HOME}/Scratch/purify/data",&sb)!=0 || !S_ISDIR(sb.st_mode) )
     mkdir("$ENV{HOME}/Scratch/purify/data",S_IRWXU);
   return dirName;
 }
scratch_filename()
std::string purify::notinstalled::scratch_filename (std::string const & filename) inline
Holds data and such in Scratch (useful for legion)
Definition at line 28 of file directories.in.h.
References scratch_directory().
Referenced by visibility_filename().
{
   return scratch_directory() + "/" + filename;
 }
visibility_filename()
std::string purify::notinstalled::visibility_filename (std::string const & filename) inline
Visibility filename.
Definition at line 36 of file directories.in.h.
References scratch_filename().
Referenced by b_utilities::random_measurements().
{
   return scratch_filename("vis_" + filename);
 }
vla_filename()
std::string purify::notinstalled::vla_filename (std::string const & filename) inline
Specific vla data.
Definition at line 40 of file directories.in.h.
References data_filename().
Referenced by main(), and TEST_CASE().
{
   return data_filename("vla/" + filename);
 }