PURIFY: purify Namespace Reference
purify Namespace Reference
Namespaces
casa
constant
convol
details
distribute
factory
integration
kernels
logging
measurementoperator
notinstalled
operators
pfitsio
projection_kernels
read_measurements
utilities
widefield
wproj_utilities
Classes
class IndexMapping
class YamlParser
Typedefs
typedef std::complex< float > t_complexf
typedef Eigen::Triplet< t_complex > t_tripletList
Root of the type hierarchy for triplet lists.
template<class T = t_real, class I = t_int>
using Sparse = Eigen::SparseMatrix< T, Eigen::RowMajor, I >
A matrix of a given type.
template<class T = t_real, class I = t_int>
using SparseVector = Eigen::SparseVector< T, Eigen::RowMajor, I >
Enumerations
enum stokes {
stokes::I, stokes::Q, stokes::U, stokes::V,
stokes::XX, stokes::YY, stokes::XY, stokes::YX,
stokes::LL, stokes::RR, stokes::LR, stokes::RL,
stokes::P
}
enum dde_type { dde_type::wkernel_radial, dde_type::wkernel_2d }
Types of DDEs in purify.
Functions
std::vector< t_int > all_to_all_send_sizes (const std::vector< t_int > &recv_sizes, const sopt::mpi::Communicator &comm)
std::string version ()
Returns library version.
std::tuple< uint8_t, uint8_t, uint8_t > version_tuple ()
Returns library version.
std::string gitref ()
Returns library git reference, if known.
std::string default_logging_level ()
Default logging level.
std::string default_logger_name ()
Default logger name.
constexpr bool color_logger ()
Wether to add color to the logger.
template<class T0 , class STORAGE_INDEX_TYPE = t_int>
std::set< STORAGE_INDEX_TYPE > non_empty_outers (Eigen::SparseMatrixBase< T0 > const &matrix)
Indices of non empty outer indices.
template<class T0 >
Sparse< typename T0::Scalar > compress_outer (T0 const &matrix)
Indices of non empty outer indices.
std::tuple< std::function< t_real(t_real)>, std::function< t_real(t_real)>, std::function< t_real(t_real)>, std::function< t_real(t_real)> > create_kernels (const kernels::kernel kernel_name_, const t_uint Ju_, const t_uint Jv_, const t_real imsizey_, const t_real imsizex_, const t_real oversample_ratio)
std::tuple< std::function< t_real(t_real)>, std::function< t_real(t_real)> > create_radial_ftkernel (const kernels::kernel kernel_name_, const t_uint Ju_, const t_real oversample_ratio)
std::vector< std::string > split (const std::string &s, char delim)
splits string into vector
void mkdir_recursive (const std::string &path)
recursively create directories when they do not exist
template<class T >
void mkdir_recursive (const T &path)
boost wrapper
template<typename T >
void split (const std::string &s, char delim, T result)
adds split string to container
template<typename T >
T get_vector (const YAML::Node &node_map, const std::initializer_list< const char *> indicies)
Variables
const std::map< stokes, t_int > stokes_int
const std::map< std::string, stokes > stokes_string
Detailed Description
YamlParser definition for the purify project
Author
Roland Guichard
Version
1.0
YamlParser header for purify project
Author
Roland Guichard
Version
1.0 The YamlParser class definition.
It browses and searches through the config.yaml file in the data folder and sets the class variable members accordingly, to be used by the purify algorithm.
Parameters
filepath path to the config file
Typedef Documentation
Sparse
template<class T = t_real, class I = t_int> using purify::Sparse = typedef Eigen::SparseMatrix<T, Eigen::RowMajor, I>
A matrix of a given type.
Operates as mathematical sparse matrix.
Definition at line 28 of file types.h.
SparseVector
template<class T = t_real, class I = t_int> using purify::SparseVector = typedef Eigen::SparseVector<T, Eigen::RowMajor, I>
Definition at line 30 of file types.h.
t_complexf
typedef std::complex<float> purify::t_complexf
Definition at line 21 of file types.h.
t_tripletList
typedef Eigen::Triplet<t_complex> purify::t_tripletList
Root of the type hierarchy for triplet lists.
Definition at line 23 of file types.h.
Enumeration Type Documentation
dde_type
enum purify::dde_type strong
Types of DDEs in purify.
Enumerator
wkernel_radial
wkernel_2d
Definition at line 47 of file types.h.
 { wkernel_radial, wkernel_2d };
stokes
enum purify::stokes strong
Enumerator
I
Q
U
V
XX
YY
XY
YX
LL
RR
LR
RL
P
Definition at line 32 of file types.h.
 { I, Q, U, V, XX, YY, XY, YX, LL, RR, LR, RL, P };
Function Documentation
all_to_all_send_sizes()
std::vector<t_int> purify::all_to_all_send_sizes (const std::vector< t_int > & recv_sizes, const sopt::mpi::Communicator & comm)
Definition at line 5 of file AllToAllSparseVector.cc.
{
   std::vector<t_int> send_sizes(recv_sizes.size(), 0);
   for (t_int i = 0; i < comm.size(); i++) {
     if (i == comm.rank())
       send_sizes = comm.gather<t_int>(recv_sizes[i], i);
     else
       comm.gather<t_int>(recv_sizes[i], i);
   }
   return send_sizes;
 }
color_logger()
constexpr bool purify::color_logger () inline
Wether to add color to the logger.
Definition at line 51 of file config.in.h.
{
   // clang-format off
   return @PURIFY_COLOR_LOGGING@;
   // clang-format on
 }
compress_outer()
template<class T0 > Sparse<typename T0::Scalar> purify::compress_outer (T0 const & matrix)
Indices of non empty outer indices.
Definition at line 71 of file IndexMapping.h.
References purify::IndexMapping< STORAGE_INDEX_TYPE >::cols(), non_empty_outers(), and purify::IndexMapping< STORAGE_INDEX_TYPE >::rows().
Referenced by TEST_CASE().
{
   static_assert(T0::IsRowMajor, "Not tested for col major");
   auto const indices = non_empty_outers(matrix);
   SparseVector<typename T0::Index, typename T0::Index> mapping(matrix.cols());
   mapping.reserve(indices.size());
   t_int i(0);
   for (auto const &index : indices) mapping.coeffRef(index) = i++;
   std::vector<typename Sparse<typename T0::Scalar>::Index> rows(matrix.rows() + 1, 0);
   std::vector<typename Sparse<typename T0::Scalar>::Index> cols(matrix.nonZeros(), 0);
   rows[matrix.rows()] = matrix.nonZeros();
   t_int index = 0;
   for (typename T0::Index k = 0; k < matrix.outerSize(); ++k) {
     rows[k] = index;
     for (typename T0::InnerIterator it(matrix, k); it; ++it) {
       cols[index] = mapping.coeff(it.col());
       index++;
     }
   }
   return Eigen::MappedSparseMatrix<typename T0::Scalar, Eigen::RowMajor,
                                    typename Sparse<typename T0::Scalar>::Index>(
       matrix.rows(), indices.size(), matrix.nonZeros(), rows.data(), cols.data(),
       const_cast<typename T0::Scalar *>(matrix.derived().valuePtr()));
 }
create_kernels()
std::tuple< std::function< t_real(t_real)>, std::function< t_real(t_real)>, std::function< t_real(t_real)>, std::function< t_real(t_real)> > purify::create_kernels (const kernels::kernel kernel_name_, const t_uint Ju_, const t_uint Jv_, const t_real imsizey_, const t_real imsizex_, const t_real oversample_ratio)
Definition at line 235 of file kernels.cc.
References purify::kernels::box, purify::kernels::ft_gaussian(), purify::kernels::ft_gaussian_general(), purify::kernels::ft_kaiser_bessel(), purify::kernels::ft_kaiser_bessel_general(), purify::kernels::ft_pill_box(), purify::kernels::ft_pswf(), purify::kernels::gauss, purify::kernels::gauss_alt, purify::kernels::gaussian(), purify::kernels::gaussian_general(), purify::kernels::kaiser_bessel(), purify::kernels::kaiser_bessel_general(), purify::kernels::kb, purify::kernels::kbmin, purify::constant::pi, purify::kernels::pill_box(), purify::kernels::pswf, PURIFY_ERROR, PURIFY_MEDIUM_LOG, and sigma().
Referenced by purify::operators::base_degrid_operator_2d(), GridOperatorFixture::SetUp(), and TEST_CASE().
{
   // PURIFY_MEDIUM_LOG("Kernel Name: {}", kernel_name_.c_str());
   PURIFY_MEDIUM_LOG("Kernel Support: {} x {}", Ju_, Jv_);
   const t_uint ftsizev_ = std::floor(imsizey_ * oversample_ratio);
   const t_uint ftsizeu_ = std::floor(imsizex_ * oversample_ratio);
   if ((kernel_name_ == kernels::kernel::pswf) and (Ju_ != 6 or Jv_ != 6)) {
     PURIFY_ERROR("Error: Only a support of 6 is implemented for PSWFs.");
     throw std::runtime_error("Incorrect input: PSWF requires a support of 6");
   }
   switch (kernel_name_) {
   case kernels::kernel::kb: {
     auto kbu = [=](const t_real x) { return kernels::kaiser_bessel(x, Ju_); };
     auto kbv = [=](const t_real x) { return kernels::kaiser_bessel(x, Jv_); };
     auto ftkbu = [=](const t_real x) { return kernels::ft_kaiser_bessel(x / ftsizeu_ - 0.5, Ju_); };
     auto ftkbv = [=](const t_real x) { return kernels::ft_kaiser_bessel(x / ftsizev_ - 0.5, Jv_); };
     return std::make_tuple(kbu, kbv, ftkbu, ftkbv);
     break;
   }
   case kernels::kernel::kbmin: {
     const t_real kb_interp_alpha_Ju =
         constant::pi * std::sqrt(Ju_ * Ju_ / (oversample_ratio * oversample_ratio) *
                                      (oversample_ratio - 0.5) * (oversample_ratio - 0.5) -
                                  0.8);
     const t_real kb_interp_alpha_Jv =
         constant::pi * std::sqrt(Jv_ * Jv_ / (oversample_ratio * oversample_ratio) *
                                      (oversample_ratio - 0.5) * (oversample_ratio - 0.5) -
                                  0.8);
     auto kbu = [=](const t_real x) {
       return kernels::kaiser_bessel_general(x, Ju_, kb_interp_alpha_Ju);
     };
     auto kbv = [=](const t_real x) {
       return kernels::kaiser_bessel_general(x, Jv_, kb_interp_alpha_Jv);
     };
     auto ftkbu = [=](const t_real x) {
       return kernels::ft_kaiser_bessel_general(x / ftsizeu_ - 0.5, Ju_, kb_interp_alpha_Ju);
     };
     auto ftkbv = [=](const t_real x) {
       return kernels::ft_kaiser_bessel_general(x / ftsizev_ - 0.5, Jv_, kb_interp_alpha_Jv);
     };
     return std::make_tuple(kbu, kbv, ftkbu, ftkbv);
     break;
   }
   case kernels::kernel::pswf: {
     auto pswfu = [=](const t_real x) { return kernels::pswf(x, Ju_); };
     auto pswfv = [=](const t_real x) { return kernels::pswf(x, Jv_); };
     auto ftpswfu = [=](const t_real x) { return kernels::ft_pswf(x / ftsizeu_ - 0.5, Ju_); };
     auto ftpswfv = [=](const t_real x) { return kernels::ft_pswf(x / ftsizev_ - 0.5, Jv_); };
     return std::make_tuple(pswfu, pswfv, ftpswfu, ftpswfv);
     break;
   }
   case kernels::kernel::gauss: {
     auto gaussu = [=](const t_real x) { return kernels::gaussian(x, Ju_); };
     auto gaussv = [=](const t_real x) { return kernels::gaussian(x, Jv_); };
     auto ftgaussu = [=](const t_real x) { return kernels::ft_gaussian(x / ftsizeu_ - 0.5, Ju_); };
     auto ftgaussv = [=](const t_real x) { return kernels::ft_gaussian(x / ftsizev_ - 0.5, Jv_); };
     return std::make_tuple(gaussu, gaussv, ftgaussu, ftgaussv);
     break;
   }
   case kernels::kernel::box: {
     auto boxu = [=](const t_real x) { return kernels::pill_box(x, Ju_); };
     auto boxv = [=](const t_real x) { return kernels::pill_box(x, Jv_); };
     auto ftboxu = [=](const t_real x) { return kernels::ft_pill_box(x / ftsizeu_ - 0.5, Ju_); };
     auto ftboxv = [=](const t_real x) { return kernels::ft_pill_box(x / ftsizev_ - 0.5, Jv_); };
     return std::make_tuple(boxu, boxv, ftboxu, ftboxv);
     break;
   }
   case kernels::kernel::gauss_alt: {
     const t_real sigma = 1;  // In units of radians, Rafael uses sigma = 2 * pi / ftsizeu_. However,
     // this should be 1 in units of pixels.
     auto gaussu = [=](const t_real x) { return kernels::gaussian_general(x, Ju_, sigma); };
     auto gaussv = [=](const t_real x) { return kernels::gaussian_general(x, Jv_, sigma); };
     auto ftgaussu = [=](const t_real x) {
       return kernels::ft_gaussian_general(x / ftsizeu_ - 0.5, Ju_, sigma);
     };
     auto ftgaussv = [=](const t_real x) {
       return kernels::ft_gaussian_general(x / ftsizev_ - 0.5, Jv_, sigma);
     };
     return std::make_tuple(gaussu, gaussv, ftgaussu, ftgaussv);
     break;
   }
   default:
     throw std::runtime_error("Did not choose valid kernel.");
   }
 }
create_radial_ftkernel()
std::tuple< std::function< t_real(t_real)>, std::function< t_real(t_real)> > purify::create_radial_ftkernel (const kernels::kernel kernel_name_, const t_uint Ju_, const t_real oversample_ratio)
Definition at line 321 of file kernels.cc.
References purify::kernels::box, purify::kernels::ft_gaussian(), purify::kernels::ft_kaiser_bessel(), purify::kernels::ft_kaiser_bessel_general(), purify::kernels::ft_pill_box(), purify::kernels::ft_pswf(), purify::kernels::gauss, purify::kernels::gaussian(), purify::kernels::kaiser_bessel(), purify::kernels::kaiser_bessel_general(), purify::kernels::kb, purify::kernels::kbmin, purify::constant::pi, purify::kernels::pill_box(), purify::kernels::pswf, PURIFY_ERROR, and PURIFY_MEDIUM_LOG.
Referenced by purify::operators::base_degrid_operator_2d().
{
   // PURIFY_MEDIUM_LOG("Kernel Name: {}", kernel_name_.c_str());
   PURIFY_MEDIUM_LOG("Radial Kernel Support: {}", Ju_);
   if ((kernel_name_ == kernels::kernel::pswf) and (Ju_ != 6)) {
     PURIFY_ERROR("Error: Only a support of 6 is implemented for PSWFs.");
     throw std::runtime_error("Incorrect input: PSWF requires a support of 6");
   }
   switch (kernel_name_) {
   case kernels::kernel::kb: {
     return std::make_tuple(
         [=](const t_real x) { return kernels::ft_kaiser_bessel(x, static_cast<t_real>(Ju_)); },
         [=](const t_real x) { return kernels::kaiser_bessel(x, static_cast<t_real>(Ju_)); });
     break;
   }
   case kernels::kernel::kbmin: {
     const t_real kb_interp_alpha_Ju =
         constant::pi * std::sqrt(Ju_ * Ju_ / (oversample_ratio * oversample_ratio) *
                                      (oversample_ratio - 0.5) * (oversample_ratio - 0.5) -
                                  0.8);
     auto kbuv = [=](const t_real x) {
       return kernels::kaiser_bessel_general(x, Ju_, kb_interp_alpha_Ju);
     };
     auto ftkbuv = [=](const t_real x) {
       return kernels::ft_kaiser_bessel_general(x, Ju_, kb_interp_alpha_Ju);
     };
     return std::make_tuple(ftkbuv, kbuv);
     break;
   }
   case kernels::kernel::pswf: {
     return std::make_tuple(
         [=](const t_real x) { return kernels::ft_pswf(x, static_cast<t_real>(Ju_)); },
         [=](const t_real x) { return kernels::pswf(x, Ju_); });
     break;
   }
   case kernels::kernel::gauss: {
     return std::make_tuple(
         [=](const t_real x) { return kernels::ft_gaussian(x, static_cast<t_real>(Ju_)); },
         [=](const t_real x) { return kernels::gaussian(x, Ju_); });
     break;
   }
   case kernels::kernel::box: {
     return std::make_tuple(
         [=](const t_real x) { return kernels::ft_pill_box(x, static_cast<t_real>(Ju_)); },
         [=](const t_real x) { return kernels::pill_box(x, Ju_); });
     break;
   }
   default:
     throw std::runtime_error("Did not choose valid radial kernel.");
   }
 }
default_logger_name()
std::string purify::default_logger_name () inline
Default logger name.
Definition at line 49 of file config.in.h.
 { return "@PURIFY_LOGGER_NAME@"; }
default_logging_level()
std::string purify::default_logging_level () inline
Default logging level.
Definition at line 47 of file config.in.h.
Referenced by main().
 { return "@PURIFY_TEST_LOG_LEVEL@"; }
get_vector()
template<typename T > T purify::get_vector (const YAML::Node & node_map, const std::initializer_list< const char *> indicies)
Definition at line 74 of file yaml-parser.cc.
{
   YAML::Node node = YAML::Clone(node_map);
   std::string faulty_variable;
   for (const char* index : indicies) {
     faulty_variable = std::string(index);
     node = node[index];
     if (!node.IsDefined()) {
       throw std::runtime_error("The initialisation of " + faulty_variable + " is wrong.");
     }
   }
   try {
     T output;
     for (int i = 0; i < node.size(); i++) output.push_back(node[i].as<typename T::value_type>());
     return output;
   } catch (std::exception e) {
     throw std::runtime_error("There is a mismatch in the type conversion of " + faulty_variable);
   }
 }
gitref()
std::string purify::gitref () inline
Returns library git reference, if known.
Definition at line 45 of file config.in.h.
 { return "@Purify_GITREF@"; }
mkdir_recursive() [1/2]
template<class T > void purify::mkdir_recursive (const T & path)
boost wrapper
Definition at line 45 of file read_measurements.h.
References mkdir_recursive().
{
   mkdir_recursive(path.native());
 }
mkdir_recursive() [2/2]
void purify::mkdir_recursive (const std::string & path)
recursively create directories when they do not exist
Definition at line 138 of file read_measurements.cc.
References purify::read_measurements::dir_exists(), and split().
Referenced by main(), mkdir_recursive(), TEST_CASE(), and purify::YamlParser::writeOutput().
{
   if (read_measurements::dir_exists(path)) return;
   const auto folders = split(path, '/');
   std::string current_path = "";
   for (const auto f : folders) {
     if (f == "") {
       current_path += "/";
       continue;
     }
     current_path += f;
     if (not read_measurements::dir_exists(current_path)) {
       const t_int status = mkdir(current_path.c_str(), ACCESSPERMS);
       if (status != 0)
         throw std::runtime_error("Error making recursive directory: " + current_path);
     }
     current_path += "/";
   }
   return;
 }
non_empty_outers()
template<class T0 , class STORAGE_INDEX_TYPE = t_int> std::set<STORAGE_INDEX_TYPE> purify::non_empty_outers (Eigen::SparseMatrixBase< T0 > const & matrix)
Indices of non empty outer indices.
Definition at line 61 of file IndexMapping.h.
Referenced by compress_outer(), and TEST_CASE().
{
   std::set<STORAGE_INDEX_TYPE> result;
   for (typename T0::Index k = 0; k < matrix.derived().outerSize(); ++k)
     for (typename T0::InnerIterator it(matrix.derived(), k); it; ++it)
       result.insert(static_cast<STORAGE_INDEX_TYPE>(it.col()));
   return result;
 }
split() [1/2]
template<typename T > void purify::split (const std::string & s, char delim, T result)
adds split string to container
Definition at line 50 of file read_measurements.h.
References split().
{
   std::stringstream ss(s);
   std::string item;
   while (std::getline(ss, item, delim)) {
     *(result++) = item;
   }
 };
split() [2/2]
std::vector< std::string > purify::split (const std::string & s, char delim)
splits string into vector
Definition at line 133 of file read_measurements.cc.
Referenced by mkdir_recursive(), and split().
{
   std::vector<std::string> elems;
   split(s, delim, std::back_inserter(elems));
   return elems;
 }
version()
std::string purify::version () inline
Returns library version.
Definition at line 36 of file config.in.h.
 { return "@Purify_VERSION@"; }
version_tuple()
std::tuple<uint8_t, uint8_t, uint8_t> purify::version_tuple () inline
Returns library version.
Definition at line 38 of file config.in.h.
{
   // clang-format off
   return std::tuple<uint8_t, uint8_t, uint8_t>(
       @Purify_VERSION_MAJOR@, @Purify_VERSION_MINOR@, @Purify_VERSION_PATCH@);
   // clang-format on
 }
Variable Documentation
stokes_int
const std::map<stokes, t_int> purify::stokes_int
Initial value:
= {{stokes::I, 1},   {stokes::Q, 2},   {stokes::U, 3},
                                            {stokes::V, 4},   {stokes::RR, -1}, {stokes::LL, -2},
                                            {stokes::RL, -3}, {stokes::LR, -4}, {stokes::XX, -5},
                                            {stokes::YY, -6}, {stokes::XY, -7}, {stokes::YX, -8}}
Definition at line 33 of file types.h.
Referenced by purify::pfitsio::header_params::header_params(), and TEST_CASE().
stokes_string
const std::map<std::string, stokes> purify::stokes_string
Initial value:
= {
    {"I", stokes::I},   {"i", stokes::I},   {"Q", stokes::Q},   {"q", stokes::Q},
    {"U", stokes::U},   {"u", stokes::U},   {"V", stokes::V},   {"v", stokes::V},
    {"XX", stokes::XX}, {"xx", stokes::XX}, {"YY", stokes::YY}, {"yy", stokes::YY},
    {"XY", stokes::XY}, {"xy", stokes::XY}, {"YX", stokes::YX}, {"yx", stokes::YX},
    {"LL", stokes::LL}, {"ll", stokes::LL}, {"RR", stokes::RR}, {"rr", stokes::RR},
    {"LR", stokes::LR}, {"lr", stokes::LR}, {"RL", stokes::RL}, {"rl", stokes::RL},
    {"P", stokes::P},   {"p", stokes::P}}
Definition at line 37 of file types.h.
Referenced by purify::YamlParser::parseAndSetGeneralConfiguration(), and TEST_CASE().