PURIFY: purify::pfitsio Namespace Reference
purify::pfitsio Namespace Reference
Classes
struct header_params
Functions
void write_key (fitsfile *fptr, const std::string &key, const std::string &value, const std::string &comment, int *status)
write key to fits file header
void write_key (fitsfile *fptr, const std::string &key, const char *value, const std::string &comment, int *status)
void write_history (fitsfile *fptr, const std::string &context, const std::string &history, int *status)
write history to fits file
void write2d (const Image< t_real > &eigen_image, const pfitsio::header_params &header, const bool &overwrite)
Write image to fits file.
void write2d (const Image< t_real > &image, const std::string &fits_name, const std::string &pix_units="Jy/Beam", const bool &overwrite=true)
Write image to fits file.
void write3d (const std::vector< Image< t_real >> &image, const pfitsio::header_params &header, const bool &overwrite=true)
Write cube to fits file using header information.
void write3d (const std::vector< Image< t_real >> &image, const std::string &fits_name, const std::string &pix_units="Jy/Beam", const bool &overwrite=true)
Write cube to fits file.
template<class T >
std::enable_if< std::is_scalar< T >::value, void >::type write_history (fitsfile *fptr, const std::string &context, const T &history, int *status)
template<class T >
std::enable_if< std::is_scalar< T >::value, void >::type write_key (fitsfile *fptr, const std::string &key, const T &value, const std::string &comment, int *status)
template<typename T >
T read_key (fitsfile *fptr, const std::string &key, int *status)
read fits key and return as tuple
template<typename DERIVED >
void write2d (const Eigen::EigenBase< DERIVED > &input, int nx, int ny, const std::string &fits_name, const std::string &pix_units="Jy/Beam", const bool &overwrite=true)
template<typename DERIVED >
void write2d (const Eigen::EigenBase< DERIVED > &input, int nx, int ny, const pfitsio::header_params &header, const bool overwrite=true)
template<typename DERIVED >
void write3d (const std::vector< Eigen::EigenBase< DERIVED >> &input, int nx, int ny, const std::string &fits_name, const std::string &pix_units="Jy/Beam", const bool &overwrite=true)
template<typename DERIVED >
void write3d (const std::vector< Eigen::EigenBase< DERIVED >> &input, int nx, int ny, const pfitsio::header_params &header, const bool &overwrite=true)
template<typename T >
std::enable_if< std::is_same< t_real, typename T::Scalar >::value, void >::type write3d (const Eigen::EigenBase< T > &image, const t_int rows, const t_int cols, const t_int chans, const std::string &fits_name, const std::string &pix_units="Jy/Beam", const bool &overwrite=true)
template<typename T >
std::enable_if< std::is_same< t_real, typename T::Scalar >::value, void >::type write3d (const Eigen::EigenBase< T > &image, const t_int rows, const t_int cols, const t_int chans, const pfitsio::header_params &header, const bool &overwrite)
write 3d fits cube with header
template<typename T , typename = std::enable_if_t<std::is_same_v<double, typename T::Scalar>>>
void read3d (const std::string &fits_name, Eigen::EigenBase< T > &output, int &rows, int &cols, int &channels, int &pols)
std::vector< Image< t_complex > > read3d (const std::string &fits_name)
Read cube from fits file.
Image< t_complex > read2d (const std::string &fits_name)
Read image from fits file.
utilities::vis_params read_uvfits (const std::vector< std::string > &names, const bool flag=true, const stokes pol=stokes::I)
Read uvfits files from name of vector.
utilities::vis_params read_uvfits (const std::string &vis_name2, const utilities::vis_params &u1, const bool flag=true, const stokes pol=stokes::I)
Reads in combine visiblities from uvfits files.
utilities::vis_params read_uvfits (const std::string &filename, const bool flag=true, const stokes pol=stokes::I)
Read uvfits file.
utilities::vis_params filter_and_combine (const utilities::vis_params &input, const utilities::vis_params &input2, const Vector< t_complex > &stokes_transform, const std::function< bool(t_real, t_real, t_real, t_complex, t_complex, t_real, t_real, t_real, t_complex, t_complex)> &filter=[](const t_real, const t_real, const t_real, const t_complex vis1, const t_complex weight1, const t_real, const t_real, const t_real, const t_complex vis2, const t_complex weight2) { return(weight1.real() > 0.) and(weight2.real() > 0.) and(std::abs(vis1) > 1e-20) and(std::abs(vis2) > 1e-20) and(!std::isnan(vis1.real()) and !std::isnan(vis1.imag())) and(!std::isnan(vis2.real()) and !std::isnan(vis2.imag()));})
Remove visibilities with zero weighting.
utilities::vis_params read_polarisation_with_flagging (const Vector< t_real > &data, const Matrix< t_real > &coords, const Vector< t_real > &frequencies, const t_uint pol_index1, const t_uint pol_index2, const t_uint pols, const t_uint baselines, const t_uint channels, const Vector< t_complex > stokes_transform, const std::function< bool(t_complex, t_complex, t_complex, t_complex)> &filter)
read polarisation with flaggging
utilities::vis_params read_polarisation (const Vector< t_real > &data, const Matrix< t_real > &coords, const Vector< t_real > &frequencies, const t_uint pol_index1, const t_uint pols, const t_uint baselines, const t_uint channels)
read polarisation data from uvfits data
Vector< t_real > read_uvfits_freq (fitsfile *fptr, int *status, const int &col)
read frequencies for each channel
void read_uvfits_freq (fitsfile *fptr, int *status, Vector< t_real > &output, const int &col)
Vector< t_real > read_uvfits_data (fitsfile *fptr, int *status, const std::vector< int > &naxis, const int &baselines)
read data from uvfits file
void read_uvfits_data (fitsfile *fptr, int *status, const std::vector< int > &naxis, const int &baselines, Vector< t_real > &output)
Matrix< t_real > read_uvfits_coords (fitsfile *fptr, int *status, const int &groups, const int &pcount)
read coordinates from uvfits file
t_real read_value_from_data (const Vector< t_real > &data, const t_uint col, const t_uint pol, const t_uint pols, const t_uint chan, const t_uint chans, const t_uint baseline, const t_uint baselines)
read value from data
t_complex read_vis_from_data (const Vector< t_real > &data, const t_uint pol, const t_uint pols, const t_uint chan, const t_uint chans, const t_uint baseline, const t_uint baselines)
return visibility for given baseline
t_complex read_weight_from_data (const Vector< t_real > &data, const t_uint pol, const t_uint pols, const t_uint chan, const t_uint chans, const t_uint baseline, const t_uint baselines)
return weight for given baseline
void read_uvfits_coords (fitsfile *fptr, int *status, const int &pcount, const int &groups, Matrix< t_real > &output)
void read_fits_keys (fitsfile *fptr, int *status)
Read uvfits keys out.
Function Documentation
filter_and_combine()
utilities::vis_params purify::pfitsio::filter_and_combine (const utilities::vis_params & input, const utilities::vis_params & input2, const Vector< t_complex > & stokes_transform, const std::function< bool(t_real, t_real, t_real, t_complex, t_complex, t_real, t_real, t_real, t_complex, t_complex)> & filter)
Remove visibilities with zero weighting.
Definition at line 175 of file uvfits.cc.
{
   t_uint size = 0;
   if (stokes_transform.size() != 2)
     throw std::runtime_error("stokes transform is not the right size (!= 2).");
   if (stokes_transform.isZero()) throw std::runtime_error("stokes transform not valid.");
   if (input.size() != input2.size())
     throw std::runtime_error("Cannot apply filter to each data set, sizes do not match.");
   for (int i = 0; i < input.size(); i++) {
     if (filter(input.u(i), input.v(i), input.w(i), input.vis(i), input.weights(i), input2.u(i),
                input2.v(i), input2.w(i), input2.vis(i), input2.weights(i))) {
       if (std::abs(input.u(i) - input2.u(i)) > 1e-6)
         throw std::runtime_error("baselines don't match for filter.");
       if (std::abs(input.v(i) - input2.v(i)) > 1e-6)
         throw std::runtime_error("baselines don't match for filter.");
       if (std::abs(input.w(i) - input2.w(i)) > 1e-6)
         throw std::runtime_error("baselines don't match for filter.");
       size++;
     }
   }
   PURIFY_LOW_LOG("Applying flags: Keeping {} out of {} data points.", size, input.size());
   utilities::vis_params output(Vector<t_real>::Zero(size), Vector<t_real>::Zero(size),
                                Vector<t_real>::Zero(size), Vector<t_complex>::Zero(size),
                                Vector<t_complex>::Zero(size), input.units, input.ra, input.dec,
                                input.average_frequency);
   output.time = Vector<t_real>::Zero(size);
   output.baseline = Vector<t_uint>::Zero(size);
   output.frequencies = input.frequencies;
   t_uint count = 0;
   for (t_uint i = 0; i < input.size(); i++)
     if (filter(input.u(i), input.v(i), input.w(i), input.vis(i), input.weights(i), input2.u(i),
                input2.v(i), input2.w(i), input2.vis(i), input2.weights(i))) {
       output.u(count) = input.u(i);
       output.v(count) = input.v(i);
       output.w(count) = input.w(i);
       output.vis(count) = input.vis(i) * stokes_transform(0) + input2.vis(i) * stokes_transform(1);
       output.weights(count) = 1. / std::sqrt(1. / input.weights(i) * stokes_transform(0) +
                                              1. / input2.weights(i) * stokes_transform(1));
       output.baseline(count) = input.baseline(i);
       output.time(count) = input.time(i);
       count++;
     }
   return output;
 }
References purify::utilities::vis_params::average_frequency, purify::utilities::vis_params::baseline, purify::utilities::vis_params::dec, purify::utilities::vis_params::frequencies, PURIFY_LOW_LOG, purify::utilities::vis_params::ra, purify::utilities::vis_params::size(), purify::utilities::vis_params::time, purify::utilities::vis_params::u, purify::utilities::vis_params::units, purify::utilities::vis_params::v, purify::utilities::vis_params::vis, purify::utilities::vis_params::w, and purify::utilities::vis_params::weights.
read2d()
Image<t_complex> purify::pfitsio::read2d (const std::string & fits_name)
Read image from fits file.
Definition at line 339 of file pfitsio.h.
{
   /*
     Reads in an image from a fits file and returns the image.
     fits_name:: name of fits file
   */
   const std::vector<Image<t_complex>> images = read3d(fits_name);
   return images.at(0);
 }
References read3d().
Referenced by main(), and TEST_CASE().
read3d() [1/2]
std::vector<Image<t_complex> > purify::pfitsio::read3d (const std::string & fits_name)
Read cube from fits file.
Definition at line 325 of file pfitsio.h.
{
   std::vector<Image<t_complex>> eigen_images;
   Vector<double> image;
   int rows, cols, channels, pols = 1;
   read3d<Vector<double>>(fits_name, image, rows, cols, channels, pols);
   for (int i = 0; i < channels; i++) {
     Vector<t_complex> eigen_image = Vector<t_complex>::Zero(rows * cols);
     eigen_image.real() = image.segment(i * rows * cols, rows * cols);
     eigen_images.push_back(Image<t_complex>::Map(eigen_image.data(), rows, cols));
   }
   return eigen_images;
 }
read3d() [2/2]
template<typename T , typename = std::enable_if_t<std::is_same_v<double, typename T::Scalar>>> void purify::pfitsio::read3d (const std::string & fits_name, Eigen::EigenBase< T > & output, int & rows, int & cols, int & channels, int & pols)
Definition at line 291 of file pfitsio.h.
{
   /*
      Reads in a cube from a fits file and returns the vector of images.
      fits_name:: name of fits file
    */
   fitsfile *fptr;
   int status = 0;
   PURIFY_LOW_LOG("Reading fits file {}", fits_name);
   if (fits_open_image(&fptr, fits_name.c_str(), READONLY, &status))
     throw std::runtime_error("Error opening image " + fits_name);
   const int naxis = pfitsio::read_key<int>(fptr, "NAXIS", &status);
   if (naxis < 1) throw std::runtime_error("Image contains zero axes.");
   rows = pfitsio::read_key<int>(fptr, "NAXIS1", &status);
   cols = (naxis > 1) ? pfitsio::read_key<int>(fptr, "NAXIS2", &status) : 1;
   channels = (naxis > 2) ? pfitsio::read_key<int>(fptr, "NAXIS3", &status) : 1;
   pols = (naxis > 3) ? pfitsio::read_key<int>(fptr, "NAXIS4", &status) : 1;
   PURIFY_LOW_LOG("Axes {}", naxis);
   std::vector<long> fpixel(naxis, 1);
   PURIFY_LOW_LOG("Dimensions {}x{}x{}x{}", rows, cols, channels, pols);
   if (pols > 1) throw std::runtime_error("Too many polarisations when reading " + fits_name);
   t_real nulval = 0;
   int anynul = 0;
   output.derived() = Vector<typename T::Scalar>::Zero(rows * cols * channels * pols);
   if (fits_read_pix(fptr, TDOUBLE, fpixel.data(), static_cast<long>(output.size()), &nulval,
                     output.derived().data(), &anynul, &status))
     throw std::runtime_error("Error reading data from image " + fits_name);
   if (anynul) PURIFY_LOW_LOG("There are bad values when reading " + fits_name);
   if (fits_close_file(fptr, &status))
     throw std::runtime_error("Problem closing fits file: " + fits_name);
 }
References PURIFY_LOW_LOG.
Referenced by main(), and read2d().
read_fits_keys()
void purify::pfitsio::read_fits_keys (fitsfile * fptr, int * status)
Read uvfits keys out.
Definition at line 405 of file uvfits.cc.
{
   std::shared_ptr<char> card =
       std::shared_ptr<char>(new char[FLEN_CARD], [](char *ptr) { delete[] ptr; });
   int nkeys;
   fits_get_hdrspace(fptr, &nkeys, NULL, status);
   for (int ii = 1; ii <= nkeys; ii++) {
     fits_read_record(fptr, ii, card.get(), status); /* read keyword */
     std::printf("%s\n", card.get());
   }
   std::printf("END\n\n"); /* terminate listing with END */
 }
read_key()
template<typename T > T purify::pfitsio::read_key (fitsfile * fptr, const std::string & key, int * status)
read fits key and return as tuple
Definition at line 122 of file pfitsio.h.
{
   T value;
   char comment[FLEN_COMMENT];
   if constexpr (std::is_same_v<T, std::string>) {
     if (fits_read_key(fptr, TSTRING, key.data(), value.data(), comment, status)) {
       throw std::runtime_error("Error reading value from key " + key);
     }
   } else {
     int datatype = 0;
     if (std::is_same<T, double>::value)
       datatype = TDOUBLE;
     else if (std::is_same_v<T, float>)
       datatype = TFLOAT;
     else if (std::is_same_v<T, int>)
       datatype = TINT;
     else if (std::is_same_v<T, bool>)
       datatype = TLOGICAL;
     else {
       throw std::runtime_error("Key type of value not supported by PURIFY template for " + key);
     }
     if (fits_read_key(fptr, datatype, key.data(), &value, comment, status)) {
       throw std::runtime_error("Error reading value from key " + key);
     }
   }
   return value;
 }
read_polarisation()
utilities::vis_params purify::pfitsio::read_polarisation (const Vector< t_real > & data, const Matrix< t_real > & coords, const Vector< t_real > & frequencies, const t_uint pol_index1, const t_uint pols, const t_uint baselines, const t_uint channels)
read polarisation data from uvfits data
Definition at line 284 of file uvfits.cc.
{
   const t_uint stride = channels * baselines;
   utilities::vis_params uv_data;
   uv_data.u = Vector<t_real>::Zero(stride);
   uv_data.v = Vector<t_real>::Zero(stride);
   uv_data.w = Vector<t_real>::Zero(stride);
   uv_data.time = Vector<t_real>::Zero(stride);
   uv_data.baseline = Vector<t_uint>::Zero(stride);
   uv_data.vis = Vector<t_complex>::Zero(stride);
   uv_data.weights = Vector<t_complex>::Zero(stride);
   if (pol_index1 >= pols) throw std::runtime_error("Polarisation index out of bounds.");
   // reading in data
   t_uint count = 0;
   for (t_uint c = 0; c < channels; c++)
     for (t_uint b = 0; b < baselines; b++) {
       uv_data.vis(count) = read_vis_from_data(data, pol_index1, pols, c, channels, b, baselines);
       uv_data.weights(count) =
           read_weight_from_data(data, pol_index1, pols, c, channels, b, baselines);
       count++;
     }
   uv_data.average_frequency = frequencies.array().mean();
   for (t_uint i = 0; i < frequencies.size(); i++) {
     uv_data.u.segment(i * baselines, baselines) = coords.row(0) * frequencies(i);
     uv_data.v.segment(i * baselines, baselines) = -coords.row(1) * frequencies(i);
     uv_data.w.segment(i * baselines, baselines) = coords.row(2) * frequencies(i);
     uv_data.baseline.segment(i * baselines, baselines) = coords.row(3).cast<t_uint>();
     uv_data.time.segment(i * baselines, baselines) = coords.row(4);
   }
   uv_data.frequencies = frequencies;
   uv_data.units = utilities::vis_units::lambda;
   return uv_data;
 }
References purify::utilities::vis_params::average_frequency, purify::utilities::vis_params::baseline, purify::constant::c, purify::utilities::vis_params::frequencies, purify::utilities::lambda, read_vis_from_data(), read_weight_from_data(), purify::utilities::vis_params::time, purify::utilities::vis_params::u, purify::utilities::vis_params::units, purify::utilities::vis_params::v, purify::utilities::vis_params::vis, purify::utilities::vis_params::w, and purify::utilities::vis_params::weights.
read_polarisation_with_flagging()
utilities::vis_params purify::pfitsio::read_polarisation_with_flagging (const Vector< t_real > & data, const Matrix< t_real > & coords, const Vector< t_real > & frequencies, const t_uint pol_index1, const t_uint pol_index2, const t_uint pols, const t_uint baselines, const t_uint channels, const Vector< t_complex > stokes_transform, const std::function< bool(t_complex, t_complex, t_complex, t_complex)> & filter)
read polarisation with flaggging
Definition at line 225 of file uvfits.cc.
{
   t_uint count = 0;
   for (t_uint c = 0; c < channels; c++)
     for (t_uint b = 0; b < baselines; b++) {
       t_complex const weight1 =
           read_weight_from_data(data, pol_index1, pols, c, channels, b, baselines);
       t_complex const weight2 =
           read_weight_from_data(data, pol_index2, pols, c, channels, b, baselines);
       t_complex const vis1 = read_vis_from_data(data, pol_index1, pols, c, channels, b, baselines);
       t_complex const vis2 = read_vis_from_data(data, pol_index2, pols, c, channels, b, baselines);
       if (filter(vis1, weight1, vis2, weight2)) count++;
     }
   const t_uint stride = count;
   utilities::vis_params uv_data;
   uv_data.u = Vector<t_real>::Zero(stride);
   uv_data.v = Vector<t_real>::Zero(stride);
   uv_data.w = Vector<t_real>::Zero(stride);
   uv_data.time = Vector<t_real>::Zero(stride);
   uv_data.baseline = Vector<t_uint>::Zero(stride);
   uv_data.vis = Vector<t_complex>::Zero(stride);
   uv_data.weights = Vector<t_complex>::Zero(stride);
   uv_data.average_frequency = frequencies.array().mean();
   if (pol_index1 >= pols) throw std::runtime_error("Polarisation index out of bounds.");
   if (pol_index2 >= pols) throw std::runtime_error("Polarisation index out of bounds.");
   PURIFY_LOW_LOG("Applying flags: Keeping {} out of {} data points.", stride, channels * baselines);
   // reading in data
   count = 0;
   for (t_uint c = 0; c < channels; c++)
     for (t_uint b = 0; b < baselines; b++) {
       t_complex const weight1 =
           read_weight_from_data(data, pol_index1, pols, c, channels, b, baselines);
       t_complex const weight2 =
           read_weight_from_data(data, pol_index2, pols, c, channels, b, baselines);
       t_complex const vis1 = read_vis_from_data(data, pol_index1, pols, c, channels, b, baselines);
       t_complex const vis2 = read_vis_from_data(data, pol_index2, pols, c, channels, b, baselines);
       // checking flags of both polarisations
       if (filter(vis1, weight1, vis2, weight2)) {
         uv_data.vis(count) = uv_data.vis(count) =
             vis1 * stokes_transform(0) + vis2 * stokes_transform(1);
         uv_data.weights(count) =
             1. / std::sqrt(1. / weight1 * stokes_transform(0) + 1. / weight2 * stokes_transform(1));
         uv_data.u(count) = coords(0, b) * frequencies(c);
         uv_data.v(count) = -coords(1, b) * frequencies(c);
         uv_data.w(count) = coords(2, b) * frequencies(c);
         uv_data.baseline(count) = static_cast<t_uint>(coords(3, b));
         uv_data.time(count) = coords(4, b);
         count++;
       }
     }
   assert(count == stride);
   uv_data.frequencies = frequencies;
   uv_data.units = utilities::vis_units::lambda;
   PURIFY_MEDIUM_LOG("All Data Read!");
   return uv_data;
 }
References purify::utilities::vis_params::average_frequency, purify::utilities::vis_params::baseline, purify::constant::c, purify::utilities::vis_params::frequencies, purify::utilities::lambda, PURIFY_LOW_LOG, PURIFY_MEDIUM_LOG, read_vis_from_data(), read_weight_from_data(), purify::utilities::vis_params::time, purify::utilities::vis_params::u, purify::utilities::vis_params::units, purify::utilities::vis_params::v, purify::utilities::vis_params::vis, purify::utilities::vis_params::w, and purify::utilities::vis_params::weights.
Referenced by read_uvfits().
read_uvfits() [1/3]
utilities::vis_params purify::pfitsio::read_uvfits (const std::string & filename, const bool flag, const stokes pol)
Read uvfits file.
Definition at line 49 of file uvfits.cc.
{
   fitsfile *fptr;
   int status = 0;
   int hdupos;
   int baselines;
   int naxes;
   int pcount;
   t_real ra = 0;
   t_real dec = 0;
   std::shared_ptr<char> comment =
       std::shared_ptr<char>(new char[FLEN_CARD], [](char *ptr) { delete[] ptr; });
   PURIFY_MEDIUM_LOG("Reading uvfits {}", filename);
   if (fits_open_file(&fptr, filename.c_str(), READONLY, &status))
     throw std::runtime_error("Could not open file " + filename);
   int hdutype;
   if (fits_movabs_hdu(fptr, 1, &hdutype, &status)) throw std::runtime_error("Error changing HDU.");
   if (hdutype != IMAGE_HDU)
     throw std::runtime_error("HDU 1 not expected type " + std::to_string(hdutype));
   fits_read_key(fptr, TDOUBLE, "CRVAL5", &ra, comment.get(), &status);
   fits_read_key(fptr, TDOUBLE, "CRVAL6", &dec, comment.get(), &status);
   fits_read_key(fptr, TINT, "GCOUNT", &baselines, comment.get(), &status);
   fits_read_key(fptr, TINT, "NAXIS", &naxes, comment.get(), &status);
   fits_read_key(fptr, TINT, "PCOUNT", &pcount, comment.get(), &status);
   if (naxes == 0) throw std::runtime_error("No axes in header... ");
   if (pcount == 0) throw std::runtime_error("No uvw or time coordinates in header... ");
   t_uint total = 1;
   std::vector<int> naxis(naxes, 0);
   // filling up axis sizes
   for (int i = 1; i < naxes; i++) {
     int n;
     std::string key = "NAXIS" + std::to_string(i + 1);
     fits_read_key(fptr, TINT, key.c_str(), &n, comment.get(), &status);
     naxis[i] = n;
     PURIFY_LOW_LOG("NAXIS {} Size: {}", i, n);
     total *= n;
   }
   const t_uint channels = naxis.at(3);
   const t_uint pols = naxis.at(2);
   const t_uint ifs = naxis.at(4);
   const t_uint pointings_num = naxis.at(5);
   PURIFY_LOW_LOG("RA: {} deg, Dec.: {} deg", ra, dec);
   PURIFY_MEDIUM_LOG("Pointings: {}", pointings_num);
   PURIFY_MEDIUM_LOG("IFs: {}", ifs);
   PURIFY_MEDIUM_LOG("Baselines: {}", baselines);
   PURIFY_MEDIUM_LOG("Channels: {}", channels);
   PURIFY_MEDIUM_LOG("Polarisations: {}", pols);
   PURIFY_LOW_LOG(
       "Purify currently assumes uvfits files are in XX YY XY YX format. Also will only read Stokes "
       "I for now.");
   PURIFY_MEDIUM_LOG("Total data per baseline: {}", total);
   if (pointings_num > 1) throw std::runtime_error("More than one pointing is not supported.");
   if (ifs > 1) throw std::runtime_error("More than one IF is not supported.");
   PURIFY_LOW_LOG("Reading Data...");
   const Matrix<t_real> coords = read_uvfits_coords(fptr, &status, baselines, pcount);
   //  (real, imag, weight, pol, frequency) is the order
   const Vector<t_real> data = read_uvfits_data(fptr, &status, naxis, baselines);
   const Vector<t_real> frequencies = read_uvfits_freq(fptr, &status, 4);
   if (frequencies.size() != channels)
     throw std::runtime_error("Number of frequencies doesn't match number of channels. " +
                              std::to_string(frequencies.size()) + "!=" + std::to_string(channels));
   int pol_index1;
   int pol_index2;
   Vector<t_complex> stokes_transform = Vector<t_complex>::Zero(2);
   switch (pol) {
   case stokes::I:
     pol_index1 = 0;
     pol_index2 = 1;
     stokes_transform(0) = 1. / 2;
     stokes_transform(1) = 1. / 2;
     break;
   case stokes::Q:
     throw std::runtime_error("Polarisation not supported for reading uvfits.");
     pol_index1 = 0;
     pol_index2 = 1;
     stokes_transform(0) = 1. / 2;
     stokes_transform(1) = -1. / 2;
     break;
   case stokes::U:
     throw std::runtime_error("Polarisation not supported for reading uvfits.");
     pol_index1 = 0;
     pol_index2 = 1;
     stokes_transform(0) = 1. / 2 * t_complex(0, -1);
     stokes_transform(1) = 1. / 2 * t_complex(0, -1);
     break;
   case stokes::V:
     throw std::runtime_error("Polarisation not supported for reading uvfits.");
     pol_index1 = 0;
     pol_index2 = 1;
     stokes_transform(0) = 1. / 2 * t_complex(0, -1);
     stokes_transform(1) = -1. / 2 * t_complex(0, -1);
     break;
   default:
     throw std::runtime_error("Polarisation not supported for reading uvfits.");
     pol_index1 = 0;
     pol_index2 = 1;
     stokes_transform(0) = 1. / 2;
     stokes_transform(1) = 1. / 2;
     break;
   }
   fits_close_file(fptr, &status);
   if (status) { /* print any error messages */
     fits_report_error(stderr, status);
     throw std::runtime_error("Error reading fits file...");
   }
   auto uv_data = read_polarisation_with_flagging(
       data, coords, frequencies, pol_index1, pol_index2, pols, baselines, channels,
       stokes_transform,
       [flag](const t_complex vis1, const t_complex weight1, const t_complex vis2,
              const t_complex weight2) {
         if (flag)
           return (weight1.real() > 0.) and (weight2.real() > 0.) and (std::abs(vis1) > 1e-20) and
                  (std::abs(vis2) > 1e-20) and
                  (!std::isnan(vis1.real()) and !std::isnan(vis1.imag())) and
                  (!std::isnan(vis2.real()) and !std::isnan(vis2.imag()));
         else
           return true;
       });
   uv_data.ra = ra;
   uv_data.dec = dec;
   return uv_data;
 }
References purify::I, PURIFY_LOW_LOG, PURIFY_MEDIUM_LOG, purify::Q, purify::utilities::vis_params::ra, read_polarisation_with_flagging(), read_uvfits_coords(), read_uvfits_data(), read_uvfits_freq(), purify::U, and purify::V.
read_uvfits() [2/3]
utilities::vis_params purify::pfitsio::read_uvfits (const std::string & vis_name2, const utilities::vis_params & uv1, const bool flag, const stokes pol)
Reads in combine visiblities from uvfits files.
Definition at line 20 of file uvfits.cc.
{
   utilities::vis_params uv;
   const bool w_term = not uv1.w.isZero(0);
   const auto uv2 = read_uvfits(vis_name2, flag, pol);
   if (std::abs(uv1.ra - uv2.ra) > 1e-6)
     throw std::runtime_error(vis_name2 + ": wrong RA in pointing.");
   if (std::abs(uv1.dec - uv2.dec) > 1e-6)
     throw std::runtime_error(vis_name2 + ": wrong DEC in pointing.");
   uv.ra = uv1.ra;
   uv.dec = uv1.dec;
   uv.u = Vector<t_real>::Zero(uv1.size() + uv2.size());
   uv.v = Vector<t_real>::Zero(uv1.size() + uv2.size());
   uv.w = Vector<t_real>::Zero(uv1.size() + uv2.size());
   uv.vis = Vector<t_complex>::Zero(uv1.size() + uv2.size());
   uv.weights = Vector<t_complex>::Zero(uv1.size() + uv2.size());
   uv.u.segment(0, uv1.size()) = uv1.u;
   uv.v.segment(0, uv1.size()) = uv1.v;
   uv.w.segment(0, uv1.size()) = uv1.w;
   uv.vis.segment(0, uv1.size()) = uv1.vis;
   uv.weights.segment(0, uv1.size()) = uv1.weights;
   uv.u.segment(uv1.size(), uv2.size()) = uv2.u;
   uv.v.segment(uv1.size(), uv2.size()) = uv2.v;
   uv.w.segment(uv1.size(), uv2.size()) = uv2.w;
   uv.vis.segment(uv1.size(), uv2.size()) = uv2.vis;
   uv.weights.segment(uv1.size(), uv2.size()) = uv2.weights;
   return uv;
 }
References purify::utilities::vis_params::dec, purify::utilities::vis_params::ra, read_uvfits(), purify::utilities::vis_params::size(), purify::utilities::vis_params::u, purify::utilities::vis_params::v, purify::utilities::vis_params::vis, purify::utilities::vis_params::w, and purify::utilities::vis_params::weights.
read_uvfits() [3/3]
utilities::vis_params purify::pfitsio::read_uvfits (const std::vector< std::string > & names, const bool flag, const stokes pol)
Read uvfits files from name of vector.
Definition at line 12 of file uvfits.cc.
{
   utilities::vis_params output = read_uvfits(names.at(0), flag, pol);
   if (names.size() == 1) return output;
   for (int i = 1; i < names.size(); i++) output = read_uvfits(names.at(i), output);
   return output;
 }
Referenced by main(), purify::read_measurements::read_measurements(), read_uvfits(), and TEST_CASE().
read_uvfits_coords() [1/2]
Matrix< t_real > purify::pfitsio::read_uvfits_coords (fitsfile * fptr, int * status, const int & groups, const int & pcount)
read coordinates from uvfits file
Definition at line 367 of file uvfits.cc.
{
   Matrix<t_real> output;
   read_uvfits_coords(fptr, status, pcount, groups, output);
   return output;
 }
Referenced by read_uvfits().
read_uvfits_coords() [2/2]
void purify::pfitsio::read_uvfits_coords (fitsfile * fptr, int * status, const int & pcount, const int & groups, Matrix< t_real > & output)
Definition at line 394 of file uvfits.cc.
{
   output = Matrix<t_real>::Zero(pcount, groups);
   int nulval = 0;
   int anynul;
   // reading in parameters per baseline
   for (int i = 0; i < groups; i++)
     fits_read_col(fptr, TDOUBLE, 1, 1 + i, 1, pcount, &nulval, output.col(i).data(), &anynul,
                   status);
 }
read_uvfits_data() [1/2]
Vector< t_real > purify::pfitsio::read_uvfits_data (fitsfile * fptr, int * status, const std::vector< int > & naxis, const int & baselines)
read data from uvfits file
Definition at line 346 of file uvfits.cc.
{
   Vector<t_real> output;
   read_uvfits_data(fptr, status, naxis, baselines, output);
   return output;
 }
Referenced by read_uvfits().
read_uvfits_data() [2/2]
void purify::pfitsio::read_uvfits_data (fitsfile * fptr, int * status, const std::vector< int > & naxis, const int & baselines, Vector< t_real > & output)
Definition at line 353 of file uvfits.cc.
{
   long nelements = 1;
   for (int i = 2; i < naxis.size(); i++) {
     nelements *= static_cast<long>(naxis.at(i));
   }
   if (nelements == 0) throw std::runtime_error("Zero number of elements.");
   output = Vector<t_real>::Zero(naxis.at(1) * nelements * baselines);
   int nulval = 0;
   int anynul = 0;
   fits_read_col(fptr, TDOUBLE, 2, 1, 1, static_cast<long>(output.size()), &nulval, output.data(),
                 &anynul, status);
 }
read_uvfits_freq() [1/2]
Vector< t_real > purify::pfitsio::read_uvfits_freq (fitsfile * fptr, int * status, const int & col)
read frequencies for each channel
Definition at line 320 of file uvfits.cc.
{
   Vector<t_real> output;
   read_uvfits_freq(fptr, status, output, col);
   return output;
 }
Referenced by read_uvfits().
read_uvfits_freq() [2/2]
void purify::pfitsio::read_uvfits_freq (fitsfile * fptr, int * status, Vector< t_real > & output, const int & col)
Definition at line 326 of file uvfits.cc.
{
   t_real cfreq;
   t_real dfreq;
   int crpix;
   int nfreq;
   std::shared_ptr<char> comment =
       std::shared_ptr<char>(new char[FLEN_CARD], [](char *ptr) { delete[] ptr; });
   std::string key = "CRVAL" + std::to_string(col);
   fits_read_key(fptr, TDOUBLE, key.c_str(), &cfreq, comment.get(), status);
   key = "CDELT" + std::to_string(col);
   fits_read_key(fptr, TDOUBLE, key.c_str(), &dfreq, comment.get(), status);
   key = "CRPIX" + std::to_string(col);
   fits_read_key(fptr, TINT, key.c_str(), &crpix, comment.get(), status);
   key = "NAXIS" + std::to_string(col);
   fits_read_key(fptr, TINT, key.c_str(), &nfreq, comment.get(), status);
   if (nfreq == 0) throw std::runtime_error("Wrong number of channels read from header.");
   output = Vector<t_real>::Zero(nfreq);
   for (int i = 0; i < output.size(); i++) output(i) = (i - nfreq * 0.5) * dfreq + cfreq;
 }
read_value_from_data()
t_real purify::pfitsio::read_value_from_data (const Vector< t_real > & data, const t_uint col, const t_uint pol, const t_uint pols, const t_uint chan, const t_uint chans, const t_uint baseline, const t_uint baselines)
read value from data
Definition at line 374 of file uvfits.cc.
{
   const t_uint index = col + 3 * (pol + pols * (chan + chans * baseline));
   return data(index);
 }
Referenced by read_vis_from_data(), and read_weight_from_data().
read_vis_from_data()
t_complex purify::pfitsio::read_vis_from_data (const Vector< t_real > & data, const t_uint pol, const t_uint pols, const t_uint chan, const t_uint chans, const t_uint baseline, const t_uint baselines)
return visibility for given baseline
Definition at line 381 of file uvfits.cc.
{
   return t_complex(read_value_from_data(data, 0, pol, pols, chan, chans, baseline, baselines),
                    read_value_from_data(data, 1, pol, pols, chan, chans, baseline, baselines));
 }
References read_value_from_data().
Referenced by read_polarisation(), and read_polarisation_with_flagging().
read_weight_from_data()
t_complex purify::pfitsio::read_weight_from_data (const Vector< t_real > & data, const t_uint pol, const t_uint pols, const t_uint chan, const t_uint chans, const t_uint baseline, const t_uint baselines)
return weight for given baseline
Definition at line 388 of file uvfits.cc.
{
   return t_complex(read_value_from_data(data, 2, pol, pols, chan, chans, baseline, baselines), 0);
 }
References read_value_from_data().
Referenced by read_polarisation(), and read_polarisation_with_flagging().
write2d() [1/4]
template<typename DERIVED > void purify::pfitsio::write2d (const Eigen::EigenBase< DERIVED > & input, int nx, int ny, const pfitsio::header_params & header, const bool overwrite = true)
Definition at line 165 of file pfitsio.h.
{
   Image<t_real> const data = input.derived().real().template cast<t_real>();
   write2d(Image<t_real>::Map(data.data(), nx, ny), header, overwrite);
 }
References write2d().
write2d() [2/4]
template<typename DERIVED > void purify::pfitsio::write2d (const Eigen::EigenBase< DERIVED > & input, int nx, int ny, const std::string & fits_name, const std::string & pix_units = "Jy/Beam", const bool & overwrite = true)
Definition at line 159 of file pfitsio.h.
{
   Image<t_real> const data = input.derived().real().template cast<t_real>();
   write2d(Image<t_real>::Map(data.data(), nx, ny), fits_name, pix_units, overwrite);
 }
References write2d().
write2d() [3/4]
void purify::pfitsio::write2d (const Image< t_real > & eigen_image, const pfitsio::header_params & header, const bool & overwrite)
Write image to fits file.
Write image to fits file using header information.
Definition at line 30 of file pfitsio.cc.
{
   /*
     Writes an image to a fits file.
     image:: image data, a 2d Image.
         header:: structure containing header information
         overwrite:: if true, overwrites old fits file with same name
   */
   write3d(std::vector<Image<t_real>>(1, eigen_image), header, overwrite);
 }
References write3d().
Referenced by purify::factory::add_updater(), main(), padmm(), padmm_factory(), and write2d().
write2d() [4/4]
void purify::pfitsio::write2d (const Image< t_real > & eigen_image, const std::string & fits_name, const std::string & pix_units, const bool & overwrite)
Write image to fits file.
Definition at line 44 of file pfitsio.cc.
{
   /*
     Writes an image to a fits file.
     image:: image data, a 2d Image.
     fits_name:: string containing the file name of the fits file.
     pix_units:: units of flux
     ra:: centre pixel coordinate in ra
     dec:: centre pixel coordinate in dec
   */
   pfitsio::header_params header;
   header.fits_name = fits_name;
   header.pix_units = pix_units;
   write2d(eigen_image, header, overwrite);
 }
References purify::pfitsio::header_params::fits_name, purify::pfitsio::header_params::pix_units, and write2d().
write3d() [1/6]
template<typename T > std::enable_if<std::is_same<t_real, typename T::Scalar>::value, void>::type purify::pfitsio::write3d (const Eigen::EigenBase< T > & image, const t_int rows, const t_int cols, const t_int chans, const pfitsio::header_params & header, const bool & overwrite)
write 3d fits cube with header
Definition at line 214 of file pfitsio.h.
{
   /*
      Writes an image to a fits file.
      image:: image data, a 2d Image.
      header:: structure containing header information
      overwrite:: if true, overwrites old fits file with same name
   */
   if (image.size() != rows * cols * chans)
     throw std::runtime_error("image or cube size does not match dimensions.");
   PURIFY_LOW_LOG("Writing fits file {}", header.fits_name);
   if (overwrite == true) {
     remove(header.fits_name.c_str());
   }
   fitsfile *fptr;
   int status = 0;
   std::vector<long> naxes = {static_cast<long>(rows), static_cast<long>(cols),
                              static_cast<long>(chans), 1};
   std::vector<long> fpixel = {1, 1, 1, 1};
   if (fits_create_file(&fptr, header.fits_name.c_str(), &status))
     throw std::runtime_error("Problem creating fits file:" + header.fits_name);
   if (fits_create_img(fptr, DOUBLE_IMG, static_cast<t_int>(naxes.size()), naxes.data(), &status))
     throw std::runtime_error("Problem creating HDU for image in fits file:" + header.fits_name);
   if (fits_write_pix(fptr, TDOUBLE, fpixel.data(), static_cast<long>(image.size()),
                      const_cast<t_real *>(image.derived().data()), &status))
     throw std::runtime_error("Problem writing image in fits file:" + header.fits_name);
 #define PURIFY_MACRO(KEY, VALUE, COMMENT) write_key(fptr, KEY, VALUE, COMMENT, &status);
   // Writing to fits header
   PURIFY_MACRO("BUNIT", header.pix_units, "");                  // units
   PURIFY_MACRO("NAXIS", static_cast<t_int>(naxes.size()), "");  // number of axes
   PURIFY_MACRO("NAXIS1", static_cast<t_int>(naxes.at(0)), "");
   PURIFY_MACRO("NAXIS2", static_cast<t_int>(naxes.at(1)), "");
   PURIFY_MACRO("NAXIS3", static_cast<t_int>(naxes.at(2)), "");
   PURIFY_MACRO("NAXIS4", static_cast<t_int>(naxes.at(3)), "");
   PURIFY_MACRO("CRPIX1", static_cast<t_int>(std::floor(naxes.at(0) / 2)) + 1, "");
   PURIFY_MACRO("CRPIX2", static_cast<t_int>(std::floor(naxes.at(1) / 2)) + 1, "");
   PURIFY_MACRO("CRPIX3", 1, "");
   PURIFY_MACRO("CRPIX4", 1, "");
   PURIFY_MACRO("CRVAL1", static_cast<t_real>(header.ra * 180. / purify::constant::pi), "");
   PURIFY_MACRO("CRVAL2", static_cast<t_real>(header.dec * 180. / purify::constant::pi), "");
   PURIFY_MACRO("CRVAL3", static_cast<t_real>(header.mean_frequency * 1.), "");
   PURIFY_MACRO("CRVAL4", static_cast<t_real>(1), "");
   PURIFY_MACRO("CTYPE1", "RA--SIN", "");
   PURIFY_MACRO("CTYPE2", "DEC--SIN", "");
   PURIFY_MACRO("CTYPE3", "FREQ", "");
   PURIFY_MACRO("CTYPE4", "STOKES", "");
   PURIFY_MACRO("CDELT1", static_cast<t_real>(-header.cell_x / 3600.), "");
   PURIFY_MACRO("CDELT2", static_cast<t_real>(header.cell_y / 3600.), "");
   PURIFY_MACRO("CDELT3", static_cast<t_real>(header.channel_width * 1.), "");
   PURIFY_MACRO("CDELT4", 1., "");
   PURIFY_MACRO("BTYPE", "intensity", "");
   PURIFY_MACRO("EQUINOX", 2000, "");
 #undef PURIFY_MACRO
   write_history(fptr, "SOFTWARE", "Purify", &status);
   write_history(fptr, "PURIFY-NITERS", header.niters, &status);
   if (header.hasconverged) {
     write_history(fptr, "PURIFY-CONVERGED", "True", &status);
   } else {
     write_history(fptr, "PURIFY-CONVERGED", "False", &status);
   }
   write_history(fptr, "PURIFY-RELATIVEVARIATION", header.relative_variation, &status);
   write_history(fptr, "PURIFY-RESIDUALCONVERGENCE", header.residual_convergence, &status);
   write_history(fptr, "PURIFY-EPSILON", header.epsilon, &status);
   if (fits_write_date(fptr, &status))
     throw std::runtime_error("Problem writing date in fits file:" + header.fits_name);
   if (fits_close_file(fptr, &status))
     throw std::runtime_error("Problem closing fits file:" + header.fits_name);
 }
References purify::pfitsio::header_params::cell_x, purify::pfitsio::header_params::cell_y, purify::pfitsio::header_params::channel_width, purify::pfitsio::header_params::dec, purify::pfitsio::header_params::epsilon, purify::pfitsio::header_params::fits_name, purify::pfitsio::header_params::hasconverged, purify::pfitsio::header_params::mean_frequency, purify::pfitsio::header_params::niters, purify::constant::pi, purify::pfitsio::header_params::pix_units, PURIFY_LOW_LOG, PURIFY_MACRO, purify::pfitsio::header_params::ra, purify::pfitsio::header_params::relative_variation, purify::pfitsio::header_params::residual_convergence, and write_history().
write3d() [2/6]
template<typename T > std::enable_if<std::is_same<t_real, typename T::Scalar>::value, void>::type purify::pfitsio::write3d (const Eigen::EigenBase< T > & image, const t_int rows, const t_int cols, const t_int chans, const std::string & fits_name, const std::string & pix_units = "Jy/Beam", const bool & overwrite = true)
Definition at line 202 of file pfitsio.h.
{
   pfitsio::header_params header;
   header.fits_name = fits_name;
   header.pix_units = pix_units;
   write3d<T>(image, rows, cols, chans, header, overwrite);
 }
References purify::pfitsio::header_params::fits_name, and purify::pfitsio::header_params::pix_units.
write3d() [3/6]
template<typename DERIVED > void purify::pfitsio::write3d (const std::vector< Eigen::EigenBase< DERIVED >> & input, int nx, int ny, const pfitsio::header_params & header, const bool & overwrite = true)
Definition at line 191 of file pfitsio.h.
{
   std::vector<Image<t_real>> images;
   for (int i = 0; i < input.size(); i++) {
     Image<t_real> const data = input.derived().real().template cast<t_real>();
     images.push_back(Image<t_real>::Map(data.data(), nx, ny));
   }
   write3d(images, header, overwrite);
 }
References write3d().
write3d() [4/6]
template<typename DERIVED > void purify::pfitsio::write3d (const std::vector< Eigen::EigenBase< DERIVED >> & input, int nx, int ny, const std::string & fits_name, const std::string & pix_units = "Jy/Beam", const bool & overwrite = true)
Definition at line 180 of file pfitsio.h.
{
   std::vector<Image<t_real>> images;
   for (int i = 0; i < input.size(); i++) {
     Image<t_real> const data = input.derived().real().template cast<t_real>();
     images.push_back(Image<t_real>::Map(data.data(), nx, ny));
   }
   write3d(images, fits_name, pix_units, overwrite);
 }
References write3d().
write3d() [5/6]
void purify::pfitsio::write3d (const std::vector< Image< t_real >> & eigen_images, const pfitsio::header_params & header, const bool & overwrite)
Write cube to fits file using header information.
Definition at line 63 of file pfitsio.cc.
{
   std::vector<long> naxes = {static_cast<long>(eigen_images.at(0).rows()),
                              static_cast<long>(eigen_images.at(0).cols()),
                              static_cast<long>(eigen_images.size()), 1};
   std::vector<long> fpixel = {1, 1, 1, 1};
   Vector<t_real> image = Vector<t_real>::Zero(naxes.at(0) * naxes.at(1) * naxes.at(2));
   for (int i = 0; i < eigen_images.size(); i++)
     image.segment(i * naxes.at(0) * naxes.at(1), naxes.at(0) * naxes.at(1)) =
         Vector<t_real>::Map(eigen_images.at(i).data(), naxes.at(0) * naxes.at(1));
   write3d<Vector<t_real>>(image, naxes.at(0), naxes.at(1), naxes.at(2), header, overwrite);
 }
Referenced by write2d(), and write3d().
write3d() [6/6]
void purify::pfitsio::write3d (const std::vector< Image< t_real >> & eigen_images, const std::string & fits_name, const std::string & pix_units, const bool & overwrite)
Write cube to fits file.
Definition at line 77 of file pfitsio.cc.
{
   /*
      Writes a vector of images to a fits file.
      image:: image data, a 3d Image.
      fits_name:: string containing the file name of the fits file.
      pix_units:: units of flux
      ra:: centre pixel coordinate in ra
      dec:: centre pixel coordinate in dec
 */
   pfitsio::header_params header;
   header.fits_name = fits_name;
   header.pix_units = pix_units;
   write3d(eigen_images, header, overwrite);
 }
References purify::pfitsio::header_params::fits_name, purify::pfitsio::header_params::pix_units, and write3d().
write_history() [1/2]
void purify::pfitsio::write_history (fitsfile * fptr, const std::string & context, const std::string & history, int * status)
write history to fits file
Definition at line 22 of file pfitsio.cc.
{
   const std::string entry = context + ": " + history;
   if (fits_write_history(fptr, const_cast<char *>(entry.c_str()), status))
     throw std::runtime_error("Problem writing comments in fits file");
 }
Referenced by write3d(), and write_history().
write_history() [2/2]
template<class T > std::enable_if<std::is_scalar<T>::value, void>::type purify::pfitsio::write_history (fitsfile * fptr, const std::string & context, const T & history, int * status)
Definition at line 88 of file pfitsio.h.
{
   T value = history;
   write_history(fptr, context, std::to_string(value), status);
 }
References write_history().
write_key() [1/3]
void purify::pfitsio::write_key (fitsfile * fptr, const std::string & key, const char * value, const std::string & comment, int * status)
Definition at line 17 of file pfitsio.cc.
{
   write_key(fptr, key, std::string(value), comment, status);
 }
References write_key().
write_key() [2/3]
void purify::pfitsio::write_key (fitsfile * fptr, const std::string & key, const std::string & value, const std::string & comment, int * status)
write key to fits file header
Definition at line 8 of file pfitsio.cc.
{
   std::string entry = value;
   if (fits_write_key(fptr, TSTRING, const_cast<char *>(key.c_str()),
                      reinterpret_cast<void *>(const_cast<char *>(entry.c_str())),
                      const_cast<char *>(comment.c_str()), status))
     throw std::runtime_error("Problem writing key in fits file: " + key);
 }
Referenced by write_key().
write_key() [3/3]
template<class T > std::enable_if<std::is_scalar<T>::value, void>::type purify::pfitsio::write_key (fitsfile * fptr, const std::string & key, const T & value, const std::string & comment, int * status)
Definition at line 95 of file pfitsio.h.
{
   int datatype = 0;
   if (std::is_same<T, double>::value)
     datatype = TDOUBLE;
   else if (std::is_same<T, float>::value)
     datatype = TFLOAT;
   else if (std::is_same<T, int>::value)
     datatype = TINT;
   else if (std::is_same<T, t_int>::value)
     datatype = TINT;
   else if (std::is_same<T, bool>::value)
     datatype = TLOGICAL;
   else
     throw std::runtime_error("Key type of value not supported by PURIFY template for " + key);
   T entry = value;
   if (fits_write_key(fptr, datatype, const_cast<char *>(key.c_str()),
                      reinterpret_cast<void *>(&entry), const_cast<char *>(comment.c_str()), status))
     throw std::runtime_error("Problem writing key in fits file: " + key);
 }