PURIFY: purify::measurementoperator Namespace Reference
purify::measurementoperator Namespace Reference
Functions
template<class T >
std::shared_ptr< sopt::LinearTransform< T > > init_degrid_operator_2d (const Vector< t_real > &u, const Vector< t_real > &v, const Vector< t_real > &w, const Vector< t_complex > &weights, const t_uint &imsizey, const t_uint &imsizex, const t_real &oversample_ratio=2, const kernels::kernel kernel=kernels::kernel::kb, const t_uint Ju=4, const t_uint Jv=4, const bool w_stacking=false, const t_real &cellx=1, const t_real &celly=1)
Returns linear transform that is the standard degridding operator.
template<class T >
std::shared_ptr< sopt::LinearTransform< T > > init_degrid_operator_2d (const utilities::vis_params &uv_vis_input, const t_uint &imsizey, const t_uint &imsizex, const t_real &cell_x, const t_real &cell_y, const t_real &oversample_ratio=2, const kernels::kernel kernel=kernels::kernel::kb, const t_uint Ju=4, const t_uint Jv=4, const bool w_stacking=false)
template<class T >
std::shared_ptr< sopt::LinearTransform< T > > init_degrid_operator_2d (const Vector< t_real > &u, const Vector< t_real > &v, const Vector< t_real > &w, const Vector< t_complex > &weights, const t_uint imsizey, const t_uint imsizex, const t_real oversample_ratio, const kernels::kernel kernel, const t_uint Ju, const t_uint Jw, const bool w_stacking, const t_real cellx, const t_real celly, const t_real absolute_error, const t_real relative_error, const dde_type dde)
Returns linear transform that is the standard degridding operator.
template<class T >
std::shared_ptr< sopt::LinearTransform< T > > init_degrid_operator_2d (const utilities::vis_params &uv_vis_input, const t_uint imsizey, const t_uint imsizex, const t_real cell_x, const t_real cell_y, const t_real oversample_ratio, const kernels::kernel kernel, const t_uint Ju, const t_uint Jw, const bool w_stacking, const t_real absolute_error, const t_real relative_error, const dde_type dde)
Function Documentation
init_degrid_operator_2d() [1/4]
template<class T > std::shared_ptr<sopt::LinearTransform<T> > purify::measurementoperator::init_degrid_operator_2d (const Vector< t_real > & u, const Vector< t_real > & v, const Vector< t_real > & w, const Vector< t_complex > & weights, const t_uint imsizey, const t_uint imsizex, const t_real oversample_ratio, const kernels::kernel kernel, const t_uint Ju, const t_uint Jw, const bool w_stacking, const t_real cellx, const t_real celly, const t_real absolute_error, const t_real relative_error, const dde_type dde)
Returns linear transform that is the standard degridding operator.
Definition at line 116 of file wproj_operators.h.
References purify::operators::measure, N, operators_test::u, operators_test::v, and purify::utilities::w_stacking().
{
   const operators::fftw_plan ft_plan = operators::fftw_plan::measure;
   std::array<t_int, 3> N = {0, 1, static_cast<t_int>(imsizey * imsizex)};
   std::array<t_int, 3> M = {0, 1, static_cast<t_int>(u.size())};
   sopt::OperatorFunction<T> directDegrid, indirectDegrid;
   std::tie(directDegrid, indirectDegrid) = purify::operators::base_degrid_operator_2d<T>(
       u, v, w, weights, imsizey, imsizex, oversample_ratio, kernel, Ju, Jw, ft_plan, w_stacking,
       cellx, celly, absolute_error, relative_error, dde);
   auto direct = directDegrid;
   auto indirect = indirectDegrid;
   return std::make_shared<sopt::LinearTransform<T>>(direct, M, indirect, N);
 }
init_degrid_operator_2d() [2/4]
template<class T > std::shared_ptr<sopt::LinearTransform<T> > purify::measurementoperator::init_degrid_operator_2d (const utilities::vis_params & uv_vis_input, const t_uint imsizey, const t_uint imsizex, const t_real cell_x, const t_real cell_y, const t_real oversample_ratio, const kernels::kernel kernel, const t_uint Ju, const t_uint Jw, const bool w_stacking, const t_real absolute_error, const t_real relative_error, const dde_type dde)
Definition at line 134 of file wproj_operators.h.
References purify::utilities::lambda, purify::operators::measure, N, purify::utilities::radians, purify::utilities::set_cell_size(), operators_test::u, purify::utilities::uv_scale(), operators_test::v, and purify::utilities::w_stacking().
{
   auto uv_vis = uv_vis_input;
   if (uv_vis.units == utilities::vis_units::lambda)
     uv_vis = utilities::set_cell_size(uv_vis, cell_x, cell_y);
   if (uv_vis.units == utilities::vis_units::radians)
     uv_vis = utilities::uv_scale(uv_vis, std::floor(oversample_ratio * imsizex),
                                  std::floor(oversample_ratio * imsizey));
   return init_degrid_operator_2d<T>(uv_vis.u, uv_vis.v, uv_vis.w, uv_vis.weights, imsizey, imsizex,
                                     oversample_ratio, kernel, Ju, Jw, w_stacking, cell_x, cell_y,
                                     absolute_error, relative_error, dde);
 }
init_degrid_operator_2d() [3/4]
template<class T > std::shared_ptr<sopt::LinearTransform<T> > purify::measurementoperator::init_degrid_operator_2d (const Vector< t_real > & u, const Vector< t_real > & v, const Vector< t_real > & w, const Vector< t_complex > & weights, const t_uint & imsizey, const t_uint & imsizex, const t_real & oversample_ratio = 2, const kernels::kernel kernel = kernels::kernel::kb, const t_uint Ju = 4, const t_uint Jv = 4, const bool w_stacking = false, const t_real & cellx = 1, const t_real & celly = 1)
Returns linear transform that is the standard degridding operator.
Definition at line 361 of file operators.h.
References purify::operators::measure, N, operators_test::u, operators_test::v, and purify::utilities::w_stacking().
Referenced by degrid_operator_ctor(), main(), purify::factory::measurement_operator_factory(), padmm(), DegridOperatorFixture::SetUp(), and TEST_CASE().
{
   const operators::fftw_plan ft_plan = operators::fftw_plan::measure;
   std::array<t_int, 3> N = {0, 1, static_cast<t_int>(imsizey * imsizex)};
   std::array<t_int, 3> M = {0, 1, static_cast<t_int>(u.size())};
   sopt::OperatorFunction<T> directDegrid, indirectDegrid;
   std::tie(directDegrid, indirectDegrid) = purify::operators::base_degrid_operator_2d<T>(
       u, v, w, weights, imsizey, imsizex, oversample_ratio, kernel, Ju, Jv, ft_plan, w_stacking,
       cellx, celly);
   return std::make_shared<sopt::LinearTransform<T>>(directDegrid, M, indirectDegrid, N);
 }
init_degrid_operator_2d() [4/4]
template<class T > std::shared_ptr<sopt::LinearTransform<T> > purify::measurementoperator::init_degrid_operator_2d (const utilities::vis_params & uv_vis_input, const t_uint & imsizey, const t_uint & imsizex, const t_real & cell_x, const t_real & cell_y, const t_real & oversample_ratio = 2, const kernels::kernel kernel = kernels::kernel::kb, const t_uint Ju = 4, const t_uint Jv = 4, const bool w_stacking = false)
Definition at line 378 of file operators.h.
References purify::kernels::kb, purify::utilities::lambda, purify::operators::measure, N, purify::utilities::radians, purify::utilities::set_cell_size(), operators_test::u, purify::utilities::uv_scale(), operators_test::v, and purify::utilities::w_stacking().
{
   auto uv_vis = uv_vis_input;
   if (uv_vis.units == utilities::vis_units::lambda)
     uv_vis = utilities::set_cell_size(uv_vis, cell_x, cell_y);
   if (uv_vis.units == utilities::vis_units::radians)
     uv_vis = utilities::uv_scale(uv_vis, std::floor(oversample_ratio * imsizex),
                                  std::floor(oversample_ratio * imsizey));
   return init_degrid_operator_2d<T>(uv_vis.u, uv_vis.v, uv_vis.w, uv_vis.weights, imsizey, imsizex,
                                     oversample_ratio, kernel, Ju, Jv, w_stacking, cell_x, cell_y);
 }