PURIFY: purify::widefield Namespace Reference
purify::widefield Namespace Reference
Functions
t_int w_support (const t_real w, const t_real du, const t_int min, const t_int max)
estaimte support size of w given u resolution du
t_real pixel_to_lambda (const t_real cell, const t_uint imsize, const t_real oversample_ratio)
return factors to convert between arcsecond pixel size image space and lambda for uv space
t_real estimate_cell_size (const t_real max_u, const t_uint imsize, const t_real oversample_ratio)
return cell size from the bandwidth
t_real fov_cosine (t_real const cell, t_uint const imsize)
Work out max L and M directional cosines from image parameters.
t_real equivalent_miriad_cell_size (const t_real cell, const t_uint imsize, const t_real oversample_ratio)
for a given purify cell size in arcsec provide the equivalent miriad cell size in arcsec
Matrix< t_complex > generate_chirp (const t_real w_rate, const t_real cell_x, const t_real cell_y, const t_uint x_size, const t_uint y_size)
Generates image of chirp.
Matrix< t_complex > estimate_sample_density (const Vector< t_real > &u, const Vector< t_real > &v, const t_real cellx, const t_real celly, const t_uint imsizex, const t_uint imsizey, const t_real oversample_ratio, const t_real scale)
estimate sample desity grid for a given field of view
Vector< t_complex > sample_density_weights (const Vector< t_real > &u, const Vector< t_real > &v, const t_real cellx, const t_real celly, const t_uint imsizex, const t_uint imsizey, const t_real oversample_ratio, const t_real scale)
create sample density weights for a given field of view, uniform weighting
template<class DDE >
Matrix< t_complex > generate_dde (const DDE &dde, const t_real cell_x, const t_real cell_y, const t_uint x_size, const t_uint y_size, const t_real stop_gap)
Generate image of DDE for aw-stacking.
template<class DDE >
Matrix< t_complex > generate_chirp (const DDE &dde, const t_real w_rate, const t_real cell_x, const t_real cell_y, const t_uint x_size, const t_uint y_size, const t_real stop_gap=0.1)
generates image of chirp and DDE
Function Documentation
equivalent_miriad_cell_size()
t_real purify::widefield::equivalent_miriad_cell_size (const t_real cell, const t_uint imsize, const t_real oversample_ratio)
for a given purify cell size in arcsec provide the equivalent miriad cell size in arcsec
Definition at line 28 of file wide_field_utilities.cc.
References purify::constant::pi, and pixel_to_lambda().
Referenced by main(), and TEST_CASE().
{
   const t_real du = pixel_to_lambda(cell, imsize, oversample_ratio);
   return 60. * 60. * 180. / (static_cast<t_real>(imsize) * oversample_ratio * du * constant::pi);
 }
estimate_cell_size()
t_real purify::widefield::estimate_cell_size (const t_real max_u, const t_uint imsize, const t_real oversample_ratio)
return cell size from the bandwidth
Definition at line 15 of file wide_field_utilities.cc.
References purify::constant::pi.
Referenced by main().
{
   return (2. / static_cast<t_real>(imsize)) *
          std::asin(static_cast<t_real>(imsize) / (4 * oversample_ratio * max_u)) * 60. * 60. *
          180. / constant::pi;
 }
estimate_sample_density()
Matrix< t_complex > purify::widefield::estimate_sample_density (const Vector< t_real > & u, const Vector< t_real > & v, const t_real cellx, const t_real celly, const t_uint imsizex, const t_uint imsizey, const t_real oversample_ratio, const t_real scale)
estimate sample desity grid for a given field of view
Definition at line 39 of file wide_field_utilities.cc.
References purify::utilities::mod(), pixel_to_lambda(), operators_test::u, and operators_test::v.
Referenced by sample_density_weights().
{
   const t_int ftsizeu = std::floor(oversample_ratio * imsizex);
   const t_int ftsizev = std::floor(oversample_ratio * imsizex);
   Matrix<t_complex> sample_density = Matrix<t_complex>::Zero(ftsizev, ftsizeu);
   const t_real du = pixel_to_lambda(cellx, imsizex, oversample_ratio) * scale;
   const t_real dv = pixel_to_lambda(celly, imsizey, oversample_ratio) * scale;
   for (t_int i = 0; i < u.size(); ++i) {
     const t_int q = utilities::mod(floor(u(i) * du), ftsizeu);
     const t_int p = utilities::mod(floor(v(i) * dv), ftsizev);
     sample_density(p, q) += 1.;
   }
   return sample_density;
 }
fov_cosine()
t_real purify::widefield::fov_cosine (t_real const cell, t_uint const imsize)
Work out max L and M directional cosines from image parameters.
Definition at line 21 of file wide_field_utilities.cc.
References purify::constant::pi.
Referenced by generate_dde(), and pixel_to_lambda().
{
   const t_real theta_FoV_L = imsize * cell;
   const t_real extra_theta = (theta_FoV_L > 180. * 60. * 60.) ? theta_FoV_L - 180. * 60. * 60. : 0.;
   return 2 * std::sin(constant::pi / 180. * (theta_FoV_L - extra_theta) / (60. * 60.) * 0.5) +
          2 * std::sin(constant::pi / 180. * extra_theta / (60. * 60.) * 0.5);
 }
generate_chirp() [1/2]
Matrix< t_complex > purify::widefield::generate_chirp (const t_real w_rate, const t_real cell_x, const t_real cell_y, const t_uint x_size, const t_uint y_size)
Generates image of chirp.
Definition at line 34 of file wide_field_utilities.cc.
Referenced by generate_chirp(), purify::details::init_correction2d(), and purify::details::init_correction_radial_2d().
{
   return generate_chirp([](t_real, t_real) { return 1.; }, w_rate, cell_x, cell_y, x_size, y_size);
 }
generate_chirp() [2/2]
template<class DDE > Matrix<t_complex> purify::widefield::generate_chirp (const DDE & dde, const t_real w_rate, const t_real cell_x, const t_real cell_y, const t_uint x_size, const t_uint y_size, const t_real stop_gap = 0.1)
generates image of chirp and DDE
Definition at line 64 of file wide_field_utilities.h.
References generate_chirp(), generate_dde(), purify::I, and purify::constant::pi.
{
   const t_real nz = y_size * x_size;
   const t_complex I(0, 1);
   const auto chirp = [=](const t_real y, const t_real x) {
     return dde(y, x) *
            (std::exp(-2 * constant::pi * I * w_rate * (std::sqrt(1 - x * x - y * y) - 1))) /
            std::sqrt(1 - x * x - y * y) / nz;
   };
   return generate_dde(chirp, cell_x, cell_y, x_size, y_size, stop_gap);
 }
generate_dde()
template<class DDE > Matrix<t_complex> purify::widefield::generate_dde (const DDE & dde, const t_real cell_x, const t_real cell_y, const t_uint x_size, const t_uint y_size, const t_real stop_gap)
Generate image of DDE for aw-stacking.
Definition at line 43 of file wide_field_utilities.h.
References fov_cosine().
Referenced by generate_chirp(), and TEST_CASE().
{
   assert(stop_gap <= 1);
   const t_real L = fov_cosine(cell_x, x_size);
   const t_real M = fov_cosine(cell_y, y_size);
   const t_real delt_x = L / x_size;
   const t_real delt_y = M / y_size;
   Image<t_complex> output = Image<t_complex>::Zero(y_size, x_size);
   for (t_int l = 0; l < x_size; ++l)
     for (t_int m = 0; m < y_size; ++m) {
       const t_real x = (l - x_size * 0.5) * delt_x;
       const t_real y = (m - y_size * 0.5) * delt_y;
       output(m, l) = ((x * x + y * y) < 1 - stop_gap) ? dde(y, x) : 0.;
     }
   return output;
 };
pixel_to_lambda()
t_real purify::widefield::pixel_to_lambda (const t_real cell, const t_uint imsize, const t_real oversample_ratio)
return factors to convert between arcsecond pixel size image space and lambda for uv space
Definition at line 11 of file wide_field_utilities.cc.
References fov_cosine().
Referenced by purify::utilities::convert_to_pixels(), equivalent_miriad_cell_size(), estimate_sample_density(), purify::details::init_gridding_matrix_2d(), main(), sample_density_weights(), DegridOperatorCtorFixturePar::SetUp(), and TEST_CASE().
{
   return 1. / (oversample_ratio * fov_cosine(cell, imsize));
 }
sample_density_weights()
Vector< t_complex > purify::widefield::sample_density_weights (const Vector< t_real > & u, const Vector< t_real > & v, const t_real cellx, const t_real celly, const t_uint imsizex, const t_uint imsizey, const t_real oversample_ratio, const t_real scale)
create sample density weights for a given field of view, uniform weighting
Definition at line 56 of file wide_field_utilities.cc.
References estimate_sample_density(), purify::utilities::mod(), pixel_to_lambda(), operators_test::u, and operators_test::v.
Referenced by main(), and TEST_CASE().
{
   Vector<t_complex> weights = Vector<t_complex>::Zero(u.size());
   const t_int ftsizeu = std::floor(oversample_ratio * imsizex);
   const t_int ftsizev = std::floor(oversample_ratio * imsizex);
   const Matrix<t_complex> sample_density =
       estimate_sample_density(u, v, cellx, celly, imsizex, imsizey, oversample_ratio, scale);
   const t_real du = pixel_to_lambda(cellx, imsizex, oversample_ratio) * scale;
   const t_real dv = pixel_to_lambda(celly, imsizey, oversample_ratio) * scale;
   for (t_int i = 0; i < u.size(); ++i) {
     const t_int q = utilities::mod(floor(u(i) * du), ftsizeu);
     const t_int p = utilities::mod(floor(v(i) * dv), ftsizev);
     weights(i) = 1. / sample_density(p, q);
   }
   const t_real max_weight = weights.array().cwiseAbs().maxCoeff();
   weights /= max_weight;
   return weights;
 }
w_support()
t_int purify::widefield::w_support (const t_real w, const t_real du, const t_int min, const t_int max)
estaimte support size of w given u resolution du
Definition at line 7 of file wide_field_utilities.cc.
Referenced by purify::details::init_gridding_matrix_2d(), purify::distribute::kmeans_algo(), main(), TEST_CASE(), and purify::utilities::w_stacking_with_all_to_all().
{
   return std::min<int>(std::max<int>(static_cast<int>(2 * std::floor(std::abs(w / du))), min), max);
 }