PURIFY: purify::factory Namespace Reference
purify::factory Namespace Reference
Enumerations
enum algorithm { algorithm::padmm, algorithm::primal_dual, algorithm::sdmm, algorithm::forward_backward }
enum algo_distribution { algo_distribution::serial, algo_distribution::mpi_serial, algo_distribution::mpi_distributed }
enum ConvergenceType { ConvergenceType::mpi_local, ConvergenceType::mpi_global }
enum distributed_measurement_operator {
distributed_measurement_operator::serial, distributed_measurement_operator::mpi_distribute_image, distributed_measurement_operator::mpi_distribute_grid, distributed_measurement_operator::mpi_distribute_all_to_all,
distributed_measurement_operator::gpu_serial, distributed_measurement_operator::gpu_mpi_distribute_image, distributed_measurement_operator::gpu_mpi_distribute_grid, distributed_measurement_operator::gpu_mpi_distribute_all_to_all
}
determine type of distribute for mpi measurement operator
enum distributed_wavelet_operator { distributed_wavelet_operator::serial, distributed_wavelet_operator::mpi_sara }
Functions
template<class Algorithm , class... ARGS>
std::shared_ptr< Algorithm > algorithm_factory (const factory::algorithm algo, ARGS &&... args)
return chosen algorithm given parameters
template<class Algorithm >
std::enable_if< std::is_same< Algorithm, sopt::algorithm::ImagingProximalADMM< t_complex > >::value, std::shared_ptr< Algorithm > >::type padmm_factory (const algo_distribution dist, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const &measurements, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const &wavelets, const utilities::vis_params &uv_data, const t_real sigma, const t_uint imsizey, const t_uint imsizex, const t_uint sara_size, const t_uint max_iterations=500, const bool real_constraint=true, const bool positive_constraint=true, const bool tight_frame=false, const t_real relative_variation=1e-3, const t_real l1_proximal_tolerance=1e-2, const t_uint maximum_proximal_iterations=50)
return shared pointer to padmm object
template<class Algorithm >
std::enable_if< std::is_same< Algorithm, sopt::algorithm::ImagingForwardBackward< t_complex > >::value, std::shared_ptr< Algorithm > >::type fb_factory (const algo_distribution dist, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const &measurements, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const &wavelets, const utilities::vis_params &uv_data, const t_real sigma, const t_real step_size, const t_real reg_parameter, const t_uint imsizey, const t_uint imsizex, const t_uint sara_size, const t_uint max_iterations=500, const bool real_constraint=true, const bool positive_constraint=true, const bool tight_frame=false, const t_real relative_variation=1e-3, const t_real l1_proximal_tolerance=1e-2, const t_uint maximum_proximal_iterations=50)
return shared pointer to forward backward object
template<class Algorithm >
std::enable_if< std::is_same< Algorithm, sopt::algorithm::ImagingPrimalDual< t_complex > >::value, std::shared_ptr< Algorithm > >::type primaldual_factory (const algo_distribution dist, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const &measurements, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const &wavelets, const utilities::vis_params &uv_data, const t_real sigma, const t_uint imsizey, const t_uint imsizex, const t_uint sara_size, const t_uint max_iterations=500, const bool real_constraint=true, const bool positive_constraint=true, const t_real relative_variation=1e-3)
return shared pointer to primal dual object
template<class T , class... ARGS>
std::shared_ptr< sopt::LinearTransform< T > > all_to_all_measurement_operator_factory (const distributed_measurement_operator distribute, const std::vector< t_int > &image_stacks, const std::vector< t_real > &w_stacks, ARGS &&... args)
distributed measurement operator factory
template<class T , class... ARGS>
std::shared_ptr< sopt::LinearTransform< T > > measurement_operator_factory (const distributed_measurement_operator distribute, ARGS &&... args)
distributed measurement operator factory
template<class T , class Algo >
void add_updater (std::weak_ptr< Algo > const algo_weak, const t_real step_size_scale, const t_real update_tol, const t_uint update_iters, const pfitsio::header_params &update_solution_header, const pfitsio::header_params &update_residual_header, const t_uint imsizey, const t_uint imsizex, const t_uint sara_size, const bool using_mpi, const t_real beam_units=1)
template<class T >
std::shared_ptr< sopt::LinearTransform< T > const > wavelet_operator_factory (const distributed_wavelet_operator distribute, const std::vector< std::tuple< std::string, t_uint >> &wavelets, const t_uint imsizey, const t_uint imsizex, t_uint &sara_size)
construct sara wavelet operator
template<class T >
std::shared_ptr< sopt::LinearTransform< T > const > wavelet_operator_factory (const distributed_wavelet_operator distribute, const std::vector< std::tuple< std::string, t_uint >> &wavelets, const t_uint imsizey, const t_uint imsizex)
Variables
const std::map< std::string, algo_distribution > algo_distribution_string
Enumeration Type Documentation
algo_distribution
enum purify::factory::algo_distribution strong
Enumerator
serial
mpi_serial
mpi_distributed
Definition at line 28 of file algorithm_factory.h.
 { serial, mpi_serial, mpi_distributed };
algorithm
enum purify::factory::algorithm strong
Enumerator
padmm
primal_dual
sdmm
forward_backward
Definition at line 27 of file algorithm_factory.h.
 { padmm, primal_dual, sdmm, forward_backward };
ConvergenceType
enum purify::factory::ConvergenceType strong
Enumerator
mpi_local
mpi_global
Definition at line 12 of file convergence_factory.h.
 { mpi_local, mpi_global };
distributed_measurement_operator
enum purify::factory::distributed_measurement_operator strong
determine type of distribute for mpi measurement operator
Enumerator
serial
mpi_distribute_image
mpi_distribute_grid
mpi_distribute_all_to_all
gpu_serial
gpu_mpi_distribute_image
gpu_mpi_distribute_grid
gpu_mpi_distribute_all_to_all
Definition at line 22 of file measurement_operator_factory.h.
{
   serial,
   mpi_distribute_image,
   mpi_distribute_grid,
   mpi_distribute_all_to_all,
   gpu_serial,
   gpu_mpi_distribute_image,
   gpu_mpi_distribute_grid,
   gpu_mpi_distribute_all_to_all
 };
distributed_wavelet_operator
enum purify::factory::distributed_wavelet_operator strong
Enumerator
serial
mpi_sara
Definition at line 18 of file wavelet_operator_factory.h.
 { serial, mpi_sara };
Function Documentation
add_updater()
template<class T , class Algo > void purify::factory::add_updater (std::weak_ptr< Algo > const algo_weak, const t_real step_size_scale, const t_real update_tol, const t_uint update_iters, const pfitsio::header_params & update_solution_header, const pfitsio::header_params & update_residual_header, const t_uint imsizey, const t_uint imsizex, const t_uint sara_size, const bool using_mpi, const t_real beam_units = 1)
Definition at line 20 of file update_factory.h.
References PURIFY_MEDIUM_LOG, and purify::pfitsio::write2d().
{
   if (update_tol < 0)
     throw std::runtime_error("Step size update tolerance must be greater than zero.");
   if (step_size_scale < 0)
     throw std::runtime_error("Step size update scale must be greater than zero.");
 #ifdef PURIFY_CImg
   auto const canvas =
       std::make_shared<CDisplay>(cimg::make_display(Vector<t_real>::Zero(1024 * 512), 1024, 512));
 #endif
   const std::shared_ptr<pfitsio::header_params> update_header_sol =
       std::make_shared<pfitsio::header_params>(update_solution_header);
   const std::shared_ptr<pfitsio::header_params> update_header_res =
       std::make_shared<pfitsio::header_params>(update_residual_header);
   if (using_mpi) {
 #ifdef PURIFY_MPI
     const auto comm = sopt::mpi::Communicator::World();
     const std::shared_ptr<t_int> iter = std::make_shared<t_int>(0);
     const auto updater = [update_tol, update_iters, imsizex, imsizey, algo_weak, iter,
                           step_size_scale, update_header_sol, update_header_res, sara_size, comm,
                           beam_units](const Vector<T> &x, const Vector<T> &res) -> bool {
       auto algo = algo_weak.lock();
       if (comm.is_root()) PURIFY_MEDIUM_LOG("Step size  {}", algo->gamma());
       if (algo->gamma() > 0) {
         Vector<t_complex> const alpha = algo->Psi().adjoint() * x;
         const t_real new_gamma =
             comm.all_reduce((sara_size > 0) ? alpha.real().cwiseAbs().maxCoeff() : 0., MPI_MAX) *
             step_size_scale;
         if (comm.is_root()) PURIFY_MEDIUM_LOG("Step size  update {}", new_gamma);
         // updating parameter
         algo->gamma(((std::abs(algo->gamma() - new_gamma) > update_tol) and *iter < update_iters)
                         ? new_gamma
                         : algo->gamma());
       }
       Vector<t_complex> const residual = algo->Phi().adjoint() * (res / beam_units).eval();
       PURIFY_MEDIUM_LOG("RMS of residual map in Jy/beam {}",
                         residual.norm() / std::sqrt(residual.size()));
       if (comm.is_root()) {
         update_header_sol->niters = *iter;
         update_header_res->niters = *iter;
         pfitsio::write2d(Image<T>::Map(x.data(), imsizey, imsizex).real(), *update_header_sol,
                          true);
         pfitsio::write2d(Image<T>::Map(residual.data(), imsizey, imsizex).real(),
                          *update_header_res, true);
       }
       *iter = *iter + 1;
       return true;
     };
     auto algo = algo_weak.lock();
     algo->is_converged(updater);
 #else
     throw std::runtime_error(
         "Trying to use algorithm step size update with MPI, but you did not compile with MPI.");
 #endif
   } else {
     const std::shared_ptr<t_int> iter = std::make_shared<t_int>(0);
     const auto updater = [update_tol, update_iters, imsizex, imsizey, algo_weak, iter,
                           step_size_scale, update_header_sol, update_header_res, beam_units
 #ifdef PURIFY_CImg
                           ,
                           canvas
 #endif
     ](const Vector<T> &x, const Vector<T> &res) -> bool {
       auto algo = algo_weak.lock();
       if (algo->gamma() > 0) {
         PURIFY_MEDIUM_LOG("Step size  {}", algo->gamma());
         Vector<T> const alpha = algo->Psi().adjoint() * x;
         const t_real new_gamma = alpha.real().cwiseAbs().maxCoeff() * step_size_scale;
         PURIFY_MEDIUM_LOG("Step size  update {}", new_gamma);
         // updating parameter
         algo->gamma(((std::abs((algo->gamma() - new_gamma) / algo->gamma()) > update_tol) and
                      *iter < update_iters)
                         ? new_gamma
                         : algo->gamma());
       }
       Vector<t_complex> const residual = algo->Phi().adjoint() * (res / beam_units).eval();
       PURIFY_MEDIUM_LOG("RMS of residual map in Jy/beam {}",
                         residual.norm() / std::sqrt(residual.size()));
 #ifdef PURIFY_CImg
       const auto img1 = cimg::make_image(x.real().eval(), imsizey, imsizex)
                             .get_normalize(0, 1)
                             .get_resize(512, 512);
       const auto img2 = cimg::make_image(residual.real().eval(), imsizey, imsizex)
                             .get_normalize(0, 1)
                             .get_resize(512, 512);
       const auto results =
           CImageList<t_real>(img1.get_equalize(256, 0.05, 1.), img2.get_equalize(256, 0.1, 1.));
       canvas->display(results);
       canvas->resize(true);
 #endif
       update_header_sol->niters = *iter;
       update_header_res->niters = *iter;
       pfitsio::write2d(Image<T>::Map(x.data(), imsizey, imsizex).real(), *update_header_sol, true);
       pfitsio::write2d(Image<T>::Map(residual.data(), imsizey, imsizex).real(), *update_header_res,
                        true);
       *iter = *iter + 1;
       return true;
     };
     auto algo = algo_weak.lock();
     algo->is_converged(updater);
   }
 }
algorithm_factory()
template<class Algorithm , class... ARGS> std::shared_ptr< Algorithm > purify::factory::algorithm_factory (const factory::algorithm algo, ARGS &&... args)
return chosen algorithm given parameters
Definition at line 266 of file algorithm_factory.h.
References padmm.
{
   switch (algo) {
   case algorithm::padmm:
     return padmm_factory<Algorithm>(std::forward<ARGS>(args)...);
     break;
     /*
   case algorithm::primal_dual:
     return pd_factory(std::forward<ARGS>(args)...);
     break;
   case algorithm::sdmm:
     return sdmm_factory(std::forward<ARGS>(args)...);
     break;
   case algorithm::forward_backward:
     return fb_factory(std::forward<ARGS>(args)...);
     break;
     */
   default:
     throw std::runtime_error("Algorithm not implimented.");
   }
 }
all_to_all_measurement_operator_factory()
template<class T , class... ARGS> std::shared_ptr<sopt::LinearTransform<T> > purify::factory::all_to_all_measurement_operator_factory (const distributed_measurement_operator distribute, const std::vector< t_int > & image_stacks, const std::vector< t_real > & w_stacks, ARGS &&... args)
distributed measurement operator factory
Definition at line 43 of file measurement_operator_factory.h.
References mpi_distribute_all_to_all, and PURIFY_LOW_LOG.
Referenced by main().
{
   switch (distribute) {
 #ifdef PURIFY_MPI
   case (distributed_measurement_operator::mpi_distribute_all_to_all): {
     PURIFY_LOW_LOG("Using MPI all to all measurement operator.");
     auto const world = sopt::mpi::Communicator::World();
     return measurementoperator::init_degrid_operator_2d_all_to_all<T>(world, image_stacks, w_stacks,
                                                                       std::forward<ARGS>(args)...);
   }
 #endif
   default:
     throw std::runtime_error(
         "Distributed method not found for Measurement Operator. Are you sure you compiled with "
         "MPI?");
   }
 }
fb_factory()
template<class Algorithm > std::enable_if< std::is_same<Algorithm, sopt::algorithm::ImagingForwardBackward<t_complex> >::value, std::shared_ptr<Algorithm> >::type purify::factory::fb_factory (const algo_distribution dist, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const & measurements, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const & wavelets, const utilities::vis_params & uv_data, const t_real sigma, const t_real step_size, const t_real reg_parameter, const t_uint imsizey, const t_uint imsizex, const t_uint sara_size, const t_uint max_iterations = 500, const bool real_constraint = true, const bool positive_constraint = true, const bool tight_frame = false, const t_real relative_variation = 1e-3, const t_real l1_proximal_tolerance = 1e-2, const t_uint maximum_proximal_iterations = 50)
return shared pointer to forward backward object
Definition at line 132 of file algorithm_factory.h.
References mpi_serial, serial, and purify::utilities::vis_params::vis.
Referenced by main().
{
   typedef typename Algorithm::Scalar t_scalar;
   if (sara_size > 1 and tight_frame)
     throw std::runtime_error(
         "l1 proximal not consistent: You say you are using a tight frame, but you have more than "
         "one wavelet basis.");
   auto fb = std::make_shared<Algorithm>(uv_data.vis);
   fb->itermax(max_iterations)
       .gamma(reg_parameter)
       .sigma(sigma)
       .beta(step_size)
       .relative_variation(relative_variation)
       .tight_frame(tight_frame)
       .l1_proximal_tolerance(l1_proximal_tolerance)
       .l1_proximal_nu(1.)
       .l1_proximal_itermax(maximum_proximal_iterations)
       .l1_proximal_positivity_constraint(positive_constraint)
       .l1_proximal_real_constraint(real_constraint)
       .nu(1e0)
       .Psi(*wavelets)
       .Phi(*measurements);
   switch (dist) {
   case (algo_distribution::serial): {
     break;
   }
 #ifdef PURIFY_MPI
   case (algo_distribution::mpi_serial): {
     auto const comm = sopt::mpi::Communicator::World();
     fb->l1_proximal_adjoint_space_comm(comm);
     fb->obj_comm(comm);
     break;
   }
 #endif
   default:
     throw std::runtime_error(
         "Type of distributed Forward Backward algorithm not recognised. You might not have "
         "compiled "
         "with MPI.");
   }
   return fb;
 }
measurement_operator_factory()
template<class T , class... ARGS> std::shared_ptr<sopt::LinearTransform<T> > purify::factory::measurement_operator_factory (const distributed_measurement_operator distribute, ARGS &&... args)
distributed measurement operator factory
Definition at line 63 of file measurement_operator_factory.h.
References gpu_mpi_distribute_grid, gpu_mpi_distribute_image, gpu_serial, purify::measurementoperator::init_degrid_operator_2d(), mpi_distribute_grid, mpi_distribute_image, PURIFY_LOW_LOG, and serial.
Referenced by main(), and TEST_CASE().
{
   switch (distribute) {
   case (distributed_measurement_operator::serial): {
     PURIFY_LOW_LOG("Using serial measurement operator.");
     return measurementoperator::init_degrid_operator_2d<T>(std::forward<ARGS>(args)...);
   }
   case (distributed_measurement_operator::gpu_serial): {
 #ifndef PURIFY_ARRAYFIRE
     throw std::runtime_error("Tried to use GPU operator but you did not build with ArrayFire.");
 #else
     check_complex_for_gpu<T>();
     PURIFY_LOW_LOG("Using serial measurement operator with Arrayfire.");
     af::setDevice(0);
     return gpu::measurementoperator::init_degrid_operator_2d(std::forward<ARGS>(args)...);
 #endif
   }
 #ifdef PURIFY_MPI
   case (distributed_measurement_operator::mpi_distribute_image): {
     auto const world = sopt::mpi::Communicator::World();
     PURIFY_LOW_LOG("Using distributed image MPI measurement operator.");
     return measurementoperator::init_degrid_operator_2d<T>(world, std::forward<ARGS>(args)...);
   }
   case (distributed_measurement_operator::mpi_distribute_grid): {
     auto const world = sopt::mpi::Communicator::World();
     PURIFY_LOW_LOG("Using distributed grid MPI measurement operator.");
     return measurementoperator::init_degrid_operator_2d_mpi<T>(world, std::forward<ARGS>(args)...);
   }
   case (distributed_measurement_operator::gpu_mpi_distribute_image): {
 #ifndef PURIFY_ARRAYFIRE
     throw std::runtime_error("Tried to use GPU operator but you did not build with ArrayFire.");
 #else
     check_complex_for_gpu<T>();
     auto const world = sopt::mpi::Communicator::World();
     PURIFY_LOW_LOG("Using distributed image MPI + Arrayfire measurement operator.");
     af::setDevice(0);
     return gpu::measurementoperator::init_degrid_operator_2d(world, std::forward<ARGS>(args)...);
 #endif
   }
   case (distributed_measurement_operator::gpu_mpi_distribute_grid): {
 #ifndef PURIFY_ARRAYFIRE
     throw std::runtime_error("Tried to use GPU operator but you did not build with ArrayFire.");
 #else
     check_complex_for_gpu<T>();
     auto const world = sopt::mpi::Communicator::World();
     PURIFY_LOW_LOG("Using distributed grid MPI + Arrayfire measurement operator.");
     af::setDevice(0);
     return gpu::measurementoperator::init_degrid_operator_2d_mpi(world,
                                                                  std::forward<ARGS>(args)...);
 #endif
   }
 #endif
   default:
     throw std::runtime_error(
         "Distributed method not found for Measurement Operator. Are you sure you compiled with "
         "MPI?");
   }
 }
padmm_factory()
template<class Algorithm > std::enable_if< std::is_same<Algorithm, sopt::algorithm::ImagingProximalADMM<t_complex> >::value, std::shared_ptr<Algorithm> >::type purify::factory::padmm_factory (const algo_distribution dist, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const & measurements, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const & wavelets, const utilities::vis_params & uv_data, const t_real sigma, const t_uint imsizey, const t_uint imsizex, const t_uint sara_size, const t_uint max_iterations = 500, const bool real_constraint = true, const bool positive_constraint = true, const bool tight_frame = false, const t_real relative_variation = 1e-3, const t_real l1_proximal_tolerance = 1e-2, const t_uint maximum_proximal_iterations = 50)
return shared pointer to padmm object
Definition at line 42 of file algorithm_factory.h.
References purify::utilities::calculate_l2_radius(), epsilon(), mpi_distributed, mpi_global, mpi_local, mpi_serial, padmm, serial, purify::utilities::step_size(), and purify::utilities::vis_params::vis.
Referenced by main().
{
   typedef typename Algorithm::Scalar t_scalar;
   if (sara_size > 1 and tight_frame)
     throw std::runtime_error(
         "l1 proximal not consistent: You say you are using a tight frame, but you have more than "
         "one wavelet basis.");
   auto epsilon = utilities::calculate_l2_radius(uv_data.vis.size(), sigma);
   auto padmm = std::make_shared<Algorithm>(uv_data.vis);
   padmm->itermax(max_iterations)
       .relative_variation(relative_variation)
       .tight_frame(tight_frame)
       .l1_proximal_tolerance(l1_proximal_tolerance)
       .l1_proximal_nu(1.)
       .l1_proximal_itermax(maximum_proximal_iterations)
       .l1_proximal_positivity_constraint(positive_constraint)
       .l1_proximal_real_constraint(real_constraint)
       .lagrange_update_scale(0.9)
       .nu(1e0)
       .Psi(*wavelets)
       .Phi(*measurements);
 #ifdef PURIFY_MPI
   ConvergenceType obj_conv = ConvergenceType::mpi_global;
   ConvergenceType rel_conv = ConvergenceType::mpi_global;
 #endif
   switch (dist) {
   case (algo_distribution::serial): {
     padmm
         ->gamma((wavelets->adjoint() * (measurements->adjoint() * uv_data.vis).eval())
                     .cwiseAbs()
                     .maxCoeff() *
                 1e-3)
         .l2ball_proximal_epsilon(epsilon)
         .residual_tolerance(epsilon);
     return padmm;
   }
 #ifdef PURIFY_MPI
   case (algo_distribution::mpi_serial): {
     obj_conv = ConvergenceType::mpi_global;
     rel_conv = ConvergenceType::mpi_global;
     auto const comm = sopt::mpi::Communicator::World();
     epsilon =
         utilities::calculate_l2_radius(comm.all_sum_all(uv_data.vis.size()), comm.broadcast(sigma));
     // communicator ensuring l2 norm in l2ball proximal is global
     padmm->l2ball_proximal_communicator(comm);
     break;
   }
   case (algo_distribution::mpi_distributed): {
     obj_conv = ConvergenceType::mpi_local;
     rel_conv = ConvergenceType::mpi_local;
     break;
   }
 #endif
   default:
     throw std::runtime_error(
         "Type of distributed proximal ADMM algorithm not recognised. You might not have compiled "
         "with MPI.");
   }
 #ifdef PURIFY_MPI
   auto const comm = sopt::mpi::Communicator::World();
   std::weak_ptr<Algorithm> const padmm_weak(padmm);
   // set epsilon
   padmm->residual_tolerance(epsilon).l2ball_proximal_epsilon(epsilon);
   // set gamma
   padmm->gamma(comm.all_reduce(
       utilities::step_size(uv_data.vis, measurements, wavelets, sara_size) * 1e-3, MPI_MAX));
   // communicator ensuring l1 norm in l1 proximal is global
   padmm->l1_proximal_adjoint_space_comm(comm);
   padmm->residual_convergence(
       purify::factory::l2_convergence_factory<typename Algorithm::Scalar>(rel_conv, padmm_weak));
   padmm->objective_convergence(
       purify::factory::l1_convergence_factory<typename Algorithm::Scalar>(obj_conv, padmm_weak));
 #endif
   return padmm;
 }
primaldual_factory()
template<class Algorithm > std::enable_if< std::is_same<Algorithm, sopt::algorithm::ImagingPrimalDual<t_complex> >::value, std::shared_ptr<Algorithm> >::type purify::factory::primaldual_factory (const algo_distribution dist, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const & measurements, std::shared_ptr< sopt::LinearTransform< Vector< typename Algorithm::Scalar >> const > const & wavelets, const utilities::vis_params & uv_data, const t_real sigma, const t_uint imsizey, const t_uint imsizex, const t_uint sara_size, const t_uint max_iterations = 500, const bool real_constraint = true, const bool positive_constraint = true, const t_real relative_variation = 1e-3)
return shared pointer to primal dual object
Definition at line 190 of file algorithm_factory.h.
References purify::utilities::calculate_l2_radius(), epsilon(), mpi_distributed, mpi_global, mpi_local, mpi_serial, serial, purify::utilities::step_size(), and purify::utilities::vis_params::vis.
Referenced by main().
{
   typedef typename Algorithm::Scalar t_scalar;
   auto epsilon = utilities::calculate_l2_radius(uv_data.vis.size(), sigma);
   auto primaldual = std::make_shared<Algorithm>(uv_data.vis);
   primaldual->itermax(max_iterations)
       .relative_variation(relative_variation)
       .real_constraint(real_constraint)
       .positivity_constraint(positive_constraint)
       .Psi(*wavelets)
       .Phi(*measurements);
 #ifdef PURIFY_MPI
   ConvergenceType obj_conv = ConvergenceType::mpi_global;
   ConvergenceType rel_conv = ConvergenceType::mpi_global;
 #endif
   switch (dist) {
   case (algo_distribution::serial): {
     primaldual
         ->gamma((wavelets->adjoint() * (measurements->adjoint() * uv_data.vis).eval())
                     .cwiseAbs()
                     .maxCoeff() *
                 1e-3)
         .l2ball_proximal_epsilon(epsilon)
         .residual_tolerance(epsilon);
     return primaldual;
   }
 #ifdef PURIFY_MPI
   case (algo_distribution::mpi_serial): {
     obj_conv = ConvergenceType::mpi_global;
     rel_conv = ConvergenceType::mpi_global;
     auto const comm = sopt::mpi::Communicator::World();
     epsilon =
         utilities::calculate_l2_radius(comm.all_sum_all(uv_data.vis.size()), comm.broadcast(sigma));
     // communicator ensuring l2 norm in l2ball proximal is global
     primaldual->l2ball_proximal_communicator(comm);
     break;
   }
   case (algo_distribution::mpi_distributed): {
     obj_conv = ConvergenceType::mpi_local;
     rel_conv = ConvergenceType::mpi_local;
     break;
   }
 #endif
   default:
     throw std::runtime_error(
         "Type of distributed primal dual algorithm not recognised. You might not have compiled "
         "with MPI.");
   }
 #ifdef PURIFY_MPI
   auto const comm = sopt::mpi::Communicator::World();
   std::weak_ptr<Algorithm> const primaldual_weak(primaldual);
   // set epsilon
   primaldual->residual_tolerance(epsilon).l2ball_proximal_epsilon(epsilon);
   // set gamma
   primaldual->gamma(comm.all_reduce(
       utilities::step_size(uv_data.vis, measurements, wavelets, sara_size) * 1e-3, MPI_MAX));
   // communicator ensuring l1 norm in l1 proximal is global
   primaldual->residual_convergence(
       purify::factory::l2_convergence_factory<typename Algorithm::Scalar>(rel_conv,
                                                                           primaldual_weak));
   primaldual->objective_convergence(
       purify::factory::l1_convergence_factory<typename Algorithm::Scalar>(obj_conv,
                                                                           primaldual_weak));
 #endif
   return primaldual;
 }
wavelet_operator_factory() [1/2]
template<class T > std::shared_ptr<sopt::LinearTransform<T> const> purify::factory::wavelet_operator_factory (const distributed_wavelet_operator distribute, const std::vector< std::tuple< std::string, t_uint >> & wavelets, const t_uint imsizey, const t_uint imsizex, t_uint & sara_size)
construct sara wavelet operator
Definition at line 21 of file wavelet_operator_factory.h.
References sopt::wavelets::distribute_sara(), mpi_sara, PURIFY_LOW_LOG, and serial.
{
   const auto sara = sopt::wavelets::SARA(wavelets.begin(), wavelets.end());
   switch (distribute) {
   case (distributed_wavelet_operator::serial): {
     PURIFY_LOW_LOG("Using serial wavelet operator.");
     sara_size = sara.size();
     return std::make_shared<sopt::LinearTransform<T>>(
         sopt::linear_transform<typename T::Scalar>(sara, imsizey, imsizex));
   }
 #ifdef PURIFY_MPI
   case (distributed_wavelet_operator::mpi_sara): {
     auto const comm = sopt::mpi::Communicator::World();
     PURIFY_LOW_LOG("Using distributed image MPI wavelet operator.");
     const auto dsara = sopt::wavelets::distribute_sara(sara, comm);
     sara_size = dsara.size();
     return std::make_shared<sopt::LinearTransform<T>>(
         sopt::linear_transform<typename T::Scalar>(dsara, imsizey, imsizex, comm));
   }
 #endif
   default:
     throw std::runtime_error(
         "Distributed method not found for Wavelet Operator. Are you sure you compiled with MPI?");
   }
 }
wavelet_operator_factory() [2/2]
template<class T > std::shared_ptr<sopt::LinearTransform<T> const> purify::factory::wavelet_operator_factory (const distributed_wavelet_operator distribute, const std::vector< std::tuple< std::string, t_uint >> & wavelets, const t_uint imsizey, const t_uint imsizex)
Definition at line 49 of file wavelet_operator_factory.h.
{
   t_uint size = 0;
   return wavelet_operator_factory<T>(distribute, wavelets, imsizey, imsizex, size);
 }
Variable Documentation
algo_distribution_string
const std::map<std::string, algo_distribution> purify::factory::algo_distribution_string
Initial value:
= {
    {"none", algo_distribution::serial},
    {"serial-equivalent", algo_distribution::mpi_serial},
    {"fully-distributed", algo_distribution::mpi_distributed}}
Definition at line 29 of file algorithm_factory.h.
Referenced by purify::YamlParser::parseAndSetAlgorithmOptions().