PURIFY: purify::read_measurements Namespace Reference
purify::read_measurements Namespace Reference
Enumerations
enum format { format::vis, format::uvfits, format::ms }
Functions
utilities::vis_params read_measurements (const std::string &name, const bool w_term=false, const stokes pol=stokes::I, const utilities::vis_units units=utilities::vis_units::lambda)
read in signle measurement file
utilities::vis_params read_measurements (const std::vector< std::string > &names, const bool w_term=false, const stokes pol=stokes::I, const utilities::vis_units units=utilities::vis_units::lambda)
read in measurements from a vector of file names
bool file_exists (const std::string &path)
check that file path exists
bool dir_exists (const std::string &path)
check that directory path exists
Enumeration Type Documentation
format
enum purify::read_measurements::format strong
Enumerator
vis
uvfits
ms
Definition at line 15 of file read_measurements.h.
 { vis, uvfits, ms };
Function Documentation
dir_exists()
bool purify::read_measurements::dir_exists (const std::string & path)
check that directory path exists
Definition at line 127 of file read_measurements.cc.
Referenced by purify::mkdir_recursive(), read_measurements(), and TEST_CASE().
{
   struct stat buf;
   return (stat(path.c_str(), &buf) == 0 && S_ISDIR(buf.st_mode));
 }
file_exists()
bool purify::read_measurements::file_exists (const std::string & path)
check that file path exists
Definition at line 122 of file read_measurements.cc.
Referenced by read_measurements().
{
   struct stat buf;
   return (stat(path.c_str(), &buf) == 0);
 }
read_measurements() [1/2]
utilities::vis_params purify::read_measurements::read_measurements (const std::string & name, const bool w_term, const stokes pol, const utilities::vis_units units)
read in signle measurement file
Definition at line 17 of file read_measurements.cc.
Referenced by main(), read_measurements(), and TEST_CASE().
{
   return read_measurements(std::vector<std::string>{name}, w_term, pol, units);
 }
read_measurements() [2/2]
utilities::vis_params purify::read_measurements::read_measurements (const std::vector< std::string > & names, const bool w_term, const stokes pol, const utilities::vis_units units)
read in measurements from a vector of file names
Definition at line 21 of file read_measurements.cc.
References dir_exists(), purify::distribute::distribute_measurements(), file_exists(), purify::I, ms, PURIFY_HIGH_LOG, read_measurements(), purify::casa::read_measurementset(), purify::pfitsio::read_uvfits(), purify::utilities::read_visibility(), purify::utilities::regroup_and_scatter(), purify::utilities::scatter_visibilities(), uvfits, and vis.
{
   std::vector<std::string> found_files;
   format format_type = format::uvfits;
   for (t_int i = 0; i < names.size(); i++) {
     const boost::filesystem::path file_path(names.at(i));
     if (not file_exists(file_path.native())) {
       PURIFY_HIGH_LOG("Missing file will be removed from list: {}", names.at(i));
     } else {
       found_files.emplace_back(names.at(i));
       format format_check = format::uvfits;
       // checking if reading measurement set or .vis file
       std::size_t found = names.at(i).find_last_of(".");
       std::string format = "." + names.at(i).substr(found + 1);
       std::transform(format.begin(), format.end(), format.begin(), ::tolower);
       if (format == ".ms") {
         format_check = format::ms;
         if (not dir_exists(file_path.native()))
           throw std::runtime_error(names.at(i) +
                                    " is not a directory, as expected for a measurement set.");
       } else if (format == ".vis") {
         format_check = format::vis;
         if (not file_exists(file_path.native()))
           throw std::runtime_error(names.at(i) + " is not a regular file.");
       } else if (format == ".uvfits") {
         format_check = format::uvfits;
         if (not file_exists(file_path.native()))
           throw std::runtime_error(names.at(i) + " is not a regular file.");
       } else
         throw std::runtime_error("File extention for " + names.at(i) +
                                  " not recognised. Must be .vis, .uvfits, or .ms.");
       if (i == 0) format_type = format_check;
       if (i > 0 and (format_check != format_type))
         throw std::runtime_error("File extention is not the same for " + names.at(i) + " " +
                                  names.at(i - 1));
     }
   }
   if (found_files.size() == 0) throw std::runtime_error("No files found, all files are missing!");
   switch (format_type) {
   case (format::vis): {
     if (pol != stokes::I)
       throw std::runtime_error(
           ".vis files are ascii, so it is assumed that it is Stokes I. But, you are trying to "
           "choose a different type!");
     auto measurements = utilities::read_visibility(found_files, w_term);
     measurements.units = units;
     return measurements;
     break;
   }
   case (format::uvfits): {
     return pfitsio::read_uvfits(found_files, true, pol);
     break;
   }
   case (format::ms): {
 #ifdef PURIFY_CASACORE
     return casa::read_measurementset(found_files, pol);
     break;
 #else
     throw std::runtime_error(
         "You want to read a measurement set, but you did not compile with casacore.");
 #endif
   }
   default:
     throw std::runtime_error("Format not recongised.");
   }
 }