PURIFY: b_utilities Namespace Reference
b_utilities Namespace Reference
Functions
void Arguments (benchmark::internal::Benchmark *b)
double duration (std::chrono::high_resolution_clock::time_point start, std::chrono::high_resolution_clock::time_point end)
bool updateImage (t_uint newSize, Image< t_complex > &image, t_uint &sizex, t_uint &sizey)
bool updateEmptyImage (t_uint newSize, Vector< t_complex > &image, t_uint &sizex, t_uint &sizey)
bool updateMeasurements (t_uint newSize, utilities::vis_params &data)
bool updateMeasurements (t_uint newSize, utilities::vis_params &data, t_real &epsilon, bool newImage, Image< t_complex > &image)
std::tuple< utilities::vis_params, t_real > dirty_measurements (Image< t_complex > const &ground_truth_image, t_uint number_of_vis, t_real snr, const t_real &cellsize)
utilities::vis_params random_measurements (t_int size)
Function Documentation
Arguments()
void b_utilities::Arguments (benchmark::internal::Benchmark * b)
Definition at line 16 of file utilities.cc.
{
   int im_size_max = 4096;      // 4096
   int uv_size_max = 10000000;  // 1M, 10M, 100M
   int kernel_max = 16;         // 16
   for (int i = 128; i <= im_size_max; i *= 2)
     for (int j = 1000000; j <= uv_size_max; j *= 10)
       for (int k = 2; k <= kernel_max; k *= 2)
         if (k * k < i) b->Args({i, j, k});
 }
dirty_measurements()
std::tuple< utilities::vis_params, t_real > b_utilities::dirty_measurements (Image< t_complex > const & ground_truth_image, t_uint number_of_vis, t_real snr, const t_real & cellsize)
Definition at line 79 of file utilities.cc.
References purify::utilities::add_noise(), purify::kernels::kb, random_measurements(), sigma(), and purify::utilities::SNR_to_standard_deviation().
Referenced by random_measurements(), and updateMeasurements().
{
   auto uv_data = random_measurements(number_of_vis);
   // creating operator to generate measurements
   auto measurement_op = measurementoperator::init_degrid_operator_2d<Vector<t_complex>>(
       uv_data, ground_truth_image.rows(), ground_truth_image.cols(), cellsize, cellsize, 2,
       kernels::kernel::kb, 8, 8, false);
   // Generates measurements from image
   uv_data.vis = (*measurement_op) *
                 Image<t_complex>::Map(ground_truth_image.data(), ground_truth_image.size(), 1);
   // working out value of signal given SNR
   auto const sigma = utilities::SNR_to_standard_deviation(uv_data.vis, snr);
   // adding noise to visibilities
   uv_data.vis = utilities::add_noise(uv_data.vis, 0., sigma);
   return std::make_tuple(uv_data, sigma);
 }
duration()
double b_utilities::duration (std::chrono::high_resolution_clock::time_point start, std::chrono::high_resolution_clock::time_point end)
Definition at line 26 of file utilities.cc.
Referenced by BENCHMARK_DEFINE_F(), degrid_operator_ctor(), random_measurements(), and wavelet_operator_constructor().
{
   auto elapsed_seconds = std::chrono::duration_cast<std::chrono::duration<double>>(end - start);
   return elapsed_seconds.count();
 }
random_measurements()
utilities::vis_params b_utilities::random_measurements (t_int size)
Definition at line 98 of file utilities.cc.
References purify::utilities::calculate_l2_radius(), dirty_measurements(), purify::distribute::distribute_measurements(), duration(), epsilon(), purify::constant::pi, purify::distribute::radial, purify::utilities::radians, purify::utilities::random_sample_density(), purify::utilities::read_visibility(), purify::utilities::regroup_and_scatter(), purify::utilities::scatter_visibilities(), sigma(), purify::utilities::vis_params::units, updateMeasurements(), purify::utilities::vis_params::vis, purify::notinstalled::visibility_filename(), and purify::utilities::write_visibility().
Referenced by degrid_operator_ctor(), dirty_measurements(), GridOperatorFixture::SetUp(), and updateMeasurements().
{
   std::stringstream filename;
   filename << "random_" << size << ".vis";
   std::string const vis_file = visibility_filename(filename.str());
   std::ifstream vis_file_str(vis_file);
   utilities::vis_params uv_data;
   if (vis_file_str.good()) {
     uv_data = utilities::read_visibility(vis_file, false);
     uv_data.units = utilities::vis_units::radians;
   } else {
     t_real const sigma_m = constant::pi / 3;
     const t_real max_w = 100.;  // lambda
     uv_data = utilities::random_sample_density(size, 0, sigma_m, max_w);
     uv_data.units = utilities::vis_units::radians;
     utilities::write_visibility(uv_data, vis_file);
   }
   return uv_data;
 }
updateEmptyImage()
bool b_utilities::updateEmptyImage (t_uint newSize, Vector< t_complex > & image, t_uint & sizex, t_uint & sizey)
Definition at line 46 of file utilities.cc.
Referenced by DegridOperatorAdjointFixture::updateImage(), and DegridOperatorAdjointFixturePar::updateImage().
{
   if (sizex == newSize) {
     return false;
   }
   image.resize(newSize * newSize);
   sizex = newSize;
   sizey = newSize;
   return true;
 }
updateImage()
bool b_utilities::updateImage (t_uint newSize, Image< t_complex > & image, t_uint & sizex, t_uint & sizey)
Definition at line 32 of file utilities.cc.
References purify::notinstalled::image_filename(), and purify::pfitsio::read2d().
Referenced by PadmmFixture::SetUp(), PadmmFixtureMPI::SetUp(), DegridOperatorFixture::SetUp(), DegridOperatorFixturePar::SetUp(), DegridOperatorFixture::TearDown(), DegridOperatorFixturePar::TearDown(), DegridOperatorDirectFixture::updateImage(), and DegridOperatorDirectFixturePar::updateImage().
{
   if (sizex == newSize) {
     return false;
   }
   const std::string &name = "M31_" + std::to_string(newSize);
   std::string const fitsfile = image_filename(name + ".fits");
   image = pfitsio::read2d(fitsfile);
   sizex = image.cols();
   sizey = image.rows();
   t_real const max = image.array().abs().maxCoeff();
   image = image * 1. / max;
   return true;
 }
updateMeasurements() [1/2]
bool b_utilities::updateMeasurements (t_uint newSize, utilities::vis_params & data)
Definition at line 56 of file utilities.cc.
References random_measurements(), and purify::utilities::vis_params::vis.
Referenced by PadmmFixture::SetUp(), DegridOperatorCtorFixturePar::SetUp(), PadmmFixtureMPI::SetUp(), DegridOperatorFixture::SetUp(), and DegridOperatorFixturePar::SetUp().
{
   if (data.vis.size() == newSize) {
     return false;
   }
   data = b_utilities::random_measurements(newSize);
   return true;
 }
updateMeasurements() [2/2]
bool b_utilities::updateMeasurements (t_uint newSize, utilities::vis_params & data, t_real & epsilon, bool newImage, Image< t_complex > & image)
Definition at line 64 of file utilities.cc.
References purify::utilities::calculate_l2_radius(), dirty_measurements(), and purify::utilities::vis_params::vis.
Referenced by random_measurements().
{
   if (data.vis.size() == newSize && !newImage) {
     return false;
   }
   const t_real FoV = 1;  // deg
   const t_real cellsize = FoV / image.size() * 60. * 60.;
   std::tuple<utilities::vis_params, t_real> temp =
       b_utilities::dirty_measurements(image, newSize, 30., cellsize);
   data = std::get<0>(temp);
   epsilon = utilities::calculate_l2_radius(data.vis.size(), std::get<1>(temp));
   return true;
 }