PURIFY: /mydata/cpp/benchmarks/padmm.cc File Reference
padmm.cc File Reference
#include "purify/config.h"
#include "purify/types.h"
#include <array>
#include <benchmark/benchmark.h>
#include "benchmarks/utilities.h"
#include "purify/operators.h"
#include "purify/utilities.h"
#include <sopt/imaging_padmm.h>
#include <sopt/relative_variation.h>
#include <sopt/utilities.h>
#include <sopt/wavelets.h>
#include <sopt/wavelets/sara.h>
Classes
class PadmmFixture
Functions
BENCHMARK_DEFINE_F (PadmmFixture, Apply)(benchmark
Args ({1024, 1000000, 4}) -> Args(
UseManualTime () -> Repetitions(10) ->Unit(benchmark::kMillisecond)
BENCHMARK_MAIN ()
Function Documentation
Args()
Args ({1024, 1000000, 4}) -> Args(
Definition at line 96 of file padmm.cc.
References BENCHMARK_MAIN(), and UseManualTime().
            {1024, 1000000, 4})
     ->Args({1024, 10000000, 4})
BENCHMARK_DEFINE_F()
BENCHMARK_DEFINE_F (PadmmFixture , Apply)
Definition at line 81 of file padmm.cc.
References b_utilities::duration().
{
   // Benchmark the application of the algorithm
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     (*m_padmm)();
     auto end = std::chrono::high_resolution_clock::now();
     state.SetIterationTime(b_utilities::duration(start, end));
   }
   //  state.SetBytesProcessed(int64_t(state.iterations()) * (state.range(1) + m_imsizey * m_imsizex)
   //  * sizeof(t_complex));
 }
BENCHMARK_MAIN()
BENCHMARK_MAIN ()
Referenced by Args().
UseManualTime()
UseManualTime () -> Repetitions(10) ->Unit(benchmark::kMillisecond)
Referenced by Args().