PURIFY: /home/runner/work/purify/purify/cpp/benchmarks/padmm_mpi.cc File Reference
padmm_mpi.cc File Reference
#include "purify/types.h"
#include <array>
#include <random>
#include "benchmarks/utilities.h"
#include "purify/convergence_factory.h"
#include "purify/directories.h"
#include "purify/distribute.h"
#include "purify/mpi_utilities.h"
#include "purify/operators.h"
#include "purify/pfitsio.h"
#include "purify/utilities.h"
#include <sopt/imaging_padmm.h>
#include <sopt/mpi/communicator.h>
#include <sopt/mpi/session.h>
#include <sopt/relative_variation.h>
#include <sopt/utilities.h>
#include <sopt/wavelets.h>
#include <sopt/wavelets/sara.h>
Classes
class PadmmFixtureMPI
Functions
BENCHMARK_DEFINE_F (PadmmFixtureMPI, ApplyAlgo1)(benchmark
BENCHMARK_DEFINE_F (PadmmFixtureMPI, ApplyAlgo3)(benchmark
Args ({1024, static_cast< t_int >(1e6), 4, 10, 1}) -> Args(
Args ({1024, static_cast< t_int >(1e7), 4, 10, 1}) -> Args(
Args ({1024, static_cast< t_int >(1e8), 4, 10, 1}) -> Args(
UseManualTime () -> Repetitions(3) ->Unit(benchmark::kMillisecond)
Args ({1024, static_cast< t_int >(1e6), 4, 10, 3}) -> Args(
Args ({1024, static_cast< t_int >(1e7), 4, 10, 3}) -> Args(
Args ({1024, static_cast< t_int >(1e8), 4, 10, 3}) -> Args(
Function Documentation
Args() [1/6]
Args ({1024, static_cast< t_int >(1e6), 4, 10, 1}) -> Args(
Definition at line 172 of file padmm_mpi.cc.
            {1024, static_cast<t_int>(1e6), 4, 10, 1})
     ->Args({1024, static_cast<t_int>(5e6), 4, 10, 1})
Args() [2/6]
Args ({1024, static_cast< t_int >(1e6), 4, 10, 3}) -> Args(
Definition at line 185 of file padmm_mpi.cc.
            {1024, static_cast<t_int>(1e6), 4, 10, 3})
     ->Args({1024, static_cast<t_int>(5e6), 4, 10, 3})
Args() [3/6]
Args ({1024, static_cast< t_int >(1e7), 4, 10, 1}) -> Args(
Definition at line 174 of file padmm_mpi.cc.
            {1024, static_cast<t_int>(1e7), 4, 10, 1})
     ->Args({1024, static_cast<t_int>(5e7), 4, 10, 1})
Args() [4/6]
Args ({1024, static_cast< t_int >(1e7), 4, 10, 3}) -> Args(
Definition at line 187 of file padmm_mpi.cc.
            {1024, static_cast<t_int>(1e7), 4, 10, 3})
     ->Args({1024, static_cast<t_int>(5e7), 4, 10, 3})
Args() [5/6]
Args ({1024, static_cast< t_int >(1e8), 4, 10, 1}) -> Args(
Definition at line 176 of file padmm_mpi.cc.
            {1024, static_cast<t_int>(1e8), 4, 10, 1})
     ->Args({1024, static_cast<t_int>(5e8), 4, 10, 1})
Args() [6/6]
Args ({1024, static_cast< t_int >(1e8), 4, 10, 3}) -> Args(
Definition at line 189 of file padmm_mpi.cc.
            {1024, static_cast<t_int>(1e8), 4, 10, 3})
     ->Args({1024, static_cast<t_int>(5e8), 4, 10, 3})
BENCHMARK_DEFINE_F() [1/2]
BENCHMARK_DEFINE_F (PadmmFixtureMPI , ApplyAlgo1)
Definition at line 76 of file padmm_mpi.cc.
{
   // Create the algorithm - somehow doesn't work if done in the fixture...
   sopt::wavelets::SARA saraDistr = sopt::wavelets::distribute_sara(m_sara, m_world);
   auto const Psi =
       sopt::linear_transform<t_complex>(saraDistr, m_image.rows(), m_image.cols(), m_world);
   t_real gamma =
       utilities::step_size(m_uv_data.vis, m_measurements1,
                            std::make_shared<sopt::LinearTransform<Vector<t_complex>> const>(Psi),
                            saraDistr.size()) *
       1e-3;
   gamma = m_world.all_reduce(gamma, MPI_MAX);
   std::shared_ptr<sopt::algorithm::ImagingProximalADMM<t_complex>> padmm =
       std::make_shared<sopt::algorithm::ImagingProximalADMM<t_complex>>(m_uv_data.vis);
   padmm->itermax(state.range(3) + 1)
       .gamma(gamma)
       .relative_variation(1e-3)
       .l2ball_proximal_epsilon(m_epsilon)
       // communicator ensuring l1 norm in l1 proximal is global
       .l1_proximal_adjoint_space_comm(m_world)
       .tight_frame(false)
       .l1_proximal_tolerance(1e-2)
       .l1_proximal_nu(1)
       .l1_proximal_itermax(2)
       .l1_proximal_positivity_constraint(true)
       .l1_proximal_real_constraint(true)
       .residual_tolerance(m_epsilon)
       .lagrange_update_scale(0.9)
       .nu(1e0)
       .Psi(Psi)
       .Phi(*m_measurements1);
   std::weak_ptr<decltype(padmm)::element_type> const padmm_weak(padmm);
   padmm->residual_convergence(
       factory::l2_convergence_factory<t_complex>(factory::ConvergenceType::mpi_local, padmm_weak));
   padmm->objective_convergence(
       factory::l1_convergence_factory<t_complex>(factory::ConvergenceType::mpi_local, padmm_weak));
   // Benchmark the application of the algorithm
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     auto result = (*padmm)();
     auto end = std::chrono::high_resolution_clock::now();
     // std::cout << "Converged? " << result.good << " , niters = " << result.niters << std::endl;
     state.SetIterationTime(b_utilities::duration(start, end, m_world));
   }
 }
References b_utilities::duration(), purify::factory::mpi_local, padmm(), and purify::utilities::step_size().
BENCHMARK_DEFINE_F() [2/2]
BENCHMARK_DEFINE_F (PadmmFixtureMPI , ApplyAlgo3)
Definition at line 123 of file padmm_mpi.cc.
{
   // Create the algorithm - somehow doesn't work if done in the fixture...
   sopt::wavelets::SARA saraDistr = sopt::wavelets::distribute_sara(m_sara, m_world);
   auto const Psi =
       sopt::linear_transform<t_complex>(saraDistr, m_image.rows(), m_image.cols(), m_world);
   t_real gamma =
       utilities::step_size(m_uv_data.vis, m_measurements3,
                            std::make_shared<sopt::LinearTransform<Vector<t_complex>> const>(Psi),
                            saraDistr.size()) *
       1e-3;
   gamma = m_world.all_reduce(gamma, MPI_MAX);
   std::shared_ptr<sopt::algorithm::ImagingProximalADMM<t_complex>> padmm =
       std::make_shared<sopt::algorithm::ImagingProximalADMM<t_complex>>(m_uv_data.vis);
   padmm->itermax(state.range(3) + 1)
       .gamma(gamma)
       .relative_variation(1e-3)
       .l2ball_proximal_epsilon(m_epsilon)
       // communicator ensuring l1 norm in l1 proximal is global
       .l1_proximal_adjoint_space_comm(m_world)
       .tight_frame(false)
       .l1_proximal_tolerance(1e-2)
       .l1_proximal_nu(1)
       .l1_proximal_itermax(2)
       .l1_proximal_positivity_constraint(true)
       .l1_proximal_real_constraint(true)
       .residual_tolerance(m_epsilon)
       .lagrange_update_scale(0.9)
       .nu(1e0)
       .Psi(Psi)
       .Phi(*m_measurements3);
   std::weak_ptr<decltype(padmm)::element_type> const padmm_weak(padmm);
   padmm->residual_convergence(
       factory::l2_convergence_factory<t_complex>(factory::ConvergenceType::mpi_local, padmm_weak));
   padmm->objective_convergence(
       factory::l1_convergence_factory<t_complex>(factory::ConvergenceType::mpi_local, padmm_weak));
   // Benchmark the application of the algorithm
   while (state.KeepRunning()) {
     auto start = std::chrono::high_resolution_clock::now();
     auto result = (*padmm)();
     auto end = std::chrono::high_resolution_clock::now();
     // std::cout << "Converged? " << result.good << " , niters = " << result.niters << std::endl;
     state.SetIterationTime(b_utilities::duration(start, end, m_world));
   }
 }
References b_utilities::duration(), purify::factory::mpi_local, padmm(), and purify::utilities::step_size().
UseManualTime()
UseManualTime () -> Repetitions(3) ->Unit(benchmark::kMillisecond)