PURIFY: /mydata/cpp/tests/kernels.cc File Reference
kernels.cc File Reference
#include <iomanip>
#include "catch.hpp"
#include "purify/kernels.h"
#include "purify/pfitsio.h"
#include "purify/utilities.h"
#include "purify/test_data.h"
Namespaces
kernels_test
Functions
TEST_CASE ("kernels")
TEST_CASE ("kernel_correction")
Variables
const std::string kernels_test::test_dir = "expected/kernels/"
const std::vector< t_real > kernels_test::kernel_x_values
const std::vector< t_real > kernels_test::kernel_pswf_values
const std::vector< t_real > kernels_test::kernel_kb_values
const std::vector< t_real > kernels_test::kernel_gauss_values
const std::vector< t_real > kernels_test::correction_x_values
const std::vector< t_real > kernels_test::correction_pswf_values
const std::vector< t_real > kernels_test::correction_kb_values
const std::vector< t_real > kernels_test::correction_gauss_values
Function Documentation
TEST_CASE() [1/2]
TEST_CASE ("kernels")
Definition at line 35 of file kernels.cc.
References CHECK, purify::kernels::gaussian(), purify::kernels::kaiser_bessel(), kernels_test::kernel_gauss_values, kernels_test::kernel_kb_values, kernels_test::kernel_pswf_values, kernels_test::kernel_x_values, and purify::kernels::pswf().
                      {
   const t_uint number_of_samples = kernels_test::kernel_x_values.size();
   for (t_uint i = 0; i < number_of_samples; ++i) {
     // Test that pswf is the same as matlab calculations
     const t_real pswf_difference = std::abs(kernels::pswf(kernels_test::kernel_x_values.at(i), 6) -
                                             kernels_test::kernel_pswf_values.at(i));
     CHECK(pswf_difference < 1e-13);
     // Test that kaiser_bessel is the same as matlab calculations
     const t_real kb_difference =
         std::abs(kernels::kaiser_bessel(kernels_test::kernel_x_values.at(i), 6) -
                  kernels_test::kernel_kb_values.at(i));
     CHECK(kb_difference < 1e-13);
     // Test that gaussian is the same as matlab calculations
     const t_real gauss_difference =
         std::abs(kernels::gaussian(kernels_test::kernel_x_values.at(i), 6) -
                  kernels_test::kernel_gauss_values.at(i));
     CHECK(gauss_difference < 1e-13);
   }
 }
TEST_CASE() [2/2]
TEST_CASE ("kernel_correction")
Definition at line 55 of file kernels.cc.
References CHECK, kernels_test::correction_gauss_values, kernels_test::correction_kb_values, kernels_test::correction_pswf_values, kernels_test::correction_x_values, purify::kernels::ft_gaussian(), purify::kernels::ft_kaiser_bessel(), and purify::kernels::ft_pswf().
{
   const t_uint number_of_samples = kernels_test::correction_x_values.size();
   for (t_uint i = 0; i < number_of_samples; ++i) {
     const t_real pswf_difference =
         std::abs(kernels::ft_pswf(kernels_test::correction_x_values.at(i), 6) -
                  kernels_test::correction_pswf_values.at(i));
     CHECK(pswf_difference < 1e-13);  // Test that pswf is the same as matlab calculations
     const t_real kb_difference =
         std::abs(kernels::ft_kaiser_bessel(kernels_test::correction_x_values.at(i), 6) -
                  kernels_test::correction_kb_values.at(i));
     CHECK(kb_difference < 1e-13);  // Test that kaiser_bessel is the same as matlab calculations
     const t_real gauss_difference =
         std::abs(kernels::ft_gaussian(kernels_test::correction_x_values.at(i), 6) -
                  kernels_test::correction_gauss_values.at(i));
     CHECK(gauss_difference < 1e-13);  // Test that gaussian is the same as matlab calculations
   }
 }