var searchData=
[
  ['degridoperatoradjointfixture_988',['DegridOperatorAdjointFixture',['../classDegridOperatorAdjointFixture.html',1,'']]],
  ['degridoperatoradjointfixturedistr_989',['DegridOperatorAdjointFixtureDistr',['../classDegridOperatorAdjointFixtureDistr.html',1,'']]],
  ['degridoperatoradjointfixturempi_990',['DegridOperatorAdjointFixtureMPI',['../classDegridOperatorAdjointFixtureMPI.html',1,'']]],
  ['degridoperatoradjointfixturepar_991',['DegridOperatorAdjointFixturePar',['../classDegridOperatorAdjointFixturePar.html',1,'']]],
  ['degridoperatorctorfixturepar_992',['DegridOperatorCtorFixturePar',['../classDegridOperatorCtorFixturePar.html',1,'']]],
  ['degridoperatordirectfixture_993',['DegridOperatorDirectFixture',['../classDegridOperatorDirectFixture.html',1,'']]],
  ['degridoperatordirectfixturedistr_994',['DegridOperatorDirectFixtureDistr',['../classDegridOperatorDirectFixtureDistr.html',1,'']]],
  ['degridoperatordirectfixturempi_995',['DegridOperatorDirectFixtureMPI',['../classDegridOperatorDirectFixtureMPI.html',1,'']]],
  ['degridoperatordirectfixturepar_996',['DegridOperatorDirectFixturePar',['../classDegridOperatorDirectFixturePar.html',1,'']]],
  ['degridoperatorfixture_997',['DegridOperatorFixture',['../classDegridOperatorFixture.html',1,'']]],
  ['degridoperatorfixturepar_998',['DegridOperatorFixturePar',['../classDegridOperatorFixturePar.html',1,'']]],
  ['delayedproximalenveloppefunction_999',['DelayedProximalEnveloppeFunction',['http://astro-informatics.github.io/sopt/classsopt_1_1proximal_1_1details_1_1DelayedProximalEnveloppeFunction.html',1,'sopt::proximal::details']]],
  ['delayedproximalfunction_1000',['DelayedProximalFunction',['http://astro-informatics.github.io/sopt/classsopt_1_1proximal_1_1details_1_1DelayedProximalFunction.html',1,'sopt::proximal::details']]],
  ['derived_1001',['Derived',['http://astro-informatics.github.io/sopt/structsopt_1_1details_1_1HasValueType_1_1Derived.html',1,'sopt::details::HasValueType']]],
  ['diagnostic_1002',['Diagnostic',['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ProximalADMM_1_1Diagnostic.html',1,'sopt::algorithm::ProximalADMM::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::ForwardBackward::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1SDMM_1_1Diagnostic.html',1,'sopt::algorithm::SDMM::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1PrimalDual_1_1Diagnostic.html',1,'sopt::algorithm::PrimalDual::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingPrimalDual_1_1Diagnostic.html',1,'sopt::algorithm::ImagingPrimalDual::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::ImagingForwardBackward::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1proximal_1_1L1_1_1Diagnostic.html',1,'sopt::proximal::L1::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1ConjugateGradient_1_1Diagnostic.html',1,'sopt::ConjugateGradient::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingProximalADMM_1_1Diagnostic.html',1,'sopt::algorithm::ImagingProximalADMM::Diagnostic']]],
  ['diagnosticandresult_1003',['DiagnosticAndResult',['http://astro-informatics.github.io/sopt/structsopt_1_1ConjugateGradient_1_1DiagnosticAndResult.html',1,'sopt::ConjugateGradient::DiagnosticAndResult&lt; class &gt;'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ForwardBackward::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingPrimalDual_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingPrimalDual::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ProximalADMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ProximalADMM::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1SDMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::SDMM::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1PowerMethod_1_1DiagnosticAndResult.html',1,'sopt::algorithm::PowerMethod::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structDummyAlgorithm_1_1DiagnosticAndResult.html',1,'DummyAlgorithm::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1PrimalDual_1_1DiagnosticAndResult.html',1,'sopt::algorithm::PrimalDual::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingForwardBackward::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1proximal_1_1L1_1_1DiagnosticAndResult.html',1,'sopt::proximal::L1::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingProximalADMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingProximalADMM::DiagnosticAndResult']]],
  ['diagnosticandresultreg_1004',['DiagnosticAndResultReg',['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1JointMAP_1_1DiagnosticAndResultReg.html',1,'sopt::algorithm::JointMAP']]],
  ['directfilter_1005',['DirectFilter',['http://astro-informatics.github.io/sopt/structsopt_1_1wavelets_1_1WaveletData_1_1DirectFilter.html',1,'sopt::wavelets::WaveletData']]],
  ['dummyalgorithm_1006',['DummyAlgorithm',['http://astro-informatics.github.io/sopt/structDummyAlgorithm.html',1,'']]]
];
