var searchData=
[
  ['degridoperatoradjointfixture',['DegridOperatorAdjointFixture',['../classDegridOperatorAdjointFixture.html',1,'']]],
  ['degridoperatoradjointfixturedistr',['DegridOperatorAdjointFixtureDistr',['../classDegridOperatorAdjointFixtureDistr.html',1,'']]],
  ['degridoperatoradjointfixturempi',['DegridOperatorAdjointFixtureMPI',['../classDegridOperatorAdjointFixtureMPI.html',1,'']]],
  ['degridoperatoradjointfixturepar',['DegridOperatorAdjointFixturePar',['../classDegridOperatorAdjointFixturePar.html',1,'']]],
  ['degridoperatorctorfixturepar',['DegridOperatorCtorFixturePar',['../classDegridOperatorCtorFixturePar.html',1,'']]],
  ['degridoperatordirectfixture',['DegridOperatorDirectFixture',['../classDegridOperatorDirectFixture.html',1,'']]],
  ['degridoperatordirectfixturedistr',['DegridOperatorDirectFixtureDistr',['../classDegridOperatorDirectFixtureDistr.html',1,'']]],
  ['degridoperatordirectfixturempi',['DegridOperatorDirectFixtureMPI',['../classDegridOperatorDirectFixtureMPI.html',1,'']]],
  ['degridoperatordirectfixturepar',['DegridOperatorDirectFixturePar',['../classDegridOperatorDirectFixturePar.html',1,'']]],
  ['degridoperatorfixture',['DegridOperatorFixture',['../classDegridOperatorFixture.html',1,'']]],
  ['degridoperatorfixturepar',['DegridOperatorFixturePar',['../classDegridOperatorFixturePar.html',1,'']]],
  ['delayedproximalenveloppefunction',['DelayedProximalEnveloppeFunction',['http://astro-informatics.github.io/sopt/classsopt_1_1proximal_1_1details_1_1DelayedProximalEnveloppeFunction.html',1,'sopt::proximal::details']]],
  ['delayedproximalfunction',['DelayedProximalFunction',['http://astro-informatics.github.io/sopt/classsopt_1_1proximal_1_1details_1_1DelayedProximalFunction.html',1,'sopt::proximal::details']]],
  ['derived',['Derived',['http://astro-informatics.github.io/sopt/structsopt_1_1details_1_1HasValueType_1_1Derived.html',1,'sopt::details::HasValueType']]],
  ['diagnostic',['Diagnostic',['http://astro-informatics.github.io/sopt/structsopt_1_1proximal_1_1L1_1_1Diagnostic.html',1,'sopt::proximal::L1::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1SDMM_1_1Diagnostic.html',1,'sopt::algorithm::SDMM::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1PrimalDual_1_1Diagnostic.html',1,'sopt::algorithm::PrimalDual::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::ImagingForwardBackward::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1ConjugateGradient_1_1Diagnostic.html',1,'sopt::ConjugateGradient::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingProximalADMM_1_1Diagnostic.html',1,'sopt::algorithm::ImagingProximalADMM::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ForwardBackward_1_1Diagnostic.html',1,'sopt::algorithm::ForwardBackward::Diagnostic'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ProximalADMM_1_1Diagnostic.html',1,'sopt::algorithm::ProximalADMM::Diagnostic']]],
  ['diagnosticandresult',['DiagnosticAndResult',['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ForwardBackward::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1SDMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::SDMM::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1PowerMethod_1_1DiagnosticAndResult.html',1,'sopt::algorithm::PowerMethod::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1ConjugateGradient_1_1DiagnosticAndResult.html',1,'sopt::ConjugateGradient::DiagnosticAndResult&lt; T &gt;'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1PrimalDual_1_1DiagnosticAndResult.html',1,'sopt::algorithm::PrimalDual::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structDummyAlgorithm_1_1DiagnosticAndResult.html',1,'DummyAlgorithm::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1proximal_1_1L1_1_1DiagnosticAndResult.html',1,'sopt::proximal::L1::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingForwardBackward_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingForwardBackward::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ImagingProximalADMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ImagingProximalADMM::DiagnosticAndResult'],['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1ProximalADMM_1_1DiagnosticAndResult.html',1,'sopt::algorithm::ProximalADMM::DiagnosticAndResult']]],
  ['diagnosticandresultreg',['DiagnosticAndResultReg',['http://astro-informatics.github.io/sopt/structsopt_1_1algorithm_1_1JointMAP_1_1DiagnosticAndResultReg.html',1,'sopt::algorithm::JointMAP']]],
  ['directfilter',['DirectFilter',['http://astro-informatics.github.io/sopt/structsopt_1_1wavelets_1_1WaveletData_1_1DirectFilter.html',1,'sopt::wavelets::WaveletData']]],
  ['dummyalgorithm',['DummyAlgorithm',['http://astro-informatics.github.io/sopt/structDummyAlgorithm.html',1,'']]]
];
