var searchData=
[
  ['padmm_2ecc',['padmm.cc',['../padmm_8cc.html',1,'(Global Namespace)'],['http://astro-informatics.github.io/sopt/padmm_8cc.html',1,'(Global Namespace)']]],
  ['padmm_2eh',['padmm.h',['http://astro-informatics.github.io/sopt/padmm_8h.html',1,'']]],
  ['padmm_5finpainting_2ecc',['padmm_inpainting.cc',['http://astro-informatics.github.io/sopt/padmm__inpainting_8cc.html',1,'']]],
  ['padmm_5fmpi_2ecc',['padmm_mpi.cc',['../padmm__mpi_8cc.html',1,'']]],
  ['padmm_5fmpi_5frandom_5fcoverage_2ecc',['padmm_mpi_random_coverage.cc',['../padmm__mpi__random__coverage_8cc.html',1,'']]],
  ['padmm_5fmpi_5freal_5fdata_2ecc',['padmm_mpi_real_data.cc',['../padmm__mpi__real__data_8cc.html',1,'']]],
  ['padmm_5frandom_5fcoverage_2ecc',['padmm_random_coverage.cc',['../padmm__random__coverage_8cc.html',1,'']]],
  ['padmm_5freal_5fdata_2ecc',['padmm_real_data.cc',['../padmm__real__data_8cc.html',1,'']]],
  ['padmm_5freweighted_5fsimulation_2ecc',['padmm_reweighted_simulation.cc',['../padmm__reweighted__simulation_8cc.html',1,'']]],
  ['padmm_5fsimulation_2ecc',['padmm_simulation.cc',['../padmm__simulation_8cc.html',1,'']]],
  ['padmm_5fwarm_5fstart_2ecc',['padmm_warm_start.cc',['http://astro-informatics.github.io/sopt/padmm__warm__start_8cc.html',1,'']]],
  ['parallel_5fmpi_5futilities_2ecc',['parallel_mpi_utilities.cc',['../parallel__mpi__utilities_8cc.html',1,'']]],
  ['parser_5ftest_2ecc',['parser_test.cc',['../parser__test_8cc.html',1,'']]],
  ['pfitsio_2ecc',['pfitsio.cc',['../pfitsio_8cc.html',1,'']]],
  ['pfitsio_2eh',['pfitsio.h',['../pfitsio_8h.html',1,'']]],
  ['plot_5fwkernel_2ecc',['plot_wkernel.cc',['../plot__wkernel_8cc.html',1,'']]],
  ['positive_5fquadrant_2eh',['positive_quadrant.h',['http://astro-informatics.github.io/sopt/positive__quadrant_8h.html',1,'']]],
  ['positive_5fquadrant_5fprojection_2ecc',['positive_quadrant_projection.cc',['http://astro-informatics.github.io/sopt/positive__quadrant__projection_8cc.html',1,'']]],
  ['power_5fmethod_2ecc',['power_method.cc',['http://astro-informatics.github.io/sopt/examples_2power__method_8cc.html',1,'(Global Namespace)'],['http://astro-informatics.github.io/sopt/tests_2power__method_8cc.html',1,'(Global Namespace)']]],
  ['power_5fmethod_2eh',['power_method.h',['http://astro-informatics.github.io/sopt/power__method_8h.html',1,'']]],
  ['primal_5fdual_2ecc',['primal_dual.cc',['http://astro-informatics.github.io/sopt/primal__dual_8cc.html',1,'']]],
  ['primal_5fdual_2eh',['primal_dual.h',['http://astro-informatics.github.io/sopt/primal__dual_8h.html',1,'']]],
  ['proximal_2ecc',['proximal.cc',['http://astro-informatics.github.io/sopt/proximal_8cc.html',1,'']]],
  ['proximal_2eh',['proximal.h',['http://astro-informatics.github.io/sopt/proximal_8h.html',1,'']]],
  ['proximal_5fexpression_2eh',['proximal_expression.h',['http://astro-informatics.github.io/sopt/proximal__expression_8h.html',1,'']]],
  ['purify_5fcontributors_2emd',['PURIFY_CONTRIBUTORS.md',['../PURIFY__CONTRIBUTORS_8md.html',1,'']]],
  ['purify_5ffitsio_2ecc',['purify_fitsio.cc',['../purify__fitsio_8cc.html',1,'']]]
];
