var searchData=
[
  ['image_5ffilename',['image_filename',['../namespacepurify_1_1notinstalled.html#adcd4a748b6eaf349d7a41cfc85428883',1,'purify::notinstalled']]],
  ['ind2sub',['ind2sub',['../namespacepurify_1_1utilities.html#afb213bdf3ecdb4d9557e810349443234',1,'purify::utilities']]],
  ['indexmapping',['IndexMapping',['../classpurify_1_1IndexMapping.html#a3cf84d8eb0d9b3b9c7b7ed08cca787b6',1,'purify::IndexMapping::IndexMapping(const std::vector&lt; t_int &gt; &amp;indices, const t_int N, const t_int start=0)'],['../classpurify_1_1IndexMapping.html#a08f286e69b232701b9be656282141668',1,'purify::IndexMapping::IndexMapping(const ITER &amp;first, const ITER &amp;end, const t_int N, const t_int start=0)'],['../classpurify_1_1IndexMapping.html#aba763e2e761a4b1c1e092f0cd863476b',1,'purify::IndexMapping::IndexMapping(const std::set&lt; t_int &gt; &amp;indices, const t_int N, const t_int start=0)']]],
  ['init_5fcorrection2d',['init_correction2d',['../namespacepurify_1_1details.html#a288d7453cd72dededadfb96cfcad60b4',1,'purify::details']]],
  ['init_5fcorrection_5fradial_5f2d',['init_correction_radial_2d',['../namespacepurify_1_1details.html#a8baba6d82e8930a1b2571c541a660669',1,'purify::details']]],
  ['init_5fdegrid_5foperator_5f2d',['init_degrid_operator_2d',['../namespacepurify_1_1measurementoperator.html#aff5a8794ed28522484f6b2fdae3724cb',1,'purify::measurementoperator::init_degrid_operator_2d(const Vector&lt; t_real &gt; &amp;u, const Vector&lt; t_real &gt; &amp;v, const Vector&lt; t_real &gt; &amp;w, const Vector&lt; t_complex &gt; &amp;weights, const t_uint &amp;imsizey, const t_uint &amp;imsizex, const t_real &amp;oversample_ratio=2, const kernels::kernel kernel=kernels::kernel::kb, const t_uint Ju=4, const t_uint Jv=4, const bool w_stacking=false, const t_real &amp;cellx=1, const t_real &amp;celly=1)'],['../namespacepurify_1_1measurementoperator.html#aa97759ff26b02066f150a1f83f447db6',1,'purify::measurementoperator::init_degrid_operator_2d(const utilities::vis_params &amp;uv_vis_input, const t_uint &amp;imsizey, const t_uint &amp;imsizex, const t_real &amp;cell_x, const t_real &amp;cell_y, const t_real &amp;oversample_ratio=2, const kernels::kernel kernel=kernels::kernel::kb, const t_uint Ju=4, const t_uint Jv=4, const bool w_stacking=false)'],['../namespacepurify_1_1measurementoperator.html#af2d03beb248bc90cbce87b61a676993c',1,'purify::measurementoperator::init_degrid_operator_2d(const Vector&lt; t_real &gt; &amp;u, const Vector&lt; t_real &gt; &amp;v, const Vector&lt; t_real &gt; &amp;w, const Vector&lt; t_complex &gt; &amp;weights, const t_uint imsizey, const t_uint imsizex, const t_real oversample_ratio, const kernels::kernel kernel, const t_uint Ju, const t_uint Jw, const bool w_stacking, const t_real cellx, const t_real celly, const t_real absolute_error, const t_real relative_error, const dde_type dde)'],['../namespacepurify_1_1measurementoperator.html#af14d4bff532ed08e5f31dc24d0e1bde2',1,'purify::measurementoperator::init_degrid_operator_2d(const utilities::vis_params &amp;uv_vis_input, const t_uint imsizey, const t_uint imsizex, const t_real cell_x, const t_real cell_y, const t_real oversample_ratio, const kernels::kernel kernel, const t_uint Ju, const t_uint Jw, const bool w_stacking, const t_real absolute_error, const t_real relative_error, const dde_type dde)']]],
  ['init_5ffft_5f2d',['init_FFT_2d',['../namespacepurify_1_1operators.html#adb16231e49aafda70e2b117b4d6190fc',1,'purify::operators']]],
  ['init_5fgridding_5fmatrix_5f2d',['init_gridding_matrix_2d',['../namespacepurify_1_1details.html#a96036c7a586e56d378dbbb4dad742144',1,'purify::details::init_gridding_matrix_2d(const Vector&lt; t_real &gt; &amp;u, const Vector&lt; t_real &gt; &amp;v, const Vector&lt; t_complex &gt; &amp;weights, const t_uint &amp;imsizey_, const t_uint &amp;imsizex_, const t_real &amp;oversample_ratio, const std::function&lt; t_real(t_real)&gt; kernelu, const std::function&lt; t_real(t_real)&gt; kernelv, const t_uint Ju, const t_uint Jv)'],['../namespacepurify_1_1details.html#aadad7ec0a0d88c5ddd10f28a27d1b4a5',1,'purify::details::init_gridding_matrix_2d(const Vector&lt; t_real &gt; &amp;u, const Vector&lt; t_real &gt; &amp;v, const Vector&lt; t_real &gt; &amp;w, const Vector&lt; t_complex &gt; &amp;weights, const t_uint imsizey_, const t_uint imsizex_, const t_real oversample_ratio, const std::function&lt; t_real(t_real)&gt; &amp;ftkerneluv, const std::function&lt; t_real(t_real)&gt; &amp;kerneluv, const t_uint Ju, const t_uint Jw, const t_real cellx, const t_real celly, const t_real abs_error, const t_real rel_error, const dde_type dde)'],['../namespacepurify_1_1details.html#a196bc201d3a368eeeadafc2ca859368a',1,'purify::details::init_gridding_matrix_2d(const Sparse&lt; T &gt; &amp;mixing_matrix, ARGS &amp;&amp;... args)'],['../namespacepurify_1_1operators.html#ac94ce709c2bbcf2f07d31a68fe962f82',1,'purify::operators::init_gridding_matrix_2d()']]],
  ['init_5fnormalise',['init_normalise',['../namespacepurify_1_1operators.html#acbb0f25b649b725caa29142a3c9acb43',1,'purify::operators']]],
  ['init_5fweights',['init_weights',['../namespacepurify_1_1utilities.html#a0bb5cc817f651a8bf2d9eebdfbf91caf',1,'purify::utilities']]],
  ['init_5fweights_5f',['init_weights_',['../namespacepurify_1_1operators.html#a1dc82eed77f88b50dd4c2689c88d53fe',1,'purify::operators']]],
  ['init_5fzero_5fpadding_5f2d',['init_zero_padding_2d',['../namespacepurify_1_1operators.html#a1ece84ba389010359b10f07ee76bc984',1,'purify::operators']]],
  ['initialize',['initialize',['../namespacepurify_1_1logging.html#a766221e3a05f736017082766ede24d4a',1,'purify::logging::initialize(std::string const &amp;name=&quot;&quot;)'],['../namespacepurify_1_1logging.html#a5a761be31c4fb31b3a9e636c17133904',1,'purify::logging::initialize()']]],
  ['integrate',['integrate',['../namespacepurify_1_1integration.html#ae71083362428137f328d85469be8c255',1,'purify::integration::integrate(const Vector&lt; t_real &gt; &amp;xmin, const Vector&lt; t_real &gt; &amp;xmax, const std::function&lt; t_real(Vector&lt; t_real &gt;)&gt; &amp;func, const norm_type norm, const t_real required_abs_error, const t_real required_rel_error, const t_uint max_evaluations, const method methodtype)'],['../namespacepurify_1_1integration.html#a10cce957449a468b764cf02c240848ac',1,'purify::integration::integrate(const Vector&lt; t_real &gt; &amp;xmin, const Vector&lt; t_real &gt; &amp;xmax, const std::function&lt; t_complex(Vector&lt; t_real &gt;)&gt; &amp;func, const norm_type norm, const t_real required_abs_error, const t_real required_rel_error, const t_uint max_evaluations, const method methodtype)'],['../namespacepurify_1_1integration.html#a7d5e16597c855bdf29d195364c353e18',1,'purify::integration::integrate(const t_uint fdim, const Vector&lt; t_real &gt; &amp;xmin, const Vector&lt; t_real &gt; &amp;xmax, const std::function&lt; Vector&lt; t_real &gt;(Vector&lt; t_real &gt;)&gt; &amp;func, const norm_type norm, const t_real required_abs_error, const t_real required_rel_error, const t_uint max_evaluations, const method methodtype)']]],
  ['integrate_5fv',['integrate_v',['../namespacepurify_1_1integration.html#a1cd627283e9e7bca5d0b763a9f7b05c5',1,'purify::integration::integrate_v(const t_uint fdim, const t_uint npts, const Vector&lt; t_real &gt; &amp;xmin, const Vector&lt; t_real &gt; &amp;xmax, const std::vector&lt; std::function&lt; t_complex(Vector&lt; t_real &gt;)&gt;&gt; &amp;func, const norm_type norm, const t_real required_abs_error, const t_real required_rel_error, const t_uint max_evaluations, const method methodtype)'],['../namespacepurify_1_1integration.html#af0570a8b8956046214f724b5e6982344',1,'purify::integration::integrate_v(const t_uint fdim, const Vector&lt; t_real &gt; &amp;xmin, const Vector&lt; t_real &gt; &amp;xmax, const std::vector&lt; std::function&lt; t_complex(Vector&lt; t_real &gt;)&gt;&gt; &amp;func, const norm_type norm, const t_real required_abs_error, const t_real required_rel_error, const t_uint max_evaluations, const method methodtype)']]],
  ['is_5fvalid',['is_valid',['../classpurify_1_1casa_1_1MeasurementSet_1_1ChannelWrapper.html#afc12a6cdd8db10b9bcc921e01c95ff24',1,'purify::casa::MeasurementSet::ChannelWrapper']]]
];
