src/example_ami.c File Reference
example_ami.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <complex.h>
#include <fftw3.h>
#include <math.h>
#include <assert.h>
#include <time.h>
#include <cblas.h>
#include "purify_visibility.h"
#include "purify_sparsemat.h"
#include "purify_image.h"
#include "purify_measurement.h"
#include "purify_types.h"
#include "purify_error.h"
#include "purify_ran.h"
#include "sopt_image.h"
#include "sopt_utility.h"
#include "sopt_prox.h"
#include "sopt_tv.h"
#include "sopt_l1.h"
#include "sopt_wavelet.h"
#include "sopt_sara.h"
#include "sopt_ran.h"
#include "purify_utils.h"
Defines
#define VERBOSE 1
Functions
int main (int argc, char *argv[])
Detailed Description
Image recontruction example from continuos visibilities. Test image: M31 128x128. Coverage: AMI simulation with M=9413 visibilities.
Definition in file example_ami.c.
Define Documentation
#define VERBOSE 1
Definition at line 43 of file example_ami.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 45 of file example_ami.c.
References purify_image::fov_x, purify_image::fov_y, purify_measurement_cparam::kx, purify_measurement_cparam::ky, purify_measurement_cparam::nmeas, purify_visibility::nmeas, purify_image::nx, purify_measurement_cparam::nx1, purify_image::ny, purify_measurement_cparam::ny1, purify_measurement_cparam::ofx, purify_measurement_cparam::ofy, purify_image::pix, PURIFY_ERROR_MEM_ALLOC_CHECK(), PURIFY_IMAGE_FILETYPE_FITS, purify_image_free(), purify_image_readfile(), purify_image_writefile(), purify_measurement_cftadj(), purify_measurement_cftfwd(), purify_measurement_init_cft(), PURIFY_PI, purify_sparsemat_freer(), purify_utils_maxarray(), PURIFY_VISIBILITY_FILETYPE_PROFILE_VIS, purify_visibility_free(), purify_visibility_readfile(), purify_visibility::u, and purify_visibility::v.