include/purify_error.h File Reference
purify_error.h File Reference
Functions
void PURIFY_ERROR_GENERIC (char *comment)
void PURIFY_ERROR_MEM_ALLOC_CHECK (void *pointer)
Detailed Description
Error functions used in PURIFY package.
Definition in file purify_error.h.
Function Documentation
void PURIFY_ERROR_GENERIC (char * comment) [inline]
Display error message and halt program execution.
Parameters:
[in] comment Additional comment to display.
Authors:
Jason McEwen
Definition at line 15 of file purify_error.c.
Referenced by PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_image_ind2iuiv(), purify_image_ixiy2ind(), purify_image_readfile(), purify_image_writefile(), purify_ran_knuthshuffle(), purify_visibility_ind2iuiv(), purify_visibility_iuiv2ind(), purify_visibility_ivis2vis(), purify_visibility_readfile(), purify_visibility_vdsmask(), and purify_visibility_writefile().
void PURIFY_ERROR_MEM_ALLOC_CHECK (void * pointer) [inline]
Test whether memory allocation was successful (i.e. check allocated pointer not NULL) and throw a generic error is allocation failed.
Parameters:
[in] pointer Pointer that should point to allocated memory is memory allocation was successful.
Authors:
Jason McEwen
Definition at line 35 of file purify_error.c.
References PURIFY_ERROR_GENERIC().
Referenced by main(), purify_image_readfile(), purify_measurement_fft_real(), purify_measurement_init_cft(), purify_measurement_opfwd(), purify_measurement_pow_meth(), purify_ran_knuthshuffle(), purify_sparsemat_explictmat(), purify_sparsemat_explictmatr(), purify_visibility_alloc(), purify_visibility_genranmask(), purify_visibility_ivis2mask(), purify_visibility_mask2ivis(), purify_visibility_vdsmask(), and purify_visibility_vis2mask().