src/purify_sparsemat.c File Reference
purify_sparsemat.c File Reference
#include <stdlib.h>
#include "purify_sparsemat.h"
#include "purify_error.h"
Functions
void purify_sparsemat_free (purify_sparsemat *mat)
void purify_sparsemat_explictmat (double **A, purify_sparsemat *S)
void purify_sparsemat_fwd_real (double *y, double *x, purify_sparsemat *A)
void purify_sparsemat_adj_real (double *y, double *x, purify_sparsemat *A)
void purify_sparsemat_fwd_complex (complex double *y, complex double *x, purify_sparsemat *A)
void purify_sparsemat_adj_complex (complex double *y, complex double *x, purify_sparsemat *A)
void purify_sparsemat_freer (purify_sparsemat_row *mat)
void purify_sparsemat_explictmatr (double **A, purify_sparsemat_row *S)
void purify_sparsemat_fwd_realr (double *y, double *x, purify_sparsemat_row *A)
void purify_sparsemat_adj_realr (double *y, double *x, purify_sparsemat_row *A)
void purify_sparsemat_fwd_complexr (complex double *y, complex double *x, purify_sparsemat_row *A)
void purify_sparsemat_adj_complexr (complex double *y, complex double *x, purify_sparsemat_row *A)
Detailed Description
Functionality to perform operations with sparse matrices.
Definition in file purify_sparsemat.c.
Function Documentation
void purify_sparsemat_adj_complex (complex double * y, complex double * x, purify_sparsemat * A)
Multiple a complex vector by the adjoint of a real sparse matrix, i.e. compute , where is the Hermitian operator.
Parameters:
[out] y Ouput vector of length ncols.
[in] x Input vector of length nrows.
[in] A Sparse matrix (passed by reference).
Note:
Space for the output vector must be allocated by the calling routine.
Authors:
Jason McEwen
Definition at line 162 of file purify_sparsemat.c.
References purify_sparsemat::colptr, purify_sparsemat::cvals, purify_sparsemat::ncols, purify_sparsemat::real, purify_sparsemat::rowind, and purify_sparsemat::vals.
Referenced by purify_measurement_mask_opadj().
void purify_sparsemat_adj_complexr (complex double * y, complex double * x, purify_sparsemat_row * A)
Multiply a complex vector by the adjoint of a real sparse matrix, i.e. compute , where is the Hermitian operator.
Parameters:
[out] y Ouput vector of length ncols.
[in] x Input vector of length nrows.
[in] A Sparse matrix (passed by reference).
Note:
Space for the output vector must be allocated by the calling routine.
Authors:
Jason McEwen
Definition at line 335 of file purify_sparsemat.c.
References purify_sparsemat_row::colind, purify_sparsemat_row::cvals, purify_sparsemat_row::ncols, purify_sparsemat_row::nrows, purify_sparsemat_row::real, purify_sparsemat_row::rowptr, and purify_sparsemat_row::vals.
Referenced by purify_measurement_cftadj().
void purify_sparsemat_adj_real (double * y, double * x, purify_sparsemat * A)
Multiple a real vector by the adjoint of a real sparse matrix, i.e. compute , where is the Hermitian operator.
Parameters:
[out] y Ouput vector of length ncols.
[in] x Input vector of length nrows.
[in] A Sparse matrix (passed by reference).
Note:
Space for the output vector must be allocated by the calling routine.
Authors:
Jason McEwen
Definition at line 102 of file purify_sparsemat.c.
References purify_sparsemat::colptr, purify_sparsemat::ncols, purify_sparsemat::rowind, and purify_sparsemat::vals.
void purify_sparsemat_adj_realr (double * y, double * x, purify_sparsemat_row * A)
Multiple a real vector by the adjoint of a real sparse matrix, i.e. compute , where is the Hermitian operator.
Parameters:
[out] y Ouput vector of length ncols.
[in] x Input vector of length nrows.
[in] A Sparse matrix (passed by reference).
Note:
Space for the output vector must be allocated by the calling routine.
Authors:
Jason McEwen
Definition at line 273 of file purify_sparsemat.c.
References purify_sparsemat_row::colind, purify_sparsemat_row::ncols, purify_sparsemat_row::nrows, purify_sparsemat_row::rowptr, and purify_sparsemat_row::vals.
void purify_sparsemat_explictmat (double ** A, purify_sparsemat * S)
Compute explicit representation of a sparse matrix.
Parameters:
[out] A Explicit matrix representation of sparse matrix S. The matrix A is stored in column-major order, i.e. can be accessed as A[col_index * nrows + row_index].
[in] S Sparse matrix to representation explicitly (passed by reference).
Note:
Space for the output matrix A is allocated herein and must be freed by the calling routine.
Authors:
Jason McEwen
Definition at line 46 of file purify_sparsemat.c.
References purify_sparsemat::colptr, purify_sparsemat::ncols, purify_sparsemat::nrows, PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_sparsemat::rowind, and purify_sparsemat::vals.
void purify_sparsemat_explictmatr (double ** A, purify_sparsemat_row * S)
Compute explicit representation of a sparse matrix.
Parameters:
[out] A Explicit matrix representation of sparse matrix S. The matrix A is stored in row-major order, i.e. can be accessed as A[row_index * ncols + col_index].
[in] S Sparse matrix to representation explicitly (passed by reference).
Note:
Space for the output matrix A is allocated herein and must be freed by the calling routine.
Authors:
Jason McEwen
Definition at line 219 of file purify_sparsemat.c.
References purify_sparsemat_row::colind, purify_sparsemat_row::ncols, purify_sparsemat_row::nrows, PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_sparsemat_row::rowptr, and purify_sparsemat_row::vals.
void purify_sparsemat_free (purify_sparsemat * mat)
Free all memory used to store a spare matrix.
Parameters:
[in] mat Sparse matrix to free.
Authors:
Jason McEwen
Definition at line 18 of file purify_sparsemat.c.
References purify_sparsemat::colptr, purify_sparsemat::cvals, purify_sparsemat::ncols, purify_sparsemat::nrows, purify_sparsemat::nvals, purify_sparsemat::real, purify_sparsemat::rowind, and purify_sparsemat::vals.
void purify_sparsemat_freer (purify_sparsemat_row * mat)
Free all memory used to store a spare matrix.
Parameters:
[in] mat Sparse matrix to free.
Authors:
Jason McEwen
Definition at line 191 of file purify_sparsemat.c.
References purify_sparsemat_row::colind, purify_sparsemat_row::cvals, purify_sparsemat_row::ncols, purify_sparsemat_row::nrows, purify_sparsemat_row::nvals, purify_sparsemat_row::real, purify_sparsemat_row::rowptr, and purify_sparsemat_row::vals.
Referenced by main().
void purify_sparsemat_fwd_complex (complex double * y, complex double * x, purify_sparsemat * A)
Multiple a complex vector by a real sparse matrix, i.e. compute .
Parameters:
[out] y Ouput vector of length nrows.
[in] x Input vector of length ncols.
[in] A Sparse matrix (passed by reference).
Note:
Space for the output vector must be allocated by the calling routine.
Authors:
Jason McEwen
Definition at line 128 of file purify_sparsemat.c.
References purify_sparsemat::colptr, purify_sparsemat::cvals, purify_sparsemat::ncols, purify_sparsemat::nrows, purify_sparsemat::real, purify_sparsemat::rowind, and purify_sparsemat::vals.
Referenced by purify_measurement_mask_opfwd().
void purify_sparsemat_fwd_complexr (complex double * y, complex double * x, purify_sparsemat_row * A)
Multiply a complex vector by a real sparse matrix, i.e. compute .
Parameters:
[out] y Ouput vector of length nrows.
[in] x Input vector of length ncols.
[in] A Sparse matrix (passed by reference).
Note:
Space for the output vector must be allocated by the calling routine.
Authors:
Jason McEwen
Definition at line 300 of file purify_sparsemat.c.
References purify_sparsemat_row::colind, purify_sparsemat_row::cvals, purify_sparsemat_row::nrows, purify_sparsemat_row::real, purify_sparsemat_row::rowptr, and purify_sparsemat_row::vals.
Referenced by purify_measurement_cftfwd().
void purify_sparsemat_fwd_real (double * y, double * x, purify_sparsemat * A)
Multiple a real vector by a real sparse matrix, i.e. compute .
Parameters:
[out] y Ouput vector of length nrows.
[in] x Input vector of length ncols.
[in] A Sparse matrix (passed by reference).
Note:
Space for the output vector must be allocated by the calling routine.
Authors:
Jason McEwen
Definition at line 75 of file purify_sparsemat.c.
References purify_sparsemat::colptr, purify_sparsemat::ncols, purify_sparsemat::nrows, purify_sparsemat::rowind, and purify_sparsemat::vals.
void purify_sparsemat_fwd_realr (double * y, double * x, purify_sparsemat_row * A)
Multiple a real vector by a real sparse matrix, i.e. compute .
Parameters:
[out] y Ouput vector of length nrows.
[in] x Input vector of length ncols.
[in] A Sparse matrix (passed by reference).
Note:
Space for the output vector must be allocated by the calling routine.
Authors:
Jason McEwen
Definition at line 248 of file purify_sparsemat.c.
References purify_sparsemat_row::colind, purify_sparsemat_row::nrows, purify_sparsemat_row::rowptr, and purify_sparsemat_row::vals.