src/purify_utils.c File Reference
purify_utils.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "purify_error.h"
#include "purify_types.h"
Functions
void purify_utils_fftshift_1d (double *out, double *in, int n)
void purify_utils_ifftshift_1d (double *out, double *in, int n)
double purify_utils_maxarray (double *a, int num_elements)
int purify_utils_absearch (double *x, int nx, double key)
Function Documentation
int purify_utils_absearch (double * x, int nx, double key)
Find the index of the closest memmber of an array to the input.
Parameters:
[in] x array of real numbers.
[in] nx number of elements in the array.
[in] key input real number to search for.
Return values:
ind output index.
Authors:
Rafael Carrillo
Definition at line 98 of file purify_utils.c.
Referenced by purify_measurement_init_cft().
void purify_utils_fftshift_1d (double * out, double * in, int n)
fftshift of 1D array. Swaps the second and first parts of the array.
Parameters:
[out] out shifted output array.
[in] in input array.
[in] n number of elements in the array.
Authors:
Rafael Carrillo
Definition at line 22 of file purify_utils.c.
void purify_utils_ifftshift_1d (double * out, double * in, int n)
inverse fftshift of 1D array .
Parameters:
[out] out shifted output array.
[in] in input array.
[in] n number of elements in the array.
Authors:
Rafael Carrillo
Definition at line 49 of file purify_utils.c.
Referenced by purify_visibility_vdsmask().
double purify_utils_maxarray (double * a, int num_elements)
Find the maximum of an array.
Parameters:
[in] a array of real numbers.
[in] num_elements number of elements in the array.
Return values:
max output value.
Authors:
Rafael Carrillo
Definition at line 76 of file purify_utils.c.
Referenced by main(), and purify_visibility_modifypdf().