include/purify_measurement.h File Reference
purify_measurement.h File Reference
Data Structures
struct purify_measurement_cparam
Functions
void purify_measurement_fft_real (void *out, void *in, void **data)
void purify_measurement_fft_complex (void *out, void *in, void **data)
void purify_measurement_mask_opfwd (void *out, void *in, void **data)
void purify_measurement_mask_opadj (void *out, void *in, void **data)
void purify_measurement_opfwd (void *out, void *in, void **data)
void purify_measurement_init_cft (purify_sparsemat_row *mat, double *deconv, double *u, double *v, purify_measurement_cparam *param)
void purify_measurement_cftfwd (void *out, void *in, void **data)
void purify_measurement_cftadj (void *out, void *in, void **data)
double purify_measurement_pow_meth (void(*A)(void *out, void *in, void **data), void **A_data, void(*At)(void *out, void *in, void **data), void **At_data)
void purify_measurement_symcftfwd (void *out, void *in, void **data)
void purify_measurement_symcftadj (void *out, void *in, void **data)
Function Documentation
void purify_measurement_cftadj (void * out, void * in, void ** data)
Define adjoint measurement operator for continuos visibilities (currently includes adjoint continuos Fourier transform only).
Parameters:
[out] out (complex double*) Output image.
[in] in (complex double*) Input visibilities.
[in] data
data[0] (purify_measurement_cparam*): Parameters for the continuos Fourier transform.
data[1] (double*): Matrix with the deconvolution kernel in image space.
data[2] (purify_sparsemat_row*): The sparse matrix defining the convolution operator for the the interpolation.
data[3] (fftw_plan*): The complex-to-complex FFTW plan to use when computing the inverse Fourier transform (passed as an input so that the FFTW can be FFTW_MEASUREd beforehand).
data[4] (complex double*) Temporal memory for the zero padding.
Authors:
Rafael Carrillo
Definition at line 802 of file purify_measurement.c.
References purify_measurement_cparam::nx1, purify_measurement_cparam::ny1, purify_measurement_cparam::ofx, purify_measurement_cparam::ofy, and purify_sparsemat_adj_complexr().
Referenced by main(), and purify_measurement_symcftadj().
void purify_measurement_cftfwd (void * out, void * in, void ** data)
Define measurement operator for continuos visibilities (currently includes continuos Fourier transform only).
Parameters:
[out] out (complex double*) Measured visibilities.
[in] in (complex double*) Input image.
[in] data
data[0] (purify_measurement_cparam*): Parameters for the continuos Fourier transform.
data[1] (double*): Matrix with the deconvolution kernel in image space.
data[2] (purify_sparsemat_row*): The sparse matrix defining the convolution operator for the the interpolation.
data[3] (fftw_plan*): The complex-to-complex FFTW plan to use when computing the Fourier transform (passed as an input so that the FFTW can be FFTW_MEASUREd beforehand).
data[4] (complex double*) Temporal memory for the zero padding.
Authors:
Rafael Carrillo
Definition at line 728 of file purify_measurement.c.
References purify_measurement_cparam::nx1, purify_measurement_cparam::ny1, purify_measurement_cparam::ofx, purify_measurement_cparam::ofy, and purify_sparsemat_fwd_complexr().
Referenced by main(), and purify_measurement_symcftfwd().
void purify_measurement_fft_complex (void * out, void * in, void ** data)
Compute forward Fouier transform of complex signal.
Parameters:
[out] out (complex double*) Forward Fourier transform of input signal.
[in] in (complex double*) Complex input signal.
[in] data
data[0] (fftw_plan*): The real-to-complex FFTW plan to use when computing the Fourier transform (passed as an input so that the FFTW can be FFTW_MEASUREd beforehand).
Authors:
Jason McEwen
Definition at line 127 of file purify_measurement.c.
void purify_measurement_fft_real (void * out, void * in, void ** data)
Compute forward Fouier transform of real signal. A real-to-complex FFT is used (for speed optimisation) but the complex output signal is filled to its full size through conjugate symmetry.
Parameters:
[out] out (complex double*) Forward Fourier transform of input signal.
[in] in (double*) Real input signal.
[in] data
data[0] (fftw_plan*): The real-to-complex FFTW plan to use when computing the Fourier transform (passed as an input so that the FFTW can be FFTW_MEASUREd beforehand).
data[1] (purify_image*): The image defining the size of the Fourier transform.
Authors:
Jason McEwen
Definition at line 44 of file purify_measurement.c.
References purify_image::nx, purify_image::ny, PURIFY_ERROR_MEM_ALLOC_CHECK(), and purify_visibility_iuiv2ind().
Referenced by purify_measurement_opfwd().
void purify_measurement_init_cft (purify_sparsemat_row * mat, double * deconv, double * u, double * v, purify_measurement_cparam * param)
Initialization for the continuos Fourier transform operator.
Parameters:
[out] mat (purify_sparsemat_row*) Sparse matrix containing the interpolation kernels for each visibility. The matrix is stored in compressed row storage format.
[out] deconv (double*) Deconvolution kernel in real space
[in] u (double*) u coodinates between -pi and pi
[in] v (double*) v coodinates between -pi and pi
[in] param structure storing information for the operator
Authors:
Rafael Carrillo
Definition at line 244 of file purify_measurement.c.
References purify_sparsemat_row::colind, purify_sparsemat_row::cvals, purify_measurement_cparam::kx, purify_measurement_cparam::ky, purify_sparsemat_row::ncols, purify_measurement_cparam::nmeas, purify_sparsemat_row::nrows, purify_sparsemat_row::nvals, purify_measurement_cparam::nx1, purify_measurement_cparam::ny1, purify_measurement_cparam::ofx, purify_measurement_cparam::ofy, PURIFY_ERROR_MEM_ALLOC_CHECK(), PURIFY_PI, purify_utils_absearch(), purify_sparsemat_row::real, purify_sparsemat_row::rowptr, and purify_sparsemat_row::vals.
Referenced by main().
void purify_measurement_mask_opadj (void * out, void * in, void ** data)
Adjoint visibility masking operator.
Parameters:
[out] out (complex double*) Output vector of full visibilities after adjoint of masking.
[in] in (complex double*) Input vector of masked visibilities prior to adjoint of masking.
[in] data
data[0] (purify_sparsemat*): The sparse matrix defining the masking operator.
Authors:
Jason McEwen
Definition at line 175 of file purify_measurement.c.
References purify_sparsemat_adj_complex().
void purify_measurement_mask_opfwd (void * out, void * in, void ** data)
Forward visibility masking operator.
Parameters:
[out] out (complex double*) Output vector of masked visibilities.
[in] in (complex double*) Input vector of full visibilities to mask.
[in] data
data[0] (purify_sparsemat*): The sparse matrix defining the masking operator.
Authors:
Jason McEwen
Definition at line 151 of file purify_measurement.c.
References purify_sparsemat_fwd_complex().
Referenced by purify_measurement_opfwd().
void purify_measurement_opfwd (void * out, void * in, void ** data)
Define measurement operator (currently includes Fourier transform and masking only).
Parameters:
[out] out (complex double*) Measured visibilities.
[in] in (double*) Real input image.
[in] data
data[0] (fftw_plan*): The real-to-complex FFTW plan to use when computing the Fourier transform (passed as an input so that the FFTW can be FFTW_MEASUREd beforehand).
data[1] (purify_image*): The image defining the size of the Fourier transform.
data[2] (purify_sparsemat*): The sparse matrix defining the masking operator.
Authors:
Jason McEwen
Definition at line 203 of file purify_measurement.c.
References purify_image::nx, purify_image::ny, PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_measurement_fft_real(), and purify_measurement_mask_opfwd().
double purify_measurement_pow_meth (void(*)(void *out, void *in, void **data) A, void ** A_data, void(*)(void *out, void *in, void **data) At, void ** At_data)
Power method to compute the norm of the operator A.
Return values:
bound upper bound on norm of the continuos Fourier transform operator (double).
Parameters:
[in] A Pointer to the measurement operator.
[in] A_data Data structure associated to A.
[in] At Pointer to the the adjoint of the measurement operator.
[in] At_data Data structure associated to At.
Authors:
Rafael Carrillo
Definition at line 862 of file purify_measurement.c.
References purify_measurement_cparam::nmeas, purify_measurement_cparam::nx1, purify_measurement_cparam::ny1, PURIFY_ERROR_MEM_ALLOC_CHECK(), and purify_ran_gasdev2().
void purify_measurement_symcftadj (void * out, void * in, void ** data)
Define adjoint measurement operator for continuos visibilities It takes advantage of signal reality and conjugate symmetry. (currently includes adjoint continuos Fourier transform only).
Parameters:
[out] out (complex double*) Output image. Imaginary part set to zero.
[in] in (complex double*) Input visibilities.
[in] data
data[0] (purify_measurement_cparam*): Parameters for the continuos Fourier transform.
data[1] (double*): Matrix with the deconvolution kernel in image space.
data[2] (purify_sparsemat_row*): The sparse matrix defining the convolution operator for the the interpolation.
data[3] (fftw_plan*): The complex-to-complex FFTW plan to use when computing the inverse Fourier transform (passed as an input so that the FFTW can be FFTW_MEASUREd beforehand).
data[4] (complex double*) Temporal memory for the zero padding.
Authors:
Rafael Carrillo
Definition at line 1015 of file purify_measurement.c.
References purify_measurement_cparam::nx1, purify_measurement_cparam::ny1, and purify_measurement_cftadj().
void purify_measurement_symcftfwd (void * out, void * in, void ** data)
Define forward measurement operator for continuos visibilities It takes advantage of signal reality and conjugate symmetry. (currently includes adjoint continuos Fourier transform only).
Parameters:
[out] out (complex double*) Output visibilities.
[in] in (complex double*) Input image. Assumed real. Imaginary part set to zero.
[in] data
data[0] (purify_measurement_cparam*): Parameters for the continuos Fourier transform.
data[1] (double*): Matrix with the deconvolution kernel in image space.
data[2] (purify_sparsemat_row*): The sparse matrix defining the convolution operator for the the interpolation.
data[3] (fftw_plan*): The complex-to-complex FFTW plan to use when computing the inverse Fourier transform (passed as an input so that the FFTW can be FFTW_MEASUREd beforehand).
data[4] (complex double*) Temporal memory for the zero padding.
Authors:
Rafael Carrillo
Definition at line 969 of file purify_measurement.c.
References purify_measurement_cparam::nmeas, and purify_measurement_cftfwd().