src/purify_image.c File Reference
purify_image.c File Reference
#include <fitsio.h>
#include <stdio.h>
#include <math.h>
#include "purify_image.h"
#include "purify_error.h"
#include "purify_types.h"
Functions
void purify_image_ixiy2ind (int *ind, int ix, int iy, purify_image *img)
void purify_image_ind2iuiv (int *ix, int *iy, int ind, purify_image *img)
void purify_image_free (purify_image *img)
int purify_image_compare (purify_image *img1, purify_image *img2, double tol)
int purify_image_readfile (purify_image *img, const char *filename, purify_image_filetype filetype)
int purify_image_writefile (purify_image *img, const char *filename, purify_image_filetype filetype)
Detailed Description
Functionality to operate on images.
Definition in file purify_image.c.
Function Documentation
int purify_image_compare (purify_image * img1, purify_image * img2, double tol)
Compare two image objects to see whether they hold identical data.
Parameters:
[in] img1 First image object.
[in] img2 Second img object.
[in] tol Tolerance used when comparing doubles.
Return values:
comparison Zero if objects contain identical data, non-zero otherwise.
Authors:
Jason McEwen
Definition at line 87 of file purify_image.c.
References purify_image::fov_x, purify_image::fov_y, purify_image::nx, purify_image::ny, and purify_image::pix.
void purify_image_free (purify_image * img)
Free all memory used to store an image.
Parameters:
[in,out] img Image object to free.
Authors:
Jason McEwen
Definition at line 64 of file purify_image.c.
References purify_image::fov_x, purify_image::fov_y, purify_image::nx, purify_image::ny, and purify_image::pix.
Referenced by main().
void purify_image_ind2iuiv (int * ix, int * iy, int ind, purify_image * img) [inline]
Compute 2D image indices from 1D index.
Parameters:
[out] ix First coordinate of 2D image index.
[out] iy Second coordinate of 2D image index.
[in] ind 1D image index.
[in] img Image object containing image sizes.
Authors:
Jason McEwen
Definition at line 45 of file purify_image.c.
References purify_image::nx, purify_image::ny, and PURIFY_ERROR_GENERIC().
void purify_image_ixiy2ind (int * ind, int ix, int iy, purify_image * img) [inline]
Compute 1D image index from 2D indices.
Parameters:
[out] ind 1D image index.
[in] ix First coordinate of 2D image index.
[in] iy Second coordinate of 2D image index.
[in] img Image object containing image sizes.
Authors:
Jason McEwen
Definition at line 24 of file purify_image.c.
References purify_image::nx, purify_image::ny, and PURIFY_ERROR_GENERIC().
int purify_image_readfile (purify_image * img, const char * filename, purify_image_filetype filetype)
Read image from file.
Parameters:
[out] img Image read from the file.
[in] filename Name of the file to read.
[in] filetype Type of file to read.
Return values:
error Zero return indicates no errors.
Note:
Memory for the image is allocated herein and must be freed by the calling routine.
Authors:
Jason McEwen
Definition at line 117 of file purify_image.c.
References purify_image::fov_x, purify_image::fov_y, purify_image::nx, purify_image::ny, purify_image::pix, PURIFY_ERROR_GENERIC(), PURIFY_ERROR_MEM_ALLOC_CHECK(), PURIFY_IMAGE_FILETYPE_FITS, and PURIFY_STRLEN.
Referenced by main().
int purify_image_writefile (purify_image * img, const char * filename, purify_image_filetype filetype)
Write image to file.
Parameters:
[in] img Image to write to the file.
[in] filename Name of the file to write.
[in] filetype Type of file to write.
Return values:
error Zero return indicates no errors.
Authors:
Jason McEwen
Definition at line 202 of file purify_image.c.
References purify_image::nx, purify_image::ny, purify_image::pix, PURIFY_ERROR_GENERIC(), PURIFY_IMAGE_FILETYPE_FITS, and PURIFY_STRLEN.
Referenced by main().