src/purify_sim.c File Reference
purify_sim.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <complex.h>
#include <fftw3.h>
#include "purify_visibility.h"
#include "purify_image.h"
#include "purify_measurement.h"
#include "purify_types.h"
#include "purify_error.h"
#include "purify_ran.h"
Defines
#define VERBOSE 1
Functions
int main (int argc, char *argv[])
Detailed Description
Program to read an image and simulate measured visibilities.
Todo:
[JDM] Set up parameter file.
[JDM/REC] Dirty image is transposed in matlab?!?!
[REC] Define adjoint measurement operators.
[REC] Add normalisation to FFT operators.
Todo:
[REC] Define ifft operators.
Definition in file purify_sim.c.
Define Documentation
#define VERBOSE 1
Definition at line 26 of file purify_sim.c.
Function Documentation
int main (int argc, char * argv[])
Definition at line 29 of file purify_sim.c.
References PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_image_free(), purify_image_readfile(), purify_measurement_opfwd(), purify_sparsemat_free(), purify_visibility_free(), purify_visibility_genranmask(), purify_visibility_mask2vis(), and purify_visibility_writefile().