src/purify_visibility.c File Reference
purify_visibility.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "purify_visibility.h"
#include "purify_sparsemat.h"
#include "purify_utils.h"
#include "purify_ran.h"
#include "purify_error.h"
#include "purify_types.h"
Functions
int purify_compare_ints (const void *a, const void *b)
double purify_visibility_modifypdf (double *pdf, double *new_pdf, int num_elements, int nb_meas, int max_iter)
void purify_visibility_iuiv2ind (int *ind, int iu, int iv, int nx, int ny)
void purify_visibility_ind2iuiv (int *iu, int *iv, int ind, int nx, int ny)
double purify_visibility_du (double fov)
double purify_visibility_umax (double fov, int n)
void purify_visibility_alloc (purify_visibility *vis, int nmeas)
void purify_visibility_copy (purify_visibility *copy, purify_visibility *orig)
void purify_visibility_free (purify_visibility *vis)
int purify_visibility_compare (purify_visibility *vis1, purify_visibility *vis2, double tol)
void purify_visibility_genranmask (purify_sparsemat *mask, int nmeas, int nvis, int seed)
void purify_visibility_mask2ivis (int **ivis, purify_sparsemat *mask)
void purify_visibility_mask2vis (purify_visibility *vis, purify_sparsemat *mask, purify_image *img)
void purify_visibility_ivis2mask (purify_sparsemat *mask, int *ivis, int nmeas, int nvis)
void purify_visibility_ivis2vis (purify_visibility *vis, int *ivis, int nmeas, purify_image *img)
void purify_visibility_snap2grid (purify_visibility *vis, purify_image *img)
void purify_visibility_vis2mask (purify_sparsemat *mask, purify_visibility *vis, purify_image *img)
int purify_visibility_readfile (purify_visibility *vis, const char *filename, purify_visibility_filetype filetype)
int purify_visibility_writefile (purify_visibility *vis, const char *filename, purify_visibility_filetype filetype)
int purify_visibility_vdsmask (purify_sparsemat *mask, purify_image *img, double p, int nmeas_tol, int maxiter_pdf, int maxiter_nmeas, int seed)
Detailed Description
Functionality to operate on vsibilities.
Definition in file purify_visibility.c.
Function Documentation
int purify_compare_ints (const void * a, const void * b)
Integer comparison function for qsort.
Parameters:
[in] a First integer to compare.
[in] b Second integer to compare.
Return values:
diff Difference between integers (i.e. a - b).
Authors:
Jason McEwen
Definition at line 297 of file purify_visibility.c.
Referenced by purify_visibility_genranmask(), purify_visibility_ivis2mask(), and purify_visibility_ivis2vis().
void purify_visibility_alloc (purify_visibility * vis, int nmeas)
Allocate space for nmeas visibilities.
Parameters:
[out] vis Visibility object to allocate.
[in] nmeas Number of visibilities to allocate space for.
Authors:
Jason McEwen
Definition at line 106 of file purify_visibility.c.
References purify_visibility::nmeas, purify_visibility::noise_std, PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_visibility::u, purify_visibility::v, purify_visibility::w, and purify_visibility::y.
Referenced by purify_visibility_copy(), purify_visibility_ivis2vis(), and purify_visibility_readfile().
int purify_visibility_compare (purify_visibility * vis1, purify_visibility * vis2, double tol)
Compare two visibility objects to see whether they hold identical data.
Parameters:
[in] vis1 First visibility object.
[in] vis2 Second visibility object.
[in] tol Tolerance used when comparing doubles.
Return values:
comparison Zero if objects contain identical data, non-zero otherwise.
Authors:
Jason McEwen
Definition at line 185 of file purify_visibility.c.
References purify_visibility::nmeas, purify_visibility::noise_std, purify_visibility::u, purify_visibility::v, purify_visibility::w, and purify_visibility::y.
void purify_visibility_copy (purify_visibility * copy, purify_visibility * orig)
Perform a deep copy of a visibility object.
Parameters:
[out] copy Copied visibility object.
[in] orig Original visibility object to copy.
Note:
Memory for the copied visibility object is allocated herein and must be freed by the calling routine.
Authors:
Jason McEwen
Definition at line 136 of file purify_visibility.c.
References purify_visibility::nmeas, purify_visibility::noise_std, purify_visibility_alloc(), purify_visibility::u, purify_visibility::v, purify_visibility::w, and purify_visibility::y.
double purify_visibility_du (double fov) [inline]
Compute visibility spacing du from field-of-view.
Parameters:
[in] fov Field-of-view.
Return values:
du Visibility spacing.
Authors:
Jason McEwen
Definition at line 78 of file purify_visibility.c.
Referenced by purify_visibility_ivis2vis(), purify_visibility_snap2grid(), and purify_visibility_vis2mask().
void purify_visibility_free (purify_visibility * vis)
Free all memory used to store visibilities.
Parameters:
[in,out] vis Visibility object to free.
Authors:
Jason McEwen
Definition at line 161 of file purify_visibility.c.
References purify_visibility::nmeas, purify_visibility::noise_std, purify_visibility::u, purify_visibility::v, purify_visibility::w, and purify_visibility::y.
Referenced by main().
void purify_visibility_genranmask (purify_sparsemat * mask, int nmeas, int nvis, int seed)
Generate random mask.
Parameters:
[out] mask Sparse matrix representation of mask with dimensions nmeas nvis.
[in] nmeas Number of measurements to retain after masking.
[in] nvis Number of original visibilities.
[in] seed Seed for random number generator.
Note:
Memory for the sparse matrix is allocated herein and must be freed by the calling routine.
Authors:
Jason McEwen
Definition at line 228 of file purify_visibility.c.
References purify_compare_ints(), PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_ran_knuthshuffle(), and purify_visibility_ivis2mask().
void purify_visibility_ind2iuiv (int * iu, int * iv, int ind, int nx, int ny) [inline]
Compute 2D visibility indices from 1D index.
Parameters:
[out] iu First coordinate of 2D visibility index.
[out] iv Second coordinate of 2D visibility index.
[in] ind 1D visibiliy index.
[in] nx Number of visibility indices in first dimension.
[in] ny Number of visibility indices in second dimension.
Authors:
Jason McEwen
Definition at line 58 of file purify_visibility.c.
References PURIFY_ERROR_GENERIC().
Referenced by purify_visibility_ivis2vis().
void purify_visibility_iuiv2ind (int * ind, int iu, int iv, int nx, int ny) [inline]
Compute 1D visibility index from 2D indices.
Parameters:
[out] ind 1D visibiliy index.
[in] iu First coordinate of 2D visibility index.
[in] iv Second coordinate of 2D visibility index.
[in] nx Number of visibility indices in first dimension.
[in] ny Number of visibility indices in second dimension.
Authors:
Jason McEwen
Definition at line 36 of file purify_visibility.c.
References PURIFY_ERROR_GENERIC().
Referenced by purify_measurement_fft_real(), and purify_visibility_vis2mask().
void purify_visibility_ivis2mask (purify_sparsemat * mask, int * ivis, int nmeas, int nvis)
Generate mask from indices of measured visibilities.
Note:
Memory for the sparse matrix is allocated herein and must be freed by the calling routine.
Parameters:
[out] mask Sparse matrix representation of mask with dimensions nmeas nvis.
[in,out] ivis Indices of measured visibilities (will be sorted on ouput).
[in] nmeas Number of measurements to retain after masking.
[in] nvis Number of original visibilities.
Authors:
Jason McEwen
Definition at line 351 of file purify_visibility.c.
References purify_sparsemat::colptr, purify_sparsemat::ncols, purify_sparsemat::nrows, purify_sparsemat::nvals, purify_compare_ints(), PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_sparsemat::rowind, and purify_sparsemat::vals.
Referenced by purify_visibility_genranmask(), purify_visibility_vdsmask(), and purify_visibility_vis2mask().
void purify_visibility_ivis2vis (purify_visibility * vis, int * ivis, int nmeas, purify_image * img)
Compute continuous visibility locations from list of visibility indices and image parameters (i.e. size of image and field-of-view).
Parameters:
[out] vis Object containing continuous visibility locations.
[in,out] ivis Indices of measured visibilities (will be sorted on ouput).
[in] nmeas Number of measurements retained after masking.
[in] img Image containing parameters used to compute continuous visibility locations (i.e. size of image and field-of-fiew).
Note:
Memory for the visibilities is allocated herein and must be freed by the calling routine (note space for measurements is also allocated).
Authors:
Jason McEwen
Definition at line 415 of file purify_visibility.c.
References purify_image::fov_x, purify_image::fov_y, purify_image::nx, purify_image::ny, purify_compare_ints(), PURIFY_ERROR_GENERIC(), purify_visibility_alloc(), purify_visibility_du(), purify_visibility_ind2iuiv(), purify_visibility_umax(), purify_visibility::u, purify_visibility::v, and purify_visibility::w.
Referenced by purify_visibility_mask2vis().
void purify_visibility_mask2ivis (int ** ivis, purify_sparsemat * mask)
Generate indices of measured visibilities from mask.
Parameters:
[out] ivis Indices of measured visibilities.
[in] mask Sparse matrix representation of mask with dimensions nmeas nvis.
Note:
Memory for the visibility indices is allocated herein and must be freed by the calling routine.
Authors:
Jason McEwen
Definition at line 265 of file purify_visibility.c.
References purify_sparsemat::colptr, purify_sparsemat::ncols, purify_sparsemat::nvals, and PURIFY_ERROR_MEM_ALLOC_CHECK().
Referenced by purify_visibility_mask2vis().
void purify_visibility_mask2vis (purify_visibility * vis, purify_sparsemat * mask, purify_image * img)
Compute continuous visibility locations from mask and image parameters (i.e. size of image and field-of-view).
Parameters:
[out] vis Object containing continuous visibility locations.
[in] mask Sparse matrix representation of mask with dimensions nmeas nvis.
[in] img Image containing parameters used to compute continuous visibility locations (i.e. size of image and field-of-fiew).
Note:
Memory for the visibilities is allocated herein and must be freed by the calling routine (note space for measurements is also allocated).
Authors:
Jason McEwen
Definition at line 319 of file purify_visibility.c.
References purify_sparsemat::nvals, purify_visibility_ivis2vis(), and purify_visibility_mask2ivis().
double purify_visibility_modifypdf (double * pdf, double * new_pdf, int num_elements, int nb_meas, int max_iter)
Modify the pdf profile to get a determined number of measurements for variable density sampling.
Parameters:
[in] pdf array of real numbers with the pdf profile (matrix).
[out] new_pdf new pdf profile generated by the function.
[in] num_elements number of elements in the array.
[in] nb_meas target number of measurements.
[in] max_iter maximum number of iterations allowed.
Return values:
alpha return constant of the pdf
Authors:
Rafael Carrillo
Definition at line 821 of file purify_visibility.c.
References purify_utils_maxarray().
Referenced by purify_visibility_vdsmask().
int purify_visibility_readfile (purify_visibility * vis, const char * filename, purify_visibility_filetype filetype)
Read continuous visibilities from file.
Parameters:
[out] vis Visibilities read from the file.
[in] filename Name of the file to read.
[in] filetype Type of file to read.
Return values:
error Zero return indicates no errors.
Note:
Memory for the visibilities is allocated herein and must be freed by the calling routine (note space for measurements is also allocated).
Authors:
Jason McEwen
Definition at line 573 of file purify_visibility.c.
References purify_visibility::noise_std, PURIFY_ERROR_GENERIC(), PURIFY_SQRT2, PURIFY_STRLEN, purify_visibility_alloc(), PURIFY_VISIBILITY_FILETYPE_PROFILE_VIS, PURIFY_VISIBILITY_FILETYPE_PROFILE_WIS, PURIFY_VISIBILITY_FILETYPE_VIS, purify_visibility::u, purify_visibility::v, purify_visibility::w, and purify_visibility::y.
Referenced by main().
void purify_visibility_snap2grid (purify_visibility * vis, purify_image * img)
Snap continuous visibilities to grid.
Parameters:
[in,out] vis Object containing continuous visibility locations. On output the u and v coordinates are snapped to lie on the grid defined by the image parameters.
[in] img Image containing parameters used to compute continuous visibility locations (i.e. size of image and field-of-fiew).
Note:
Only the u and v coordinates of the visibilities are altered (the measurement y and noise standard deviation are NOT altered).
Authors:
Jason McEwen
Definition at line 485 of file purify_visibility.c.
References purify_image::fov_x, purify_image::fov_y, purify_visibility::nmeas, purify_visibility_du(), purify_visibility::u, and purify_visibility::v.
double purify_visibility_umax (double fov, int n) [inline]
Compute maximum visibility frequency from field-of-view and number of samples in given dimension.
Parameters:
[in] fov Field-of-view.
[in] n Number of samples in given dimension.
Return values:
umax Maximum supported frequency.
Authors:
Jason McEwen
Definition at line 93 of file purify_visibility.c.
Referenced by purify_visibility_ivis2vis().
int purify_visibility_vdsmask (purify_sparsemat * mask, purify_image * img, double p, int nmeas_tol, int maxiter_pdf, int maxiter_nmeas, int seed)
Generate the binary mask for variable density sampling in the discrete case. We sample according to the pdf defined by (1-r)^d, where d is choosen to give the required number of samples.
Parameters:
[out] mask Sparse matrix representation of mask.
[in] img Image containing parameters defining full number of visibilities (i.e. size of image).
[in] p Requested visibility coverage (0<p<1). Note that the number of actually number of measured visibilities will differ slight to the requested number.
[in] nmeas_tol Tolerance on the number of actual visibilities (compared to requested number).
[in] maxiter_pdf Maximum number of iterations when computing d (typically set to 200).
[in] maxiter_nmeas Maximum number of iterations when testing actual number of measurements.
[in] seed Positive integer seed for random number generator.
Return values:
nmeas Actual number of measurements for the VDS mask constructed (may differ slightly to p*img->nx*img->ny).
Note:
Memory for the mask is allocated herein and must be freed by the calling routine.
Authors:
Rafael Carrillo
Jason McEwen
Definition at line 900 of file purify_visibility.c.
References purify_image::nx, purify_image::ny, PURIFY_ERROR_GENERIC(), PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_ran_ran2(), purify_utils_ifftshift_1d(), purify_visibility_ivis2mask(), and purify_visibility_modifypdf().
void purify_visibility_vis2mask (purify_sparsemat * mask, purify_visibility * vis, purify_image * img)
Compute mask from continuous visibility locations and image parameters (i.e. size of image and field-of-view).
Parameters:
[out] mask Sparse matrix representation of mask with dimensions nmeas nvis.
[in] vis Object containing continuous visibility locations.
[in] img Image containing parameters used to compute continuous visibility locations (i.e. size of image and field-of-fiew).
Authors:
Jason McEwen
Definition at line 515 of file purify_visibility.c.
References purify_image::fov_x, purify_image::fov_y, purify_visibility::nmeas, purify_image::nx, purify_image::ny, PURIFY_ERROR_MEM_ALLOC_CHECK(), purify_visibility_du(), purify_visibility_iuiv2ind(), purify_visibility_ivis2mask(), purify_visibility::u, and purify_visibility::v.
int purify_visibility_writefile (purify_visibility * vis, const char * filename, purify_visibility_filetype filetype)
Write continuous visibilities to file.
Parameters:
[in] vis Visibilities to write to the file.
[in] filename Name of the file to write.
[in] filetype Type of file to write.
Return values:
error Zero return indicates no errors.
Authors:
Jason McEwen
Definition at line 745 of file purify_visibility.c.
References purify_visibility::nmeas, purify_visibility::noise_std, PURIFY_ERROR_GENERIC(), PURIFY_STRLEN, PURIFY_VISIBILITY_FILETYPE_PROFILE_VIS, PURIFY_VISIBILITY_FILETYPE_PROFILE_WIS, PURIFY_VISIBILITY_FILETYPE_VIS, purify_visibility::u, purify_visibility::v, purify_visibility::w, and purify_visibility::y.